# Travis CI configuration file
# http://travis-ci.org

sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks
    - pandoc

install:
  - eval $(luarocks path --bin)
  - luarocks install --local luacheck

# Remove unit tests folders
before-script: rm -rf `find . -name "_tests"`

# Run luacheck to make sure there is not syntax error left in the add-on
script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"

deploy:
  provider: script
  script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -p 100707 -w 24465 -g 9.0.1 -o
  on:
    tags: true

notifications:
  email:
    on_failure: always
    on_success: never

cache:
  apt: true
  directories:
    - $HOME/.luarocks
