-- Copyright The Total RP 3 Extended Authors
-- SPDX-License-Identifier: Apache-2.0

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- ALL MODIFICATIONS TO THIS FILE WILL BE LOST.

local L;

L = {
	["ALL"] = "Todo",
	["BINDING_NAME_TRP3_INVENTORY"] = "Abrir inventario del personaje",
	["BINDING_NAME_TRP3_MAIN_CONTAINER"] = "Abrir bolsa principal",
	["BINDING_NAME_TRP3_QUEST_ACTION"] = "Acción de misión: interactuar",
	["BINDING_NAME_TRP3_QUEST_LISTEN"] = "Acción de misión: escuchar",
	["BINDING_NAME_TRP3_QUEST_LOOK"] = "Acción de misión: inspeccionar",
	["BINDING_NAME_TRP3_QUEST_TALK"] = "Acción de misión: hablar",
	["BINDING_NAME_TRP3_QUESTLOG"] = "Abrir el diario de misiones de TRP3",
	["BINDING_NAME_TRP3_SEARCH_FOR_ITEMS"] = "Buscar objetos",
	["CA_ACTION_CONDI"] = "Editor de condiciones de la acción",
	["CA_ACTION_REMOVE"] = "¿Eliminar esta acción?",
	["CA_ACTIONS"] = "Acciones",
	["CA_ACTIONS_ADD"] = "Añadir acción",
	["CA_ACTIONS_COND"] = "Editar condición",
	["CA_ACTIONS_COND_OFF"] = "Esta acción no está condicionada.",
	["CA_ACTIONS_COND_ON"] = "Esta acción está condicionada.",
	["CA_ACTIONS_COND_REMOVE"] = "Eliminar condición",
	["CA_ACTIONS_EDITOR"] = "Editor de acción",
	["CA_ACTIONS_NO"] = "Sin acción",
	["CA_ACTIONS_SELECT"] = "Seleccionar tipo de acción",
	["CA_DESCRIPTION"] = "Resumen de campaña",
	["CA_DESCRIPTION_TT"] = "Este breve resumen será visible en la página de campaña, en el diario de misiones.",
	["CA_ICON"] = "Icono de campaña",
	["CA_ICON_TT"] = "Seleccionar icono de campaña",
	["CA_IMAGE"] = "Retrato de campaña",
	["CA_IMAGE_TT"] = "Seleccionar retrato de campaña",
	["CA_LINKS_ON_START"] = "Al inicio de la campaña",
	["CA_LINKS_ON_START_TT"] = [=[Activado |cff00ff00once|r cuando el jugador empiece tu campaña, ya sea por primera vez o reiniciándola en el diario de misiones.

|cff00ff00Este es un buen lugar para activar tu primera misión.]=],
	["CA_NAME"] = "Nombre de campaña",
	["CA_NAME_NEW"] = "Nueva campaña",
	["CA_NAME_TT"] = "Este es el nombre de tu campaña. Aparece en el diario de misiones.",
	["CA_NO_NPC"] = "PNJ no personalizado",
	["CA_NPC"] = "Lista de PNJs de la campaña",
	["CA_NPC_ADD"] = "Añadir PNJ personalizado",
	["CA_NPC_AS"] = "Duplicar",
	["CA_NPC_EDITOR"] = "Editor de PNJ",
	["CA_NPC_EDITOR_DESC"] = "Descripción de PNJ",
	["CA_NPC_EDITOR_NAME"] = "Nombre de PNJ",
	["CA_NPC_ID"] = "ID de PNJ",
	["CA_NPC_ID_TT"] = [=[Por favor, introduce la ID del PNJ a personalizar.

|cff00ff00Para obtener la ID del PNJ que tienes en objetivo, escribe este comando en el chat: /trp3 getID]=],
	["CA_NPC_NAME"] = "Nombre de PNJ por defecto",
	["CA_NPC_REMOVE"] = "¿Deseas eliminar la personalización para este NPC?",
	["CA_NPC_TT"] = "Puedes personalizar PNJs para darles un nombre, icono y descripción. Esta personalización será visible cuando el jugador tenga tu campaña activa.",
	["CA_NPC_UNIT"] = "PNJ personalizado",
	["CA_QE_ID"] = "Cambiar ID de misión",
	["CA_QE_ST_ID"] = "Cambiar ID del paso de misión",
	["CA_QUEST_ADD"] = "Añadir misión",
	["CA_QUEST_CREATE"] = [=[Por favor, introduce la ID de misión. No puedes tener dos misiones con la misma ID en la misma campaña.

|cffff9900Por favor, ten en cuenta que las misiones serán listadas en orden alfabético de ID en la lista de misiones.

|cff00ff00Es una buena práctica empezar tus ID por quest_#, donde # es el número de la misión en la campaña.]=],
	["CA_QUEST_EXIST"] = "Ya existe una misión con la ID %s.",
	["CA_QUEST_NO"] = "Sin misiones",
	["CA_QUEST_REMOVE"] = "¿Eliminar esta misión?",
	["CL_CAMPAIGN_PROGRESSION"] = "Progresión por %s",
	["CL_CREATION"] = "Creación extendida",
	["CL_EXTENDED_CAMPAIGN"] = "Campaña extendida",
	["CL_EXTENDED_ITEM"] = "Objeto extendido",
	["CL_IMPORT"] = "Importar en la base de datos",
	["CL_IMPORT_ITEM_BAG"] = "Añade el objeto a tu bolsa",
	["CL_TOOLTIP"] = "Crear link de chat",
	["COM_NPC_ID"] = "obtener id de pnj",
	["COND_COMPLETE"] = "Completar expresión lógica",
	["COND_CONDITIONED"] = "Condicionado",
	["COND_EDITOR"] = "Editor de condiciones",
	["COND_EDITOR_EFFECT"] = "Editor de Condición de efecto",
	["COND_LITT_COMP"] = "Todos los tipos de comparación",
	["COND_NUM_COMP"] = "Sólo comparación numérica",
	["COND_NUM_FAIL"] = "Debes tener dos operandos numéricos si usas el comparador numérico.",
	["COND_PREVIEW_TEST"] = "Prueba preliminar",
	["COND_PREVIEW_TEST_TT"] = "Muestra en el chat la evaluación de la prueba basada en la situación actual.",
	["COND_TEST_EDITOR"] = "Editor de prueba",
	["COND_TESTS"] = "Pruebas de condición",
	["CONF_MAIN"] = "Extended",
	["CONF_MUSIC_ACTIVE"] = "Reproducir música local",
	["CONF_MUSIC_ACTIVE_TT"] = [=[La música local es música reproducida por otros jugadores (por ejemplo, mediante un objeto) a cierto rango en metros.

Desactívalo si no quieres escuchar estas músicas.

|cnWARNING_FONT_COLOR:Ten en cuenta que no escucharás música de jugadores ignorados.|r

|cnGREEN_FONT_COLOR:Ten en cuenta que todas las músicas son interrumpibles mediante la opción Historial de sonido en la barra de atajos de TRP3.|r]=],
	["CONF_SOUNDS"] = "Música/sonido local",
	["CONF_SOUNDS_ACTIVE"] = "Reproducir sonidos locales",
	["CONF_SOUNDS_ACTIVE_TT"] = [=[Los sonidos locales son sonidos reproducidos por otros jugadores (por ejemplo, mediante un objeto) a cierto rango en metros.

Desactívalo si no quieres escuchar estos sonidos.

|cnWARNING_FONT_COLOR:Ten en cuenta que no escucharás sonidos de jugadores ignorados.|r

|cnGREEN_FONT_COLOR:Ten en cuenta que todos los sonidos son interrumpibles mediante la opción Historial de sonido en la barra de atajos de TRP3.|r]=],
	["CONF_SOUNDS_MAXRANGE"] = "Rango máximo de reproducción",
	["CONF_SOUNDS_MAXRANGE_TT"] = [=[Establece el rango máximo (en metros) en que escucharás sonido/música local.

|cnGREEN_FONT_COLOR:Útil para evitar a gente que use sonidos en todo el continente.|r

|cnWARNING_FONT_COLOR:¡Cero significa sin límite!|r]=],
	["CONF_UNIT"] = "Unidades",
	["CONF_UNIT_WEIGHT"] = "Unidad de peso",
	["CONF_UNIT_WEIGHT_1"] = "Gramos",
	["CONF_UNIT_WEIGHT_2"] = "Libras",
	["CONF_UNIT_WEIGHT_3"] = "Patatas",
	["CONF_UNIT_WEIGHT_TT"] = "Define cómo se muestran los valores de peso.",
	["DB"] = "Base de datos",
	["DB_ACTIONS"] = "Acciones",
	["DB_ADD_COUNT"] = "¿Cuántas unidades de %s deseas añadir al inventario?",
	["DB_ADD_ITEM"] = "Añadir al inventario principal",
	["DB_ADD_ITEM_TT"] = "Añade unidades de este objeto en tu bolsa principal (o inventario principal si no tienes una bolsa principal con el personaje).",
	["DB_BACKERS"] = "Base de datos de backers (%s)",
	["DB_BACKERS_LIST"] = "Créditos",
	["DB_BROWSER"] = "Buscador de objetos",
	["DB_COPY_ID_TT"] = "Muestra la ID del objeto en un popup para copiar/pegar.",
	["DB_COPY_TT"] = "Copia toda la información de este objeto y sus hijos para poderse añadir como objeto interno de otro objeto",
	["DB_CREATE_CAMPAIGN"] = "Crear campaña",
	["DB_CREATE_CAMPAIGN_TEMPLATES_BLANK"] = "Campaña en blanco",
	["DB_CREATE_CAMPAIGN_TEMPLATES_BLANK_TT"] = "Una plantilla en blanco. Para aquellos que les gusta comenzar desde cero.",
	["DB_CREATE_CAMPAIGN_TEMPLATES_FROM"] = "Creado desde...",
	["DB_CREATE_CAMPAIGN_TEMPLATES_FROM_TT"] = "Copia creada de campaña existente",
	["DB_CREATE_CAMPAIGN_TT"] = "Iniciar la creación de una campaña",
	["DB_CREATE_ITEM"] = "Crear objeto",
	["DB_CREATE_ITEM_TEMPLATES"] = "O seleccionar una plantilla",
	["DB_CREATE_ITEM_TEMPLATES_BLANK"] = "Objeto en blanco",
	["DB_CREATE_ITEM_TEMPLATES_BLANK_TT"] = [=[Plantilla en blanco.
Para aquellos a quienes les gusta empezar de cero.]=],
	["DB_CREATE_ITEM_TEMPLATES_CONTAINER"] = "Contenedor",
	["DB_CREATE_ITEM_TEMPLATES_CONTAINER_TT"] = [=[Una plantilla para objetos de tipo contenedor.
Un contenedor puede almacenar otros objetos.]=],
	["DB_CREATE_ITEM_TEMPLATES_DOCUMENT"] = "Documento",
	["DB_CREATE_ITEM_TEMPLATES_DOCUMENT_TT"] = [=[Una plantilla con un objeto interno de tipo documento.
Útil para crear rápidamente un libro o un pergamino.]=],
	["DB_CREATE_ITEM_TEMPLATES_EXPERT"] = "Objeto experto",
	["DB_CREATE_ITEM_TEMPLATES_EXPERT_TT"] = "Una plantilla en blanco experta. Para usuarios con experiencia haciendo creaciones.",
	["DB_CREATE_ITEM_TEMPLATES_FROM"] = "Crear desde...",
	["DB_CREATE_ITEM_TEMPLATES_FROM_TT"] = "Crear una copia de un objeto existente.",
	["DB_CREATE_ITEM_TEMPLATES_QUICK"] = "Creación rápida",
	["DB_CREATE_ITEM_TEMPLATES_QUICK_TT"] = [=[Rápidamente crea un objeto sencillo sin efectos.
Añade una unidad de este objeto a tu bolsa principal.]=],
	["DB_CREATE_ITEM_TT"] = "Seleccionar plantilla para el nuevo objeto",
	["DB_DELETE_TT"] = "Elimina este objeto y sus hijos.",
	["DB_EXPERT_TT"] = "Cambia este objeto al modo experto, permitiendo personalizaciones más complejas.",
	["DB_EXPORT"] = "Exportación rápida",
	["DB_EXPORT_DONE"] = [=[Tu objeto ha sido exportado en un archivo llamado |cff00ff00totalRP3_Extended_ImpExport.lua|r localizado en:

World of Warcraft\WTF\
account\YOUR_ACCOUNT\SavedVariables

¡Puedes compartir este archivo con tus amigos!

Con él pueden seguir el proceso de importación situado en la |cff00ff00pestaña de Base de datos total|r.]=],
	["DB_EXPORT_HELP"] = "Código para el objeto %s (tamaño: %0.1f kB)",
	["DB_EXPORT_MODULE_NOT_ACTIVE"] = "Importación/exportación completa de objetos: Por favor, habilita el complemento \"totalRP3_Extended_ImpExport\" primero.",
	["DB_EXPORT_TOO_LARGE"] = [=[Este objeto es demasiado grande para ser exportado de este modo. Por favor, usa la opción "Exportación completa".

Tamaño: %0.1f kB.]=],
	["DB_EXPORT_TT"] = [=[Serializa el contenido del objeto para ser compartido fuera del juego.

Solo funciona con objetos pequeños (menos de 20 kB una vez serializados). Para objetos de mayor tamaño, usa la opción "exportación completa".]=],
	["DB_FILTERS"] = "Filtros de búsqueda",
	["DB_FILTERS_CLEAR"] = "Limpiar",
	["DB_FILTERS_NAME"] = "Nombre de objeto",
	["DB_FILTERS_OWNER"] = "Creado por",
	["DB_FULL"] = "Base de datos total (%s)",
	["DB_FULL_EXPORT"] = "Exportación completa",
	["DB_FULL_EXPORT_TT"] = [=[Realiza una exportación completa de este objeto sin importar su tamaño.

Esto provocará una recarga de la interfaz para forzar el guardado de los ficheros del add-on.]=],
	["DB_HARD_SAVE"] = "Forzar guardado",
	["DB_HARD_SAVE_TT"] = "Recarga la interfaz del juego para forzar que las variables guardadas se escriban en el disco.",
	["DB_IMPORT"] = "Importación rápida de objetos",
	["DB_IMPORT_CONFIRM"] = [=[Este objeto ha sido serializado en una versión diferente a la tuya de Total RP 3 Extended.

Versión TRP3E del objeto: %s
Tu versión de TRP3E: %s

|cffff9900Esto podría provocar incompatibilidades.
¿Continuar con la importación de todas formas?]=],
	["DB_IMPORT_DONE"] = "¡Objeto importado con éxito!",
	["DB_IMPORT_EMPTY"] = [=[No hay objetos para importar en el fichero |cff00ff00totalRP3_Extended_ImpExport.lua|r.

Este fichero debe colocarse en el siguiente directorio |cffff9900antes de lanzar el juego|r:

World of Warcraft\WTF\
account\YOUR_ACCOUNT\SavedVariables]=],
	["DB_IMPORT_ERROR1"] = "El objeto no pudo ser deserializado.",
	["DB_IMPORT_FULL"] = "Importación total",
	["DB_IMPORT_FULL_CONFIRM"] = [=[¿Quieres importar el siguiente objeto?

%s
%s
Por |cff00ff00%s|r
Versión %s]=],
	["DB_IMPORT_FULL_TT"] = "Importa el fichero |cff00ff00totalRP3_Extended_ImpExport.lua|r.",
	["DB_IMPORT_ITEM"] = "Importar objeto",
	["DB_IMPORT_TT"] = "Pega aquí un objeto previamente serializado.",
	["DB_IMPORT_VERSION"] = [=[Estás importando una versión anterior de un objeto ya existente.

Versión de importación: %s
Tu versión: %s

|cffff9900¿Confirmas los cambios?]=],
	["DB_IMPORT_WORD"] = "Importar",
	["DB_LIST"] = "Lista de creaciones",
	["DB_LOCALE"] = "Localización del objeto",
	["DB_MY"] = "Mi base de datos (%s)",
	["DB_MY_EMPTY"] = [=[No has creado ningún objeto todavía.
¡Usa los botones de abajo para dar rienda suelta a tu creatividad!]=],
	["DB_OTHERS"] = "Base de datos de jugadores (%s)",
	["DB_OTHERS_EMPTY"] = "Aquí se colocarán los objetos creados por otros jugadores.",
	["DB_REMOVE_OBJECT_POPUP"] = [=[Por favor, confirma la eliminación del objeto:
ID: |cff00ffff"%s"|r
|cff00ff00[%s]|r

|cffff9900Aviso: ¡Esta acción no puede revertirse!]=],
	["DB_RESULTS"] = "Buscar resultados",
	["DB_SECURITY_TT"] = "Muestra todos los parámetros de seguridad para este objeto. Desde aquí puedes permitir o prevenir ciertos efectos indeseados.",
	["DB_TO_EXPERT"] = "Convertir a modo experto",
	["DB_WARNING"] = [=[|cffff0000¡¡¡ Aviso !!!

|cffff9900¡No olvides guardar los cambios antes de volver a la lista de la base de datos!]=],
	["DEBUG_QUEST_START"] = "Iniciar misión",
	["DEBUG_QUEST_START_USAGE"] = "Uso: /trp3 debug_quest_start questID",
	["DEBUG_QUEST_STEP"] = "Ir al paso de la misión.",
	["DEBUG_QUEST_STEP_USAGE"] = "Uso: /trp3 debug_quest_step questID stepID",
	["DI_ATTR_TT"] = "Solo marca esta opción si quieres cambiar este atributo en relación al paso anterior de la escena.",
	["DI_ATTRIBUTE"] = "Cambiar atributos",
	["DI_BKG"] = "Imagen de fondo",
	["DI_BKG_TT"] = [=[Se usará como fondo para este paso de la escena. Por favor introduce la ruta completa de la textura.

Si cambias el fondo durante la escena habrá una transición entre los diferentes fondos.]=],
	["DI_CHOICE"] = "Opción",
	["DI_CHOICE_CONDI"] = "Condición de opción",
	["DI_CHOICE_STEP"] = "Ir al paso",
	["DI_CHOICE_STEP_TT"] = [=[Introduce el número del paso de la escena que quieres mostrar si el jugador selecciona esta opción.

|cff00ff00Si se deja vacío o con un valor inválido, seleccionar esta opción hará terminar la escena (y activar el evento "Al finalizar").]=],
	["DI_CHOICE_TT"] = [=[Introducir el texto para esta opción.

|cff00ff00Dejar en blanco para deshabilitar esta opción.]=],
	["DI_CHOICES"] = "Elecciones del jugador",
	["DI_CHOICES_TT"] = "Configurar las elecciones de jugador para este paso.",
	["DI_CONDI_TT"] = [=[Establece una condición para esta opción. Si la condición no se cumple cuando se muestren las opciones, la opción asociada a esta no será visible.

|cff00ff00Click: Configurar condición
Click-derecho: Eliminar condición]=],
	["DI_DIALOG"] = "Diálogo",
	["DI_DISTANCE"] = "Distancia máxima (metros)",
	["DI_DISTANCE_TT"] = [=[Define la distancia máxima (en yardas) en la que el jugador puede alejarse de la escena una vez comenzada. Pasado este límite se cerrará automáticamente (y activará el evento "Al cancelar").

|cff00ff00Cero implica que no hay límite.

|cffff9900No funciona en instancias/campos de batalla/arenas desde el parche 7.1.]=],
	["DI_END"] = "Paso final",
	["DI_END_TT"] = [=[Marca este paso como el último. Cuando se llegue a éste se finalizará la escena (y se activará el evento "Al terminar").

|cff00ff00Útil si has usado opciones de jugadores en esta escena.]=],
	["DI_FRAME"] = "Decoración",
	["DI_GET_ID"] = "ID del objetivo",
	["DI_GET_ID_TT"] = "Copia la ID del PNJ objetivo. Solo funciona si tu objetivo actual es un PNJ.",
	["DI_HISTORY"] = "Historial de escenas",
	["DI_HISTORY_TT"] = "Click para mostrar/ocultar el panel del historial, mostrando las líneas anteriores de la escena.",
	["DI_IMAGE"] = "Imagen",
	["DI_IMAGE_TT"] = [=[Muestra una imagen en el centro del marco de la escena. Esta imagen aparecerá lentamente.
Por favor, introduce la ruta completa de la textura.

Para ocultar la imagen más adelante simplemente no informes este atributo.]=],
	["DI_LEFT_UNIT"] = "Cambiar modelo de la izquierda",
	["DI_LINKS_ONEND"] = "Al finalizar la escena",
	["DI_LINKS_ONEND_TT"] = [=[Se activa cuando la escena actual finaliza.

|cff00ff00Esto puede ocurrir cuando se llega al último paso o permitiendo que el jugador elija una opción con un "ir al paso" sin informar o desconocido.

|cffff0000Esto NO se activará si el jugador cancela la escena manualmente cerrando el marco.]=],
	["DI_LINKS_ONSTART"] = "Al comenzar la escena",
	["DI_LINKS_ONSTART_TT"] = [=[Se activa cuando comienza la escena.

|cffff9900Ten en cuenta que este flujo de trabajo se activará ANTES de mostrar el primer paso de la escena.]=],
	["DI_LOOT"] = "Esperar a despojar objetos",
	["DI_LOOT_TT"] = "Si el flujo de trabajo seleccionado a la izquierda muestra una selección de objetos al jugador, puedes marcar este parámetro para prevenir que el jugador avance a la siguiente escena si éste no ha despojado todos los objetos.",
	["DI_MODELS"] = "Modelos",
	["DI_NAME"] = "Cambiar el nombre del portavoz",
	["DI_NAME_DIRECTION"] = "Dirección del diálogo",
	["DI_NAME_DIRECTION_TT"] = "Determina donde colocar la burbuja de diálogo y el nombre, y qué modelo animar. Selecciona \"Ninguno\" para ocultar completamente la burbuja de diálogo y el nombre.",
	["DI_NAME_TT"] = [=[El nombre del personaje hablando en este paso.

Solo es necesario si la dirección del diálogo seleccionada arriba es "Ninguno".]=],
	["DI_NEXT"] = "Índice del siguiente paso",
	["DI_NEXT_TT"] = [=[Puedes indicar qué paso será mostrado después de este.

|cff00ff00Dejarlo en blanco mostrará el siguiente paso en orden secuencial. Únicamente usa este campo si necesitas 'saltar' a otro paso. Útil cuando se usan "opciones".]=],
	["DI_RIGHT_UNIT"] = "Cambiar modelo de la derecha",
	["DI_STEP"] = "Paso de la escena",
	["DI_STEP_ADD"] = "Añadir paso",
	["DI_STEP_EDIT"] = "Editar paso",
	["DI_STEP_TEXT"] = "Texto del paso",
	["DI_STEPS"] = "Pasos de la escena",
	["DI_UNIT_TT"] = [=[Establece el modelo a mostrar:

- Dejar vacío para ocultar el modelo
- "player" para usar el modelo del jugador
- "target" para usar el modelo del objetivo
- Cualquier número para cargar un ID de PNJ]=],
	["DI_WAIT_LOOT"] = "Por favor, despoja todos los objetos",
	["DISCLAIMER"] = "{h1:c} Leer atentamente {/h1} Crear elementos y misiones requiere tiempo y energía y siempre es terrible cuando pierde todo el trabajo duro que ha hecho. Todos los complementos en World of Warcraft pueden almacenar datos, pero existen limitaciones: • Existe un límite de tamaño de datos desconocido para los datos adicionales (dependiendo del hecho de que esté ejecutando un cliente de 32 o 64 bits, entre otras cosas). • Alcanzar este límite puede borrar todos los datos guardados del complemento. • Eliminar el proceso, forzar el cierre del cliente del juego (Alt + F4) o bloquearse puede dañar los datos guardados del complemento. • Incluso si sale del juego correctamente, siempre existe la posibilidad de que el juego no pueda guardar los datos adicionales y corromperlos. Con respecto a todo eso, recomendamos ENCARECIDAMENTE hacer una copia de seguridad regular de sus datos guardados de complementos. Puede encontrar aquí un tutorial sobre cómo encontrar todos los datos guardados: {link*https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables*¿Dónde se almacena mi información?} Puede encontrar aquí un tutorial sobre cómo sincronizar sus datos con un servicio en la nube : {link*https://github.com/Total-RP/Total-RP-3/wiki/How-to-backup-and-synchronize-your-add-ons-settings-using-a-cloud-service*Cómo hacer una copia de seguridad y sincronizar la configuración de sus complementos usando un servicio en la nube} Por favor, comprenda que ya no responderemos a comentarios o tickets relacionados con borrados de datos. No es porque no queramos ayudar, sino porque no podemos hacer nada para restaurar los datos borrados. ¡Gracias y disfrute de Total RP 3 Extended! {p:r} El equipo TRP3 {/p}",
	["DISCLAIMER_OK"] = "Por la presente firmo este contrato con mi sangre",
	["DO_EMPTY"] = "Documento vacío",
	["DO_LINKS_ONCLOSE"] = "Al cerrar",
	["DO_LINKS_ONCLOSE_TT"] = "Se activa cuando el documento se cierra por el jugador u otro evento (por ejemplo a través de un efecto del flujo de trabajo)",
	["DO_LINKS_ONOPEN"] = "Al abrir",
	["DO_LINKS_ONOPEN_TT"] = "Se activa cuando el documento se muestra al jugador.",
	["DO_NEW_DOC"] = "Documento",
	["DO_PAGE_ADD"] = "Añadir página",
	["DO_PAGE_BORDER"] = "Borde",
	["DO_PAGE_BORDER_1"] = "Pergamino",
	["DO_PAGE_COUNT"] = "Página %s / %s",
	["DO_PAGE_EDITOR"] = "Editor de página: página %s",
	["DO_PAGE_FIRST"] = "Primera página",
	["DO_PAGE_FONT"] = "%s fuente",
	["DO_PAGE_HEIGHT"] = "Altura de página",
	["DO_PAGE_HEIGHT_TT"] = "La altura de la página en píxeles. Por favor, ten en cuenta que algunos fondos sólo se verán bien a determinado ancho/alto y pueden deformarse.",
	["DO_PAGE_LAST"] = "Última página",
	["DO_PAGE_MANAGER"] = "Gestor de páginas",
	["DO_PAGE_NEXT"] = "Página siguiente",
	["DO_PAGE_PREVIOUS"] = "Página anterior",
	["DO_PAGE_REMOVE"] = "Eliminar página",
	["DO_PAGE_REMOVE_POPUP"] = "¿Eliminar la página %s ?",
	["DO_PAGE_RESIZE"] = "Redimensionable",
	["DO_PAGE_RESIZE_TT"] = [=[Permite al usuario cambiar el tamaño del marco.

|cffff9900Asegúrate que tu diseño pueda leerse y no dependa del alto/ancho.

|cff00ff00Ten en cuenta que el usuario no podrá reducir el tamaño del marco por debajo del ancho y alto por defecto.]=],
	["DO_PAGE_TILING"] = "Mosaico de fondo",
	["DO_PAGE_TILING_TT"] = "Determina si el fondo se repetirá vertical y horizontalmente. En caso contrario, la textura se expandirá hasta ocupar todo el marco.",
	["DO_PAGE_WIDTH"] = "Ancho de página",
	["DO_PAGE_WIDTH_TT"] = "El ancho de la página en píxeles. Por favor, ten en cuenta que algunos fondos sólo se verán bien a determinado ancho/alto y pueden deformarse.",
	["DO_PARAMS_CUSTOM"] = "Parámetros personalizados de página",
	["DO_PARAMS_GLOBAL"] = "Parámetros por defecto",
	["DO_PARAMS_GLOBAL_TT"] = "Cambia los parámetros por defecto del documento. Estos parámetros se usarán para todas las páginas que no usen parámetros de página propios.",
	["DO_PREVIEW"] = "Clic para vista previa",
	["DOC_UNKNOWN_ALERT"] = "No se puede abrir el documento. (Missing class)",
	["DR_DELETED"] = "Destruido: %s x%d",
	["DR_DROP_ERROR_INSTANCE"] = "No se pueden soltar objetos en una estancia",
	["DR_DROPED"] = "Soltado en el suelo: %s x%d",
	["DR_NOTHING"] = "No se hallaron objetos en este área.",
	["DR_POPUP"] = "Soltar aquí",
	["DR_POPUP_ASK"] = [=[Total RP 3

Selecciona qué quieres hacer con el objeto:
%s]=],
	["DR_POPUP_REMOVE"] = "Destruir",
	["DR_POPUP_REMOVE_TEXT"] = "¿Destruir este objeto?",
	["DR_RESULTS"] = "Objetos %s encontrados",
	["DR_SEARCH_BUTTON"] = "Buscar objetos | cff00ff00my | r",
	["DR_SEARCH_BUTTON_TT"] = "Buscar objetos en el área dentro de 15 yardas.",
	["DR_STASHED"] = "Esconder: %s x%d",
	["DR_STASHES"] = "Escondites",
	["DR_STASHES_CREATE"] = "Crear un escondite aquí",
	["DR_STASHES_CREATE_TT"] = "Crea un escondite donde estás parado.",
	["DR_STASHES_DROP"] = "No se puedes colocar un objeto en el escondite de otra persona.",
	["DR_STASHES_EDIT"] = "Editar escondite",
	["DR_STASHES_ERROR_INSTANCE"] = "No puedes crear un escondite en esta instancia",
	["DR_STASHES_ERROR_OUT_SYNC"] = "Escondite fuera de sincronización, por favor intentalo de nuevo",
	["DR_STASHES_ERROR_SYNC"] = "El escondite no está sincronizado",
	["DR_STASHES_FOUND"] = "Escondites encontrados: %s",
	["DR_STASHES_FULL"] = "Este escondite está lleno.",
	["DR_STASHES_HIDE"] = "Ocultar del escaneo",
	["DR_STASHES_HIDE_TT"] = "Este escondite no aparecerá en el escaneo de mapas de otros jugadores. Ten en cuenta que siempre podrán acceder si saben dónde está.",
	["DR_STASHES_MAX"] = "máx 50 caracteres",
	["DR_STASHES_NAME"] = "Escondite",
	["DR_STASHES_NOTHING"] = "No se han encontrado escondites en esta zona.",
	["DR_STASHES_OWNER"] = "Dueño",
	["DR_STASHES_OWNERSHIP"] = "Reclamar propiedad",
	["DR_STASHES_OWNERSHIP_PP"] = "Tomar posesión de este escondite? Este personaje se mostrará como propietario de este escondite cuando otros jugadores lo busquen.",
	["DR_STASHES_REMOVE"] = "Eliminar escondite",
	["DR_STASHES_REMOVE_PP"] = [=[¿Eliminar este escondite?
|cffff9900¡Todos los objetos que están dentro se perderán!]=],
	["DR_STASHES_REMOVED"] = "Escondite eliminado.",
	["DR_STASHES_RESYNC"] = "Resincronizar",
	["DR_STASHES_SCAN"] = "Rastrear escondites de los jugadores",
	["DR_STASHES_SCAN_MY"] = "Rastrear mis escondites",
	["DR_STASHES_SEARCH"] = "Buscar escondites de | cff00ff00players | r ",
	["DR_STASHES_SYNC"] = "Sincronizando...",
	["EDITOR_CONFIRM"] = "Confirmar",
	["EDITOR_HEIGHT"] = "Altura",
	["EDITOR_ICON"] = "Seleccionar icono",
	["EDITOR_ICON_SELECT"] = "Haz clic para seleccionar un icono.",
	["EDITOR_ID_COPY"] = "Copiar ID",
	["EDITOR_MAIN"] = "Principal",
	["EDITOR_MORE"] = "Más",
	["EDITOR_PREVIEW"] = "Previsualizar",
	["EDITOR_WARNINGS"] = [=[Hay %s avisos.

|cffff9900%s|r

¿Guardar de todos modos?]=],
	["EDITOR_WIDTH"] = "Ancho",
	["EFFECT_CAT_CAMERA"] = "Cámara",
	["EFFECT_CAT_CAMERA_LOAD"] = "Cargar cámara",
	["EFFECT_CAT_CAMERA_ZOOM_IN"] = "Acercar cámara",
	["EFFECT_CAT_CAMERA_ZOOM_OUT"] = "Alejar cámara",
	["EFFECT_CAT_CAMPAIGN"] = "Campaña y misión",
	["EFFECT_CAT_SOUND"] = "Sonido y música",
	["EFFECT_CAT_SPEECH"] = "Diálogos y emociones",
	["EFFECT_DIALOG_ID"] = "ID de escena",
	["EFFECT_DIALOG_START"] = "Iniciar escena",
	["EFFECT_DIALOG_START_PREVIEW"] = "Iniciar escena %s.",
	["EFFECT_DOC_CLOSE"] = "Cerrar documento",
	["EFFECT_DOC_CLOSE_TT"] = "Cierra el documento actualmente abierto. No hace nada si no hay ningún documento abierto.",
	["EFFECT_DOC_DISPLAY"] = "Mostrar documento",
	["EFFECT_DOC_DISPLAY_TT"] = "Muestra un documento al jugador. Si ya hay un documento abierto, este será reemplazado.",
	["EFFECT_DOC_ID"] = "ID del documento",
	["EFFECT_ITEM_ADD"] = "Añadir objeto",
	["EFFECT_ITEM_ADD_CRAFTED"] = "Creado",
	["EFFECT_ITEM_ADD_ID"] = "ID de objeto",
	["EFFECT_ITEM_ADD_PREVIEW"] = "Añadir %sx %s",
	["EFFECT_ITEM_ADD_QT"] = "Cantidad",
	["EFFECT_ITEM_ADD_TT"] = "Añade objetos a tu bolsa.",
	["EFFECT_ITEM_BAG_DURABILITY"] = "Dañar/reparar Contenedor",
	["EFFECT_ITEM_BAG_DURABILITY_METHOD"] = "Tipo",
	["EFFECT_ITEM_BAG_DURABILITY_METHOD_DAMAGE"] = "Daño",
	["EFFECT_ITEM_BAG_DURABILITY_METHOD_HEAL"] = "Reparar",
	["EFFECT_ITEM_BAG_DURABILITY_VALUE"] = "Punto de durabilidad",
	["EFFECT_ITEM_CONSUME"] = "Consumir objeto",
	["EFFECT_ITEM_CONSUME_TT"] = "Consume el objeto usado y lo destruye.",
	["EFFECT_ITEM_COOLDOWN"] = "Iniciar cuenta atras",
	["EFFECT_ITEM_COOLDOWN_PREVIEW"] = "Duración: %s segundo(s)",
	["EFFECT_ITEM_COOLDOWN_TT"] = "Iniciar cuenta atrás para este objeto",
	["EFFECT_ITEM_DICE"] = "Tirar dados",
	["EFFECT_ITEM_DICE_PREVIEW"] = "Tirando dado/s %s",
	["EFFECT_ITEM_DICE_ROLL"] = "Lanzar dados",
	["EFFECT_ITEM_DICE_ROLL_VAR"] = "Nombre de la variable (opcional)",
	["EFFECT_ITEM_REMOVE"] = "Destruir objeto",
	["EFFECT_ITEM_REMOVE_PREVIEW"] = "Destruye %sx %s",
	["EFFECT_ITEM_REMOVE_TT"] = "Destruye objetos de tu inventario.",
	["EFFECT_ITEM_SOURCE_1"] = "Todo el inventario",
	["EFFECT_ITEM_SOURCE_3"] = "Este objeto",
	["EFFECT_OPERATION"] = "Operación",
	["EFFECT_OPERATION_TYPE"] = "Tipo de operación",
	["EFFECT_OPERATION_TYPE_ADD"] = "Sumar",
	["EFFECT_OPERATION_TYPE_DIV"] = "Dividir",
	["EFFECT_OPERATION_TYPE_MULTIPLY"] = "Multiplicar",
	["EFFECT_OPERATION_TYPE_SUB"] = "Restar",
	["EFFECT_OPERATION_VALUE"] = "Valor de la operación",
	["EFFECT_PROMPT_DEFAULT"] = "Valor por defecto",
	["EFFECT_QUEST_GOTOSTEP_PREVIEW"] = "Ir al paso %s.",
	["EFFECT_QUEST_OBJ_ID"] = "ID del objetivo",
	["EFFECT_QUEST_REVEAL_OBJ_DONE"] = "Completar objetivo",
	["EFFECT_QUEST_START_ID"] = "ID de misión",
	["EFFECT_RANDSUM"] = "Invocar mascota de batalla aleatoria",
	["EFFECT_SCRIPT_I_EFFECT"] = "Insertar efecto",
	["EFFECT_SCRIPT_SCRIPT"] = "Código Lua",
	["EFFECT_SECURE_MACRO_ACTION_NAME"] = "Ejecutar macro",
	["EFFECT_SECURE_MACRO_BLOCKED"] = "Efecto de macro bloqueado:",
	["EFFECT_SECURE_MACRO_HELP_TITLE"] = "Comandos de macro",
	["EFFECT_SIGNAL"] = "Enviar señal",
	["EFFECT_SIGNAL_ID"] = "ID de señal",
	["EFFECT_SIGNAL_VALUE"] = "Valor de la señal",
	["EFFECT_SOUND_ID_LOCAL"] = "Reproducir sonido local",
	["EFFECT_SOUND_ID_SELF_CHANNEL"] = "Canal",
	["EFFECT_SOUND_ID_SELF_CHANNEL_SFX"] = "SFX",
	["EFFECT_SOUND_ID_SELF_ID"] = "ID del sonido",
	["EFFECT_SOUND_MUSIC_LOCAL"] = "Reproducir música local",
	["EFFECT_SOUND_MUSIC_SELF"] = "Reproducir música",
	["EFFECT_SOUND_MUSIC_SELF_PREVIEW"] = "Reproducir música: %s",
	["EFFECT_SOUND_MUSIC_STOP"] = "Detener música",
	["EFFECT_SOUND_PLAY"] = "Reproducir",
	["EFFECT_SOURCE"] = "Fuente",
	["EFFECT_SOURCE_CAMPAIGN"] = "Activar campaña",
	["EFFECT_SOURCE_OBJECT"] = "Objeto",
	["EFFECT_SPEECH_NPC"] = "Diálogo: PNJ",
	["EFFECT_SPEECH_NPC_DEFAULT"] = "¿Quieres hacer un muñeco de nieve?",
	["EFFECT_SPEECH_NPC_NAME"] = "Nombre del PNJ",
	["EFFECT_SPEECH_NPC_NAME_TT"] = "El nombre del PNJ.",
	["EFFECT_SPEECH_PLAYER"] = "Diálogo: Jugador",
	["EFFECT_SPEECH_PLAYER_DEFAULT"] = "¡Deja que el fuego te consuma!",
	["EFFECT_SPEECH_PLAYER_TT"] = "Hace que el jugador hable, grite o haga un /e emote.",
	["EFFECT_SPEECH_TYPE"] = "Tipo de diálogo",
	["EFFECT_SUMMOUNT"] = "Invocar montura",
	["EFFECT_SUMMOUNT_ACTION_TT"] = "Seleccionar una montura específica",
	["EFFECT_SUMMOUNT_TT"] = "Invoca una montura específica si está disponible.",
	["EFFECT_TEXT"] = "Mostrar texto",
	["EFFECT_TEXT_PREVIEW"] = "Texto mostrado",
	["EFFECT_TEXT_TEXT"] = "Texto",
	["EFFECT_TEXT_TEXT_DEFAULT"] = "Tu texto",
	["EFFECT_TEXT_TEXT_TT"] = "Texto para mostrar.",
	["EFFECT_TEXT_TYPE"] = "Tipo de texto",
	["EFFECT_TEXT_TYPE_3"] = "Texto de alerta de banda",
	["EFFECT_TEXT_TYPE_4"] = "Mensaje de alerta",
	["EFFECT_VAR_OPERAND_CONFIG"] = "Configuración del valor",
	["EFFECT_VAR_OPERAND_CONFIG_NO"] = "No hay configuración para este valor",
	["EX_SOUND_HISTORY"] = "Historial de sonido",
	["EX_SOUND_HISTORY_CLEAR"] = "Limpiar",
	["EX_SOUND_HISTORY_EMPTY"] = "No se ha reproducido ningún sonido.",
	["EX_SOUND_HISTORY_REPLAY"] = "Reproducir de nuevo",
	["EX_SOUND_HISTORY_STOP"] = "Detener",
	["EX_SOUND_HISTORY_STOP_ALL"] = "Detener todo",
	["IN_INNER"] = "Objetos internos",
	["IN_INNER_ADD"] = "Añadir objeto interno",
	["IN_INNER_ADD_COPY"] = "Añadir copia de objeto existente",
	["IN_INNER_ADD_NEW"] = "Crear nuevo objeto",
	["IN_INNER_COPY_ACTION"] = "Copiar contenido del objeto",
	["IN_INNER_DELETE_TT"] = "Eliminar este objeto interno del objeto principal.",
	["IN_INNER_EMPTY"] = [=[No hay objetos internos

Puedes añadir uno usando el botón de añadir que hay más abajo.]=],
	["IN_INNER_ENTER_ID"] = "Introduce la ID del nuevo objeto interno",
	["IN_INNER_HELP"] = [=[Los objetos internos son objetos almacenados en un objeto principal.
Empecemos con algunos ejemplos:
|cffff9900
- Quieres crear un objeto que sea un rifle con objetos que hagan de balas para cargarlo. El rifle sería el objeto principal, mientras que las balas serían los objetos internos para el rifle.
- Un objeto de correo que abra un documento. El documento sería el objeto interno y el correo el principal.
- Creando misiones: cualquier objeto/documento/excena que uses en una misión podrían ser objetos internos de la misión.
|rLas ventajas de usar objetos internos son múltiples:
|cff00ff00
- La información de los objetos internos se almacena dentro de la información del objeto principal. Eso significa que comparten el mismo número de versión y que su información se intercambia a la vez que la información del objeto principal.
- Puedes determinar libremente la ID del objeto interno dado que usará la ID del objeto principal como prefijo, ya que no puedes tener dos objetos internos con la misma ID dentro del mismo objeto principal.
- Usar un objeto interno mejora el rendimiento.
- Es más fácil administrar y navegar a través de objetos si están guardados en objetos principales. Puedes ver un objeto principal como si fuera una carpeta en la que guardaras archivos.
|rAsí que es fácil: cuando quieras crear un objeto, pregúntate si no sería mejor tenerlo como objeto interno para otro objeto o misión.
|cff00ff00Además: ¡los documentos y las escenas solo pueden ser objetos internos!]=],
	["IN_INNER_HELP_TITLE"] = "¿Qué son los objetos internos?",
	["IN_INNER_ID"] = [=[Por favor, introduce una nueva ID para el objeto interno |cff00ff00[%s]|r.

ID anterior: |cff00ffff"%s"|r]=],
	["IN_INNER_ID_ACTION"] = "Cambiar ID",
	["IN_INNER_ID_COPY"] = "Copiar",
	["IN_INNER_ID_COPY_TT"] = "Puedes copiar tu objeto interno y pegarlo en otro objeto principal.",
	["IN_INNER_LIST"] = "Lista de objetos internos",
	["IN_INNER_NO_AVAILABLE"] = "¡Esta ID interna no está disponible!",
	["IN_INNER_PASTE_ACTION"] = "Pegar el contenido del objeto",
	["IN_INNER_PASTE_CONFIRM"] = "¿Reemplazar el contenido de este objeto interno con el copiado anteriormente?",
	["IN_INNER_S"] = "Objeto interno",
	["INV_PAGE_CAMERA_CONFIG"] = [=[Parámetros de cámara:
  Rotación: %.2f]=],
	["INV_PAGE_CHARACTER_INSPECTION"] = "Inspección de personaje",
	["INV_PAGE_CHARACTER_INSPECTION_TT"] = "Inspeccionar el inventario del personaje.",
	["INV_PAGE_CHARACTER_INV"] = "Inventario",
	["INV_PAGE_EDIT_ERROR1"] = "Debes ser el autor de este objeto para editarlo.",
	["INV_PAGE_INV_OPEN"] = "Abrir inventario",
	["INV_PAGE_LOOT_ALL"] = "Despojar todo",
	["INV_PAGE_MARKER"] = [=[Marcar posición:
   x: %.2f
   y: %.2f]=],
	["INV_PAGE_PLAYER_INV"] = "Inventario de %s",
	["INV_PAGE_QUICK_SLOT_TT"] = "Este espacio se usará como contenedor primario.",
	["INV_PAGE_SEQUENCE"] = "ID de secuencia",
	["INV_PAGE_TOTAL_VALUE"] = "Valor total de los objetos",
	["INV_PAGE_TOTAL_VALUE_TT"] = [=[Este es el valor de tu inventario.

No es la cantidad de "monedas", sino el valor total estimado de todos los objetos en tu inventario.]=],
	["INV_PAGE_WAIT"] = "Esperando respuesta",
	["INV_PAGE_WEAR_ACTION_RESET"] = "Reiniciar configuración",
	["INV_PAGE_WEAR_TT"] = [=[Puedes ponerte este objeto.
La zona verde indica el lugar del objeto en el personaje.]=],
	["IT_CO_DURABILITY"] = "Durabilidad",
	["IT_CO_DURABILITY_TT"] = [=[Determina la vida máxima de tu contenedor. Un contenedor puede perder vida con el tiempo o ser dañado, pero también puede ser reparado con los objetos adecuados.

|cff00ff00Cero significa invulnerable.]=],
	["IT_CO_MAX"] = "Peso máximo (en gramos)",
	["IT_CO_SIZE"] = "Tamaño del contenedor",
	["IT_CO_SIZE_COLROW"] = "%s | 1fila;filas; por %s columnas",
	["IT_CON"] = "Contenedor",
	["IT_CON_CAN_INNER"] = "¡No puedes colocar un contenedor dentro de sí mismo!",
	["IT_CON_ERROR_TRADE"] = "No puedes soltar este contenedor si no está vacío.",
	["IT_CON_ERROR_TYPE"] = "Este contenedor no puede guardar ese tipo de objeto.",
	["IT_CON_OPEN"] = "Abrir/Cerrar contenedor",
	["IT_CON_TT"] = "Contenedor (%d/%d huecos usados)",
	["IT_CONTAINER_TT"] = [=[Fija este objeto como contenedor. Los contenedores pueden guardar otros objetos.

|cff00ff00El contendor puede ser configurado en la pestaña 'Contenedor' de este editor.]=],
	["IT_CONVERT_TO_NORMAL"] = "Pasar al modo normal",
	["IT_CRAFTED"] = "Creado",
	["IT_DISPLAY_ATT"] = "Mostrar atributos",
	["IT_DOC_ACTION"] = "Leer documento",
	["IT_DR_SOUND"] = "Sonido al soltarlo",
	["IT_EX_DOWNLOAD"] = "Descargar",
	["IT_EX_DOWNLOADING"] = "Descargando: %0.1f %%",
	["IT_EX_EMPTY"] = "Nada que intercambiar",
	["IT_EX_EMPTY_DRAG"] = "Puedes arrastrar y soltar objetos aquí.",
	["IT_EX_TRADE_BUTTON"] = "Abrir intercambio",
	["IT_EX_TRADE_BUTTON_TT"] = "Abre la ventana de intercambio para iniciar el comercio de objetos con este jugador.",
	["IT_FIELD_NAME"] = "Nombre del objeto",
	["IT_FIELD_QUALITY"] = "Calidad de objeto",
	["IT_INV_ERROR_CANT_HERE"] = "No puedes poner objetos aquí.",
	["IT_INV_ERROR_FULL"] = "%s está lleno.",
	["IT_INV_ERROR_MAX"] = "No puedes llevar más %s.",
	["IT_INV_GOT"] = "Recibido: %s x%d",
	["IT_INV_SCAN_MY_ITEMS"] = "Rastrear mis objetos",
	["IT_NEW_NAME"] = "Nuevo objeto",
	["IT_NEW_NAME_CO"] = "Nuevo contenedor",
	["IT_ON_USE"] = "En uso",
	["IT_PU_SOUND"] = "Sonido al cogerlo",
	["IT_PU_SOUND_1183"] = "Bolsa",
	["IT_PU_SOUND_1184"] = "Libro",
	["IT_PU_SOUND_1185"] = "Tela",
	["IT_PU_SOUND_1186"] = "Comida",
	["IT_PU_SOUND_1187"] = "Hierba",
	["IT_PU_SOUND_1188"] = "Cadena",
	["IT_PU_SOUND_1189"] = "Carne",
	["IT_PU_SOUND_1190"] = "Metal grande",
	["IT_PU_SOUND_1191"] = "Metal pequeño",
	["IT_PU_SOUND_1192"] = "Papel",
	["IT_PU_SOUND_1193"] = "Anillo",
	["IT_PU_SOUND_1194"] = "Roca",
	["IT_PU_SOUND_1195"] = "Cadena pequeña",
	["IT_PU_SOUND_1196"] = "Varita",
	["IT_PU_SOUND_1197"] = "Líquido",
	["IT_PU_SOUND_1198"] = "Palo pequeño",
	["IT_PU_SOUND_1199"] = "Palo grande",
	["IT_PU_SOUND_1221"] = "Gemas",
	["IT_SOULBOUND_TT"] = "Este objeto se ligará al jugador cuando se coloque en su inventario y no podrá ser intercambiado o dejado en el suelo.",
	["IT_STACK"] = "Apilable",
	["IT_TRIGGER_ON_USE"] = "En uso",
	["IT_TT_VALUE"] = "Valor del objeto",
	["IT_TT_VALUE_FORMAT"] = "Valor del objeto (en %s)",
	["IT_TT_WEIGHT"] = "Peso del objeto",
	["IT_TT_WEIGHT_FORMAT"] = "Peso del objeto (en gramos)",
	["IT_UNIQUE_COUNT"] = "Unidades máximas",
	["IT_UNIQUE_COUNT_TT"] = "Fija el máximo de unidades que un personaje puede poseer. Debe ser mayor que 0.",
	["IT_USE"] = "Usable",
	["IT_WEARABLE"] = "Equipable",
	["IT_WEARABLE_TT"] = " Habilita este elemento para la función de inspección y te permite colocarlo con precisión en tu personaje. |cffff9900Si esta marca está marcada, las personas podrán ver este artículo en tu inventario si te inspeccionan, incluso si no configuras la posición del artículo. ",
	["ITEM_ID"] = "ID del objeto",
	["MODE_EXPERT"] = "Experto",
	["MODE_NORMAL"] = "Normal",
	["MODE_QUICK"] = "Rápido",
	["NEW_EXTENDED_VERSION"] = "|cffff9900Hay disponible una nueva versión de TRP3:Extended (%s). |cff00ff00¡Revísalo en Curse!",
	["NPC_EMOTES"] = "emotea",
	["NPC_SAYS"] = "dice",
	["NPC_WHISPERS"] = "susurra",
	["NPC_YELLS"] = "grita",
	["OP_COMP_EQUALS"] = "es igual a",
	["OP_COMP_GREATER"] = "es mayor a",
	["OP_COMP_GREATER_OR_EQUALS"] = "es mayor o igual a",
	["OP_COMP_LESSER"] = "es menor a",
	["OP_COMP_LESSER_OR_EQUALS"] = "es menor o igual a",
	["OP_COMP_NEQUALS"] = "no es igual a",
	["OP_CONFIGURE"] = "Configurar",
	["OP_CURRENT"] = "Valor actual",
	["OP_DIRECT_VALUE"] = "Valor directo",
	["OP_EVAL_VALUE"] = "Valor evaluado",
	["OP_NUMERIC"] = "Valor numérico",
	["OP_OP_CHAR_ACHIEVEMENT"] = "Logro",
	["OP_OP_CHAR_ACHIEVEMENT_ACC"] = "Cuenta",
	["OP_OP_CHAR_ACHIEVEMENT_ACC_TT"] = "Revisa si el personaje de esta cuenta ha completado el logro",
	["OP_OP_CHAR_ACHIEVEMENT_CHAR"] = "Personaje",
	["OP_OP_CHAR_ACHIEVEMENT_CHAR_TT"] = "Revisa si el personaje actual ha completado el logro",
	["OP_OP_CHAR_ACHIEVEMENT_ID"] = "ID de logro",
	["OP_OP_CHAR_ACHIEVEMENT_ID_TT"] = "La ID numérica del logro que quieres revisar.",
	["OP_OP_CHAR_ACHIEVEMENT_PREVIEW"] = "%s completado por |cffff9900%s",
	["OP_OP_CHAR_ACHIEVEMENT_TT"] = "Revisa si la cuenta ha completado el logro especificado.",
	["OP_OP_CHAR_ACHIEVEMENT_WHO"] = "Completado por",
	["OP_OP_CHAR_CAM_DISTANCE"] = "Distancia de cámara",
	["OP_OP_CHAR_CAM_DISTANCE_TT"] = "La distancia de cámara del jugador. 0 si la vista es en primera persona.",
	["OP_OP_CHAR_FLYING"] = "El personaje está volando.",
	["OP_OP_CHAR_FLYING_TT"] = "Revisa si el personaje está volando.",
	["OP_OP_CHAR_MINIMAP"] = "Texto del minimapa",
	["OP_OP_CHAR_MOUNTED"] = "El personaje está montado",
	["OP_OP_CHAR_MOUNTED_TT"] = "Revisa si el personaje está montado.",
	["OP_OP_CHAR_RESTING"] = "El personaje está descansando",
	["OP_OP_CHAR_RESTING_TT"] = "Revisa si el personaje está descansando. Estás descansando si estás en una posada o en una capital como Forjaz u Orgrimmar.",
	["OP_OP_CHAR_STEALTH"] = "El personaje está en sigilo",
	["OP_OP_CHAR_STEALTH_TT"] = "Revisa si el personaje está en sigilo.",
	["OP_OP_CHAR_SUBZONE"] = "Nombre de la sub-zona",
	["OP_OP_CHAR_SUBZONE_TT"] = [=[El nombre de la sub-zona donde se encuentra actualmente el personaje.

|cffff9900Aviso: El texto depende de la localización del cliente.]=],
	["OP_OP_CHAR_SWIMMING"] = "El personaje está nadando",
	["OP_OP_CHAR_SWIMMING_TT"] = "Revisa si el personaje está nadando. No necesitan estar bajo el agua.",
	["OP_OP_CHAR_ZONE"] = "Nombre de la zona",
	["OP_OP_CHAR_ZONE_TT"] = [=[El nombre de la zona donde se encuentra actualmente el personaje.

|cffff9900Aviso: El texto depende de la localización del cliente.]=],
	["OP_OP_CHECK_VAR_N"] = "Valor numérico variable",
	["OP_OP_CHECK_VAR_N_PREVIEW"] = "|cff00ffff%s: |cffff9900(n)|r %s",
	["OP_OP_CHECK_VAR_PREVIEW"] = "|cff00ffff%s:|r %s",
	["OP_OP_DISTANCE_CURRENT"] = "Usar posición actual",
	["OP_OP_DISTANCE_X"] = "Coordenada X",
	["OP_OP_DISTANCE_Y"] = "Coordenada Y",
	["OP_OP_INV_COUNT_ANY"] = "Cualquier objeto",
	["OP_OP_INV_WEIGHT"] = "Peso total del contenedor",
	["OP_OP_INV_WEIGHT_TT"] = "|cff00ff00El peso actual del contenedor (su propio peso además del contenido).",
	["OP_OP_QUEST_NPC"] = "La unidad es un PNJ de campaña",
	["OP_OP_QUEST_OBJ"] = "Objetivo de misión",
	["OP_OP_QUEST_OBJ_CURRENT"] = "Objetivos actuales de misión",
	["OP_OP_QUEST_OBJ_PREVIEW"] = "Objetivo %s de %s",
	["OP_OP_QUEST_STEP"] = "Paso actual de la misión",
	["OP_OP_QUEST_STEP_PREVIEW"] = "%s paso actual",
	["OP_OP_RANDOM"] = "Aleatorio",
	["OP_OP_RANDOM_FROM"] = "De",
	["OP_OP_RANDOM_TO"] = "Para",
	["OP_OP_TIME_HOUR"] = "Tiempo: Hora",
	["OP_OP_TIME_HOUR_TT"] = "La hora actual del día, hora del servidor.",
	["OP_OP_TIME_MINUTE"] = "Tiempo: Minuto",
	["OP_OP_TIME_MINUTE_TT"] = "El minuto actual de la hora, hora del servidor.",
	["OP_OP_UNIT_CLASS"] = "Clase de la unidad",
	["OP_OP_UNIT_CLASSIFICATION"] = "Clasificación de la unidad",
	["OP_OP_UNIT_DEAD"] = "La unidad está muerta",
	["OP_OP_UNIT_DISTANCE_INSPECT"] = "La unidad está cerca (inspeccionar)",
	["OP_OP_UNIT_DISTANCE_TRADE"] = "La unidad está cerca (comerciar)",
	["OP_OP_UNIT_EXISTS"] = "La unidad existe",
	["OP_OP_UNIT_FACTION"] = "Facción de la unidad",
	["OP_OP_UNIT_GUILD"] = "Nombre de hermandad de la unidad",
	["OP_OP_UNIT_GUILD_RANK"] = "Rango de hermandad de la unidad",
	["OP_OP_UNIT_GUILD_RANK_TT"] = "|cff00ff00El rango de hermandad de la unidad (de pertenecer a una hermandad).",
	["OP_OP_UNIT_GUILD_TT"] = "|cff00ff00El nombre de hermandad de la unidad (si tuviera).",
	["OP_OP_UNIT_HEALTH"] = "Salud de la unidad",
	["OP_OP_UNIT_ID"] = "ID de la unidad",
	["OP_OP_UNIT_ISPLAYER"] = "La unidad es un jugador",
	["OP_OP_UNIT_LEVEL"] = "Nivel de la unidad",
	["OP_OP_UNIT_LEVEL_TT"] = "|cff00ff00Nivel de la unidad.",
	["OP_OP_UNIT_NAME"] = "Nombre de la unidad",
	["OP_OP_UNIT_POSITION_X"] = "Posición x de la unidad",
	["OP_OP_UNIT_POSITION_X_TT"] = [=[Devuelve la coordenada X de una unidad.

Solo funciona con juagdores.

|cffff9900No funciona en mazmorras/campos de batalla/arenas desde el parche 7.1.]=],
	["OP_OP_UNIT_POSITION_Y"] = "Posición y de la unidad",
	["OP_OP_UNIT_POSITION_Y_TT"] = [=[Devuelve la coordenada Y de una unidad.

Solo funciona con juagdores.

|cffff9900No funciona en mazmorras/campos de batalla/arenas desde el parche 7.1.]=],
	["OP_OP_UNIT_RACE"] = "Raza de la unidad",
	["OP_OP_UNIT_SPEED"] = "Velocidad de la unidad",
	["OP_PREVIEW"] = "Previsualizar valor",
	["OP_UNIT"] = "Tipo de unidad",
	["OP_UNIT_NPC"] = "PNJ",
	["OP_UNIT_PLAYER"] = "Jugador",
	["OP_UNIT_TARGET"] = "Objetivo",
	["QE_ACTION"] = "Acción de misión",
	["QE_ACTION_NO_CURRENT"] = "No tienes ninguna campaña activa. Deberías activar una antes de intentar realizar una acción.",
	["QE_ACTIONS_TYPE_INTERRACT"] = "Interactuar",
	["QE_ACTIONS_TYPE_LISTEN"] = "Escuchar",
	["QE_ACTIONS_TYPE_LOOK"] = "Inspeccionar",
	["QE_ACTIONS_TYPE_TALK"] = "Hablar",
	["QE_BUTTON"] = "Abrir historial de misiones",
	["QE_CAMPAIGN"] = "Campaña",
	["QE_CAMPAIGN_CURRENT"] = "Campaña actual",
	["QE_CAMPAIGN_CURRENT_NO"] = "Sin campañas activas.",
	["QE_CAMPAIGN_EMPTY"] = "Esta campaña no tiene misiones.",
	["QE_CAMPAIGN_LIST"] = "%s campañas disponibles",
	["QE_CAMPAIGN_PAUSE"] = "Pausar campaña actual.",
	["QE_CAMPAIGN_RESET"] = "Reiniciar campaña",
	["QE_CAMPAIGN_START"] = "Iniciando campaña |cff00ff00[%s]|r.",
	["QE_CAMPAIGN_UNSTARTED"] = [=[Aún no has iniciado esta campaña.
Haz clic en el botón superior derecho "Iniciar" para iniciarla.]=],
	["QE_CAMPAIGNS"] = "Campañas",
	["QE_COMPLETED"] = "Completado",
	["QE_DESCRIPTION"] = "Resumen de la misión",
	["QE_DESCRIPTION_TT"] = "Este breve resumen será visible en la página de la misión, en el historial de misiones.",
	["QE_LINKS_ON_START"] = "Al inicio de la misión",
	["QE_MACRO"] = "Crear macro",
	["QE_MACRO_MAX"] = "No puedes tener más macros. Libera un hueco de macro antes de intentarlo de nuevo, por favor.",
	["QE_MACRO_TT"] = "Crea una macro para este tipo de acción y la pone en tu ratón para que la coloques en cualquier barra de acción.",
	["QE_NAME"] = "Nombre de misión",
	["QE_NAME_NEW"] = "Nueva misión",
	["QE_NAME_TT"] = "El nombre de tu misión, tal y como aparecerá en el historial de misiones.",
	["QE_NEW"] = "Nueva misión revelada",
	["QE_NOACTION_ACTION"] = "No hay nada para hacer.",
	["QE_NOACTION_LISTEN"] = "No oyes nada especial.",
	["QE_NOACTION_LOOK"] = "No ves nada especial.",
	["QE_NOACTION_TALK"] = "No hay nada que decir.",
	["QE_NPC"] = "PNJ de campaña",
	["QE_OBJ"] = "Objetivos de misión",
	["QE_OBJ_ADD"] = "Añadir objetivo",
	["QE_OBJ_AUTO_TT"] = "Automáticamente revela este objetivo cuando se desbloquea la misión en el historial de misiones.",
	["QE_OBJ_ID"] = "ID de objetivo",
	["QE_OBJ_ID_TT"] = "Esta es la ID de tu objetivo. No puedes tener dos objetivos con la misma ID en la misma misión.",
	["QE_OBJ_NO"] = "Sin objetivo de misión",
	["QE_OBJ_REMOVE"] = "¿Eliminar este objetivo de misión?",
	["QE_OBJ_SINGULAR"] = "Objetivo de misión",
	["QE_PROGRESS"] = "Progresión",
	["QE_QUEST"] = "Misión",
	["QE_QUEST_LIST"] = "Misiones para esta campaña",
	["QE_QUEST_OBJ_AND_HIST"] = "Objetivos e historial",
	["QE_QUEST_OBJ_FINISHED"] = "|cffffff00Objetivo completado: |cff00ff00%s",
	["QE_QUEST_OBJ_REVEALED"] = "|cffffff00Nuevo objetivo: |cff00ff00%s",
	["QE_QUEST_OBJ_UPDATED"] = "|cffffff00Objetivo actualizado: |cff00ff00%s",
	["QE_QUEST_START"] = "Iniciando misión |cff00ff00[%s]|r.",
	["QE_QUEST_TT_STEP"] = [=[|cffffff00Actualmente:|r
"%s"]=],
	["QE_QUESTS"] = "Misiones",
	["QE_RESET_CONFIRM"] = [=[¿Quieres reiniciar esta campaña?

Perderás el progreso de TODAS las misiones de esta campaña.

Recuerda que guardarás los objetos que hayas ganado durante esta campaña.]=],
	["QE_ST_AUTO_REVEAL"] = "Paso inicial",
	["QE_ST_AUTO_REVEAL_TT"] = "Marca este paso como el paso inicial cuando se desbloquea la misión en el historial de misiones.",
	["QE_ST_END"] = "Paso final",
	["QE_ST_END_TT"] = "Marcar este paso como el paso final de esta misión. Cuando se alcanza este paso, la misión se marcará automáticamente como completada en el historial de misiones.",
	["QE_STEP"] = "Pasos de misión",
	["QE_STEP_ADD"] = "Añadir paso de misión",
	["QE_STEP_EXIST"] = "Ya hay un paso con la ID %s.",
	["QE_STEP_LIST"] = "Pasos para esta misión",
	["QE_STEP_LIST_CURRENT"] = "Misiones disponibles",
	["QE_STEP_LIST_FINISHED"] = "Misiones completadas",
	["QE_STEP_NAME_NEW"] = "Nuevo paso de misión",
	["QE_STEP_NO"] = "Sin paso de misión",
	["QE_STEP_REMOVE"] = "¿Eliminar este paso?",
	["QUEST_ID"] = "ID de misión",
	["ROOT_CREATED"] = "Creado por %s en %s",
	["ROOT_CREATED_BY"] = "Creado por",
	["ROOT_CREATED_ON"] = "Creado el",
	["ROOT_GEN_ID"] = "ID generada",
	["ROOT_ID"] = "ID del objeto",
	["ROOT_SAVED"] = "Última edición por %s el %s",
	["ROOT_VERSION"] = "Versión",
	["SEC_EFFECT_BLOCKED"] = "Efecto(s) bloqueado(s)",
	["SEC_HIGH"] = "Alto",
	["SEC_LEVEL"] = "Nivel de seguridad",
	["SEC_LEVEL_DETAILS"] = "Detalles de seguridad",
	["SEC_LEVEL_DETAILS_ACCEPTED"] = "Aceptado",
	["SEC_LEVEL_DETAILS_ALL"] = "Cambiar seguridad para todos los objetos",
	["SEC_LEVEL_DETAILS_ALL_TT"] = "Aceptar la ejecución de este efecto para todos los objetos, ahora y en el futuro.",
	["SEC_LEVEL_DETAILS_BLOCKED"] = "Bloqueado",
	["SEC_LEVEL_DETAILS_FROM"] = "Aceptar siempre al recibir de %s.",
	["SEC_LEVEL_DETAILS_THIS"] = "Cambiar seguridad para estos objetos",
	["SEC_LEVEL_DETAILS_THIS_TT"] = "Aceptar la ejecución de este efecto sólo para este objeto.",
	["SEC_LOW"] = "Bajo",
	["SEC_MEDIUM"] = "Medio",
	["SEC_REASON_DISMOUNT"] = "Desmontar",
	["SEC_REASON_DISMOUNT_WHY"] = [=[Este objeto podría obligarte a desmontar.

|cffff9900Puede que no quieras eso... ¡sobre todo si vas en montura voladora!]=],
	["SEC_REASON_MACRO"] = "Ejecutar una macro",
	["SEC_REASON_SOUND"] = "Reproducir un sonido",
	["SEC_REASON_SOUND_WHY"] = [=[Este objeto podría hacer sonar un sonido o música que se oirá por los usuarios de TRP3:E cerca de ti.


|cffff9900Puede que el sonido sea indeseable si es particularmente molesto o repetitivo. Si ese es el caso, podrían bloquearte.

|cff00ff00Si te bloquean, solo tú oirás el sonido o la música.]=],
	["SEC_RESOLUTION_ALL"] = "Para todos los objetos",
	["SEC_RESOLUTION_AUTHOR"] = "Eres el autor",
	["SEC_RESOLUTION_THIS_OBJECT"] = "Solo para este objeto",
	["SEC_TT_COMBO"] = "Alt + Clic derecho:|cffff9900 Configurar seguridad.",
	["SEC_TT_COMBO_2"] = "Configurar seguridad",
	["SET_TT_DETAILS_1"] = "Mantén pulsado Alt para mostrar más",
	["SET_TT_DETAILS_2"] = "%s aviso(s)",
	["SET_TT_OLD"] = [=[Este objeto ha sido creado con una versión antigua de Extended (v %s).
Puede que haya incompatibilidades.]=],
	["SET_TT_SECURED_2_1"] = "Ver más detalles.",
	["SPECIFIC"] = "Objeto específico",
	["SPECIFIC_MODE"] = "Modo",
	["TB_TOOLS_TT"] = "Crea tus propios items y misiones.",
	["TU_AC_2"] = "Evaluación de acciones",
	["TU_CS_4"] = "Escenas y flujos de trabajo",
	["TU_CS_5"] = "Previsualizar",
	["TU_DB_1_TEXT"] = [=[|cff00ff00Bienvenido al tutorial de la base de datos.|r

Esta es la base de datos, donde se almacenan todos los objetos.

Un objeto contiene toda la información de un item, documento, campaña/misión/paso o escena.]=],
	["TU_DB_2"] = "Tipos de base de datos",
	["TU_DB_6"] = "Crear objeto",
	["TU_DB_7"] = "Línea de objeto",
	["TU_DB_7_TEXT"] = "Cada línea representa un objeto. Puedes hacer clic para editarlo o clic derecho para realizar varias acciones.",
	["TU_EL_4_TEXT"] = "Los |cff00ff00eventos de juego|r solo están disponibles para campañas, misiones y pasos de misiones.",
	["TU_IT_1_TEXT"] = [=[|cff00ff00Bienvenido al tutorial de creación de objetos.|r

Un objeto es aquel que puedes almacenar en el inventario de tu personaje (o dejarlo en el suelo).

Aquí, en la ventana principal, puedes definir todos los atributos básicos para tu objeto.]=],
	["TU_IT_2"] = "Mostrar atributos",
	["TU_IT_3_TEXT"] = [=[Puedes escribir notas que te ayuden a recordar qué quieres hacer con el objeto.

Estas notas pueden ayudar también a otros que quieran crear un objeto basado en el tuyo.]=],
	["TU_IT_4"] = "Atributos de juego",
	["TU_TITLE"] = "Tutorial",
	["TU_WO_4"] = "Añadir un efecto",
	["TU_WO_4_TEXT"] = [=[Efectos como "reproducir un sonido", "mostrar un texto" o "iniciar una escena".

Hay MUCHOS efectos, ¡todos explicados en su propia herramienta!]=],
	["TU_WO_5"] = "Añadir una condición",
	["TU_WO_6"] = "Añadir retraso",
	["TYPE"] = "Tipo",
	["TYPE_CAMPAIGN"] = "Campaña",
	["TYPE_DIALOG"] = "Cinemática",
	["TYPE_DOCUMENT"] = "Documento",
	["TYPE_ITEM"] = "Objeto",
	["TYPE_ITEMS"] = "Objeto(s)",
	["TYPE_LOOT"] = "Botín",
	["TYPE_QUEST"] = "Misión",
	["UNIT_POTATOES"] = "patatas",
	["WO_ACTIONS_LINKS"] = "Enlaces de acción",
	["WO_ADD"] = "Crear flujo de trabajo",
	["WO_COMMON_EFFECT"] = "Efectos comunes",
	["WO_CONDITION"] = "Condición",
	["WO_CONDITION_TT"] = [=[Evalúa una condición.
Detiene el flujo de trabajo si la condición falla.]=],
	["WO_CONTEXT"] = "Contexto",
	["WO_CONTEXT_TT"] = "El contexto del flujo de trabajo determina qué efectos pueden usarse en el flujo de trabajo.",
	["WO_COPY"] = "Copiar contenido del flujo de trabajo",
	["WO_DELAY"] = "Retraso",
	["WO_DELAY_CAST_TEXT"] = "Texto de casteo",
	["WO_DELAY_CAST_TEXT_TT"] = "El texto situado en la barra de casteo.",
	["WO_DELAY_DURATION"] = "Duración",
	["WO_DELAY_DURATION_TT"] = "La duración del retraso, en segundos.",
	["WO_DELAY_INTERRUPT"] = "Interrupción",
	["WO_DELAY_INTERRUPT_1"] = "Sin interrupción",
	["WO_DELAY_INTERRUPT_2"] = "Interrumpir en movimiento",
	["WO_DELAY_SECONDS"] = "segundo(s)",
	["WO_DELAY_TYPE"] = "Tipo de retraso",
	["WO_DELAY_TYPE_1_TT"] = "Pausa el flujo de trabajo sin mostrar ninguna información al jugador.",
	["WO_EFFECT"] = "Efecto",
	["WO_EFFECT_CAT_COMMON"] = "Común",
	["WO_EFFECT_NO_EDITOR"] = "No se puede configurar este efecto.",
	["WO_EFFECT_SELECT"] = "Selecciona un efecto",
	["WO_EFFECT_TT"] = [=[Reproduce un efecto.
Ya sea sonidos, texto, etc.]=],
	["WO_ELEMENT"] = "Edición del elemento",
	["WO_ELEMENT_ADD"] = "Añadir elemento al flujo de trabajo",
	["WO_ELEMENT_COND"] = "Editar efecto de condición",
	["WO_ELEMENT_COND_NO"] = "Eliminar efecto de condición",
	["WO_ELEMENT_COND_TT"] = "Añade una condición a este efecto.",
	["WO_ELEMENT_COPY"] = "Copiar el contenido del elemento",
	["WO_ELEMENT_EDIT"] = "Haz clic para editar un elemento",
	["WO_ELEMENT_EDIT_CTRL"] = "Control+clic para condicionar esta instrucción",
	["WO_ELEMENT_EDIT_RIGHT"] = "Haz clic derecho para más operaciones",
	["WO_ELEMENT_PASTE"] = "Pega el contenido del elemento",
	["WO_ELEMENT_TYPE"] = "Selecciona el tipo de elemento",
	["WO_EMPTY"] = [=[Puedes comenzar añadiendo un elemento a tu flujo de trabajo.
Puede ser un efecto, condición o retraso.]=],
	["WO_END"] = "Fin de flujo de trabajo",
	["WO_EVENT_EX_ADD"] = "Añadir enlace de evento",
	["WO_EVENT_EX_BROWSER_COMBAT_LOG_ERROR"] = "No se pueden mostrar argumentos, dirígete a Wowpedia",
	["WO_EVENT_EX_BROWSER_NO_PAYLOAD"] = "Sin argumentos",
	["WO_EVENT_EX_BROWSER_OPEN"] = "Abrir buscador de eventos",
	["WO_EVENT_EX_BROWSER_TITLE"] = "Buscador de eventos",
	["WO_EVENT_EX_CONDI"] = "Editor de condición de enlace de evento",
	["WO_EVENT_EX_EDITOR"] = "Editor de enlace de evento",
	["WO_EVENT_EX_LINK"] = "Enlace de evento de juego",
	["WO_EVENT_EX_LINKS"] = "Enlaces de evento de juego",
	["WO_EVENT_EX_LINKS_TT"] = [=[Aquí puedes enlazar tus flujos de trabajo a eventos del juego.
Cada enlace puede ser condicionado.]=],
	["WO_EVENT_EX_NO"] = "Sin enlace de evento",
	["WO_EVENT_EX_UNKNOWN_ERROR"] = "[Error] Evento desconocido %s en %s",
	["WO_EVENT_ID"] = "ID de evento",
	["WO_EVENT_ID_TT"] = [=[La ID del evento.

Puedes ver la lista completa de eventos en páginas web como wowwiki o wowpedia.

He aquí un ejemplo, PLAYER_REGEN_DISABLED se activa cuando entras en combate.]=],
	["WO_EXPERT"] = "Modo experto",
	["WO_EXPERT_DONE"] = "Cambiado %s a modo experto. ¡Desata tu creatividad!",
	["WO_EXPERT_TT"] = [=[Un flujo de trabajo es un conjunto de instrucciones para hacer tu objeto dinámico.

Aquí puedes definir todos los flujos de trabajo para este objeto, para después enlazarlos a una acción en la ventana de enlaces de eventos.]=],
	["WO_LINKS"] = "Enlaces de evento",
	["WO_LINKS_NO_LINKS"] = "Sin enlace",
	["WO_NO"] = "Sin flujos de trabajo",
	["WO_SECURITY"] = "Nivel de seguridad",
	["WO_SECURITY_HIGH"] = "Alto",
	["WO_SECURITY_LOW"] = "Bajo",
	["WO_SECURITY_NORMAL"] = "Medio",
	["WO_WO_SECURITY"] = "Seguridad de los flujos de trabajo",
	["WO_WORKFLOW"] = "Flujos de trabajo"
};

TRP3_API.loc:GetLocale("esES"):AddTexts(L);
