-- Copyright The Total RP 3 Extended Authors
-- SPDX-License-Identifier: Apache-2.0

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- ALL MODIFICATIONS TO THIS FILE WILL BE LOST.

local _, TRP3_API = ...;

TRP3_API.loc:GetLocale("koKR"):AddTexts({
	["ALL"] = "모든",
	["CA_ACTIONS"] = "행위",
	["CONF_UNIT"] = "단위",
	["DB"] = "데이터 베이스"
});
