-- Copyright The Total RP 3 Extended Authors
-- SPDX-License-Identifier: Apache-2.0

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- ALL MODIFICATIONS TO THIS FILE WILL BE LOST.

local L;

L = {
	["ALL"] = "全部",
	["BINDING_NAME_TRP3_INVENTORY"] = "打开角色背包",
	["BINDING_NAME_TRP3_MAIN_CONTAINER"] = "打开主容器",
	["BINDING_NAME_TRP3_QUEST_ACTION"] = "任务动作：互动",
	["BINDING_NAME_TRP3_QUEST_LISTEN"] = "任务动作：聆听",
	["BINDING_NAME_TRP3_QUEST_LOOK"] = "任务动作：调查",
	["BINDING_NAME_TRP3_QUEST_TALK"] = "任务动作：询问",
	["BINDING_NAME_TRP3_QUESTLOG"] = "打开TRP3任务日志",
	["BINDING_NAME_TRP3_SEARCH_FOR_ITEMS"] = "搜索物品",
	["CA_ACTION_CONDI"] = "动作条件编辑器",
	["CA_ACTION_REMOVE"] = "删除这个动作?",
	["CA_ACTIONS"] = "动作",
	["CA_ACTIONS_ADD"] = "添加动作",
	["CA_ACTIONS_COND"] = "编辑条件",
	["CA_ACTIONS_COND_OFF"] = "这个动作没有被设定条件",
	["CA_ACTIONS_COND_ON"] = "这个动作拥有条件",
	["CA_ACTIONS_COND_REMOVE"] = "删除条件",
	["CA_ACTIONS_EDITOR"] = "动作编辑",
	["CA_ACTIONS_NO"] = "没有动作",
	["CA_ACTIONS_SELECT"] = "选择动作类型",
	["CA_DESCRIPTION"] = "剧本概要",
	["CA_DESCRIPTION_TT"] = "在这里写一些简明扼要的内容, 内容将在任务日志中显示。",
	["CA_ICON"] = "剧本图标",
	["CA_ICON_TT"] = "选择剧本图标",
	["CA_IMAGE"] = "剧本人物",
	["CA_IMAGE_TT"] = "选择剧本人物",
	["CA_LINKS_ON_START"] = "触发剧本时",
	["CA_LINKS_ON_START_TT"] = [=[ |cff00ff00当|r 玩家第一次激活你的剧本时触发，或者在任务日志中重置剧本时触发

|cff00ff00这里很适合激活你的第一个任务。]=],
	["CA_NAME"] = "剧本名字",
	["CA_NAME_NEW"] = "新的剧本",
	["CA_NAME_TT"] = "这是你剧本的名字。它出现在任务日志中.",
	["CA_NO_NPC"] = "没有自定义 NPC",
	["CA_NPC"] = "剧本 NPC 列表",
	["CA_NPC_ADD"] = "添加自定义 NPC",
	["CA_NPC_AS"] = "复制",
	["CA_NPC_EDITOR"] = "NPC 编辑",
	["CA_NPC_EDITOR_DESC"] = "NPC 描述",
	["CA_NPC_EDITOR_NAME"] = "NPC 名称",
	["CA_NPC_ID"] = "NPC ID",
	["CA_NPC_ID_TT"] = [=[请输入要自定义的NPC的ID

	|cff00ff00你可以输入这个指令：/trp3 getID 来获取你目标NPC的ID]=],
	["CA_NPC_NAME"] = "默认 NPC 名",
	["CA_NPC_REMOVE"] = "移除这个NPC的自定义信息？",
	["CA_NPC_TT"] = [=[你可以自定义NPC并给他们一个名字、图标和说明。
当其他玩家激活你的剧本时，这些信息将变得可见。]=],
	["CA_NPC_UNIT"] = "自定义 NPC",
	["CA_QE_ID"] = "变更任务 ID",
	["CA_QE_ST_ID"] = "改变 任务步骤 ID",
	["CA_QUEST_ADD"] = "添加任务",
	["CA_QUEST_CREATE"] = [=[请输入任务ID。一个剧本当中不能有两个使用相同ID的任务。

	|cffff9900请注意，任务会在任务日志当中以任务ID的字母顺序列出。
	
	|cff00ff00因此，我们推荐使用诸如quest_#这样的任务ID。]=],
	["CA_QUEST_DD_COPY"] = "复制任务内容",
	["CA_QUEST_DD_PASTE"] = "粘贴任务内容",
	["CA_QUEST_DD_REMOVE"] = "删除任务",
	["CA_QUEST_EXIST"] = "已经存在一个 ID是%s的任务了。",
	["CA_QUEST_NO"] = "没有任务",
	["CA_QUEST_REMOVE"] = "删除这个任务?",
	["CL_CAMPAIGN_PROGRESSION"] = "%s的进度：",
	["CL_CREATION"] = "拓展的创作",
	["CL_EXTENDED_CAMPAIGN"] = "拓展的剧本",
	["CL_EXTENDED_ITEM"] = "拓展的物品",
	["CL_IMPORT"] = "导入到数据库",
	["CL_IMPORT_ITEM_BAG"] = "将物品添加到你的背包",
	["CL_TOOLTIP"] = "创建聊天链接",
	["COM_NPC_ID"] = "获取目标NPC的ID",
	["COND_COMPLETE"] = "完成逻辑表达",
	["COND_CONDITIONED"] = "有条件的",
	["COND_EDITOR"] = "条件编辑器",
	["COND_EDITOR_EFFECT"] = "效果条件编辑器",
	["COND_LITT_COMP"] = "所有的比较类型",
	["COND_NUM_COMP"] = "只有数据比较",
	["COND_NUM_FAIL"] = "如果你要使用数据比较，你必须拥有两个数据变量",
	["COND_PREVIEW_TEST"] = "预览测试",
	["COND_PREVIEW_TEST_TT"] = "根据当前情况，在聊天框当中显示这个测试的结果。",
	["COND_TEST_EDITOR"] = "测试编辑器",
	["COND_TESTS"] = "条件测试",
	["CONF_MAIN"] = "Extended",
	["CONF_MUSIC_ACTIVE"] = "播放环境音乐",
	["CONF_MUSIC_ACTIVE_TT"] = [=[环境音乐是其他玩家在一定范围（码）内播放的音乐（例如通过物品。）

	如果你不想听到这些音乐，可以将他们关闭。
	
	|cnWARNING_FONT_COLOR:你不会听到来自被忽略的玩家的音乐。|r
	
	|cnGREEN_FONT_COLOR:所有的音乐都可以通过“声音历史”功能中止。|r]=],
	["CONF_NPC_EMBED_ORIGINAL"] = "嵌入原始提示栏",
	["CONF_NPC_EMBED_ORIGINAL_TT"] = "在NPC提示栏的底部加入原始提示栏",
	["CONF_NPC_HIDE_ORIGINAL"] = "隐藏原始提示栏",
	["CONF_NPC_TOOLTIP"] = "剧情战役NPC提示栏",
	["CONF_SOUNDS"] = "环境声音 / 音乐",
	["CONF_SOUNDS_ACTIVE"] = "播放环境声音",
	["CONF_SOUNDS_ACTIVE_TT"] = [=[环境声音是其他玩家在一定范围（码）内播放的音乐（例如通过物品。）

	如果你不想听到这些声音，可以将他们关闭。
	
	|cnWARNING_FONT_COLOR:你不会听到来自被忽略的玩家的声音。|r
	
	|cnGREEN_FONT_COLOR:所有的声音都可以通过“声音历史”功能中止。|r]=],
	["CONF_SOUNDS_MAXRANGE"] = "最大播放距离",
	["CONF_SOUNDS_MAXRANGE_TT"] = [=[设定环境声音/音乐播放的最大范围（码）。

	|cnGREEN_FONT_COLOR:有效防止人们播放范围巨大的音效。|r
	
	|cnWARNING_FONT_COLOR:为0代表范围无限！|r]=],
	["CONF_UNIT"] = "单位",
	["CONF_UNIT_WEIGHT"] = "重量单位",
	["CONF_UNIT_WEIGHT_1"] = "g/克",
	["CONF_UNIT_WEIGHT_2"] = "Pounds/磅",
	["CONF_UNIT_WEIGHT_3"] = "Potatoes/土豆数量",
	["CONF_UNIT_WEIGHT_TT"] = "确定重量如何显示。",
	["DB"] = "数据库",
	["DB_ACTIONS"] = "动作",
	["DB_ADD_COUNT"] = "你想向背包里加入多少数量的%s？",
	["DB_ADD_ITEM"] = "添加物品到主背包",
	["DB_ADD_ITEM_TT"] = "将一定数量的该物品添加到你的容器（在角色没有容器的时候则是主背包）。",
	["DB_BACKERS"] = "后台数据库 (%s)",
	["DB_BACKERS_LIST"] = "关于作者",
	["DB_BROWSER"] = "物品浏览器",
	["DB_COPY_ID_TT"] = "在一个可复制/粘贴的窗口内显示物品ID",
	["DB_COPY_TT"] = "复制这个物品（及其子物品）的信息以便粘贴为其他物品的子物品。",
	["DB_CREATE_CAMPAIGN"] = "创建剧本",
	["DB_CREATE_CAMPAIGN_TEMPLATES_BLANK"] = "空剧本",
	["DB_CREATE_CAMPAIGN_TEMPLATES_BLANK_TT"] = [=[一个空白模板
适合喜欢从头开始的人。]=],
	["DB_CREATE_CAMPAIGN_TEMPLATES_FROM"] = "从……创建",
	["DB_CREATE_CAMPAIGN_TEMPLATES_FROM_TT"] = "创建现有剧本的副本",
	["DB_CREATE_CAMPAIGN_TT"] = "开始创建剧本",
	["DB_CREATE_ITEM"] = "创建物品",
	["DB_CREATE_ITEM_TEMPLATES"] = "或者选择一个模板",
	["DB_CREATE_ITEM_TEMPLATES_BLANK"] = "空白项",
	["DB_CREATE_ITEM_TEMPLATES_BLANK_TT"] = [=[一个空白的模板.
	适合喜欢从头开始的人。]=],
	["DB_CREATE_ITEM_TEMPLATES_CONTAINER"] = "容器",
	["DB_CREATE_ITEM_TEMPLATES_CONTAINER_TT"] = [=[一个容器模板.
容器可以存放其他物品。]=],
	["DB_CREATE_ITEM_TEMPLATES_DOCUMENT"] = "文档项目",
	["DB_CREATE_ITEM_TEMPLATES_DOCUMENT_TT"] = [=[一个带有内部文档对象的项目模板.
有助于快速创建一本书或一卷书.]=],
	["DB_CREATE_ITEM_TEMPLATES_EXPERT"] = "专家级物品",
	["DB_CREATE_ITEM_TEMPLATES_EXPERT_TT"] = [=[一个专家级物品模板。
推荐有经验的玩家使用。]=],
	["DB_CREATE_ITEM_TEMPLATES_FROM"] = "从 ...创建",
	["DB_CREATE_ITEM_TEMPLATES_FROM_TT"] = "创建一个现有物品的副本.",
	["DB_CREATE_ITEM_TEMPLATES_QUICK"] = "快速创建物品",
	["DB_CREATE_ITEM_TEMPLATES_QUICK_TT"] = [=[快速创建一个没有任何效果的简单物品.
然后在你的主背包中添加这个物品。]=],
	["DB_CREATE_ITEM_TT"] = "为新物品选择一个模板",
	["DB_DELETE_TT"] = "删除该物品及其所有子物品。",
	["DB_EXPERT_TT"] = "将该物品转换为专家模式，允许更复杂的自定义功能。",
	["DB_EXPORT"] = "快速导出物品",
	["DB_EXPORT_DONE"] = [=[你的物品已作为名为|cff00ff00totalRP3_Extended_ImpExport.lua|r 的文件导出到如下目录:

World of Warcraft\WTF\
account\YOUR_ACCOUNT\SavedVariables

你可以把这个文件分享给你的朋友！

他们可以使用|cff00ff00完整数据库|r来导入物品。]=],
	["DB_EXPORT_HELP"] = "物品%s 的代码(大小: %0.1f kB)",
	["DB_EXPORT_MODULE_NOT_ACTIVE"] = "完全导入/导出物品： 请预先启用totalRP3_Extended_ImpExport插件。",
	["DB_EXPORT_TOO_LARGE"] = [=[这个物品由于尺寸太大而无法通过这种方式导出，请使用完全导出功能。

大小: %0.1f kB.]=],
	["DB_EXPORT_TT"] = [=[将目标物品导出为可以交流的代码形式。

只对小物品有效(代码化后小于20kb)。对于大型物品，请使用完整导出功能。]=],
	["DB_FILTERS"] = "搜索过滤",
	["DB_FILTERS_CLEAR"] = "清除",
	["DB_FILTERS_NAME"] = "物品名称",
	["DB_FILTERS_OWNER"] = "创建者",
	["DB_FULL"] = "全部数据库 (%s)",
	["DB_FULL_EXPORT"] = "完整导出",
	["DB_FULL_EXPORT_TT"] = [=[无视物品的大小进行完整导出

	这会重置界面以便写入插件数据文件。]=],
	["DB_HARD_SAVE"] = "本地保存",
	["DB_HARD_SAVE_TT"] = "重置界面以将修改的变量强制保存到本地磁盘。",
	["DB_IMPORT"] = "快速物品导入",
	["DB_IMPORT_CONFIRM"] = [=[这个物品是使用一个和你的不同的TRP3E版本进行序列化的

导入的TRP3E版本： %s
你的TRP3E版本： %s

|cffff9900这可能会导致不兼容，
你确定要导入吗？]=],
	["DB_IMPORT_DONE"] = "物品导入成功！",
	["DB_IMPORT_EMPTY"] = [=[在你的|cff00ff00totalRP3_Extended_ImpExport.lua|r 文件当中没有物品可以导入。

文件必须在 |cffff9900游戏启动之前|r 放入以下目录：

World of Warcraft\WTF\
account\YOUR_ACCOUNT\SavedVariables]=],
	["DB_IMPORT_ERROR1"] = "物品序列号无法解读。",
	["DB_IMPORT_FULL"] = "完整物品导入",
	["DB_IMPORT_FULL_CONFIRM"] = [=[你想要导入以下物品吗？

%s
%s
作者： |cff00ff00%s|r
版本 %s]=],
	["DB_IMPORT_FULL_TT"] = "导入 |cff00ff00totalRP3_Extended_ImpExport.lua|r 文件。",
	["DB_IMPORT_ITEM"] = "导入物品",
	["DB_IMPORT_TT"] = "在这里粘贴已序列化的物品内容",
	["DB_IMPORT_TT_WAGO"] = [=["没有可以粘贴的东西？WeakAuras共享网站|cff00ff00[<a href="http://wago.io">wago.io</a>]|r现在提供一些玩家可以导入的Total RP 3:Extended物品
	<br/>
你可以浏览网站并将其他玩家分享的内容粘贴在这里。]=],
	["DB_IMPORT_VERSION"] = [=[你正在导入一个你现有的物品的更老版本

导入版本： %s
你的版本： %s

|cffff9900确定进行回滚吗？]=],
	["DB_IMPORT_WORD"] = "导入",
	["DB_LIST"] = "创建列表",
	["DB_LOCALE"] = "物品语言",
	["DB_MY"] = "我的数据库 (%s)",
	["DB_MY_EMPTY"] = [=[你还没有创建任何物品，
用以下的按钮释放你的创造力吧！]=],
	["DB_OTHERS"] = "来自其他RP玩家的数据 (%s)",
	["DB_OTHERS_EMPTY"] = "所有来自其他玩家的物品数据将显示在这里",
	["DB_REMOVE_OBJECT_POPUP"] = [=[请确认是否删除物品：
	ID: |cff00ffff"%s"|r
	|cff00ff00[%s]|r
	
	|cffff9900警告：该过程无法逆转！]=],
	["DB_RESULTS"] = "搜索结果",
	["DB_SECURITY_TT"] = "显示该物品的所有安全参数. 你可以通过这一选项来允许或禁用特定的物品效果。",
	["DB_TO_EXPERT"] = "专家模式",
	["DB_WARNING"] = [=[
|cffff0000!!! 警告 !!!

|cffff9900不要忘记保存之前的内容!]=],
	["DEBUG_QUEST_START"] = "开始任务",
	["DEBUG_QUEST_START_USAGE"] = "使用: /trp3 debug_quest_start questID",
	["DEBUG_QUEST_STEP"] = "转到任务步骤.",
	["DEBUG_QUEST_STEP_USAGE"] = "使用: /trp3 debug_quest_step questID stepID",
	["DI_ATTR_TT"] = "仅当你希望根据之前的剧情修改这一参数时使用。",
	["DI_ATTRIBUTE"] = "舞台编辑",
	["DI_BKG"] = "修改背景图案",
	["DI_BKG_TT"] = [=[这张图案会被用作过场动画的背景，请输入完整的图案路径。

如果你在过场动画当中使用不同的背景，新背景将会以淡入形式出现。]=],
	["DI_CHOICE"] = "选项",
	["DI_CHOICE_CONDI"] = "选项条件",
	["DI_CHOICE_STEP"] = "前往步骤",
	["DI_CHOICE_STEP_TT"] = [=[如果玩家选择这一选项，可以输入想要播放的过场动画ID。

|cff00ff00如果是空白或无效ID，这会结束过场动画（并触发On Finish事件）。]=],
	["DI_CHOICE_TT"] = [=[输入这一选项的文本

|cff00ff00如果想禁用该选项，请留空。]=],
	["DI_CHOICES"] = "玩家选择",
	["DI_CHOICES_TT"] = "设定这一步骤的玩家选项。",
	["DI_CONDI_TT"] = [=[设定选项的条件，如果此时没有满足条件，则该选项不会显示。

|cff00ff00点击：设定条件
右击：清除条件]=],
	["DI_DIALOG"] = "对话",
	["DI_DISTANCE"] = "最大距离（码）",
	["DI_DISTANCE_TT"] = [=[设定玩家在中断过场动画之前可以离开的最大距离（码），如果超出，则会中断过场动画，并触发“过场动画取消”。

|cff00ff000代表无限制

|cffff9900从7.1版本开始在室内/地下城/战场当中无效。]=],
	["DI_END"] = "结束点",
	["DI_END_TT"] = [=[将这一步标记为结束点，到达这一步时会结束过场动画，并触发“过场动画结束”。

|cff00ff00这在使用玩家选项时非常有用。]=],
	["DI_FRAME"] = "装饰",
	["DI_GET_ID"] = "目标",
	["DI_GET_ID_TT"] = "复制目标的NPC ID，只在目标是NPC时有效。",
	["DI_HISTORY"] = "过场动画历史",
	["DI_HISTORY_TT"] = "点击以显示/隐藏过场动画剧情记录",
	["DI_IMAGE"] = "改变图片",
	["DI_IMAGE_TT"] = [=[在过场动画窗口中央显示一张图片，这张图片会淡入，请输入完整的图片ID。

如果要隐藏图片，只需将ID留空。]=],
	["DI_LEFT_UNIT"] = "改变左侧模型",
	["DI_LINKS_ONEND"] = "在过场动画结束时",
	["DI_LINKS_ONEND_TT"] = [=[在过场动画结束时触发

|cff00ff00这可以通过到达过场动画的最终步骤，或让玩家前往空白或未知步骤来触发。

|cffff0000如果玩家手动关闭过场动画窗口，这一条件不会触发！]=],
	["DI_LINKS_ONSTART"] = "过场动画开始",
	["DI_LINKS_ONSTART_TT"] = [=[当过场动画开始播放时触发

|cffff9900注意这一工作流的顺序在过场动画的第一步之前。]=],
	["DI_LOOT"] = "等待拾取",
	["DI_LOOT_TT"] = "如果左边选择的工作流会给玩家提供拾取列表，你可以勾选此项以强制玩家在完成所有拾取之前无法前进到下一步。",
	["DI_MODELS"] = "模型",
	["DI_NAME"] = "改变说话人的名字",
	["DI_NAME_DIRECTION"] = "改变对话方向",
	["DI_NAME_DIRECTION_TT"] = "决定聊天框和姓名版的位置，以及哪一个模型开始动作。如果想完全隐藏聊天框和姓名版，请留空。",
	["DI_NAME_TT"] = [=[说话的角色的姓名

只在“改变对话方向”不为空时有效]=],
	["DI_NEXT"] = "下一步索引",
	["DI_NEXT_TT"] = [=[你可以指定这一步播放结束后的下一步。

	|cff00ff00如果需要按顺序播放，请留空。只在需要“跳跃”到某一步时使用，这在做出剧情选择时很有用。]=],
	["DI_RIGHT_UNIT"] = "改变右侧模型",
	["DI_STEP"] = "剧本步骤",
	["DI_STEP_ADD"] = "添加步骤",
	["DI_STEP_EDIT"] = "剧本步骤编辑",
	["DI_STEP_TEXT"] = "步骤文本",
	["DI_STEPS"] = "剧本步骤",
	["DI_UNIT_TT"] = [=[选择需要显示的模型

	- 如果要隐藏模型，请留空
	- 使用玩家模型，请选择“player”
	- 使用目标模型，请选择“target”
	- 也可以使用任意NPC的ID]=],
	["DI_WAIT_LOOT"] = "请拾取所有物品",
	["DISCLAIMER"] = [=[{h1:c}请一定要阅读{/h1}

创造物品和任务是非常消耗精力的一件事，所以存储丢失是非常悲剧的。

这里可以存储所有你在wow里创造的东西，当然它是有限制的：
*所有附加数据都有一个未知的数据大小限制（取决于运行32或64位客户端，还有其他杂七杂八）
*达到或者超过这个限制会删除所有数据
*杀死进程，强制关闭客户端（alt+f4）会损坏已经保存的数据
*即使你正确退出游戏，但有时仍有可能游戏不能成功保存数据并损坏数据
*顺便说下这玩意和MyRolePlay（另一个人物卡RP插件）冲突 
*顺便说下存储机制是一个账号下所有角色存一个地方，所以精分太多可能容易崩溃，目前存储限制尚不清楚

正因如此，我们强烈建议你备份保存所有数据。
数据保存位置参见:
{link*https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables*我的信息存在哪里?}
{h2:c}直接备份“WTF\Account\你的角色名\SavedVariables” 下所有内容就行了{/h2}
主要是totalRP3.lua 配置存档/totalrp3_data.lua数据存档/totalrp3_storyline.lua

你可以在这里找到关于同步您的数据到云服务教程:
{link*https://github.com/Total-RP/Total-RP-3/wiki/How-to-backup-and-synchronize-your-add-ons-settings-using-a-cloud-service*如何云同步数据？}
需要一些满足版本迭代的云同步如Google Driver你们上不去我就不管了 O(∩_∩)O~

反正你数据没了我们不能恢复。
特此 感谢︿(￣︶￣)︿。

{p:r} TRP3 小组{/p}]=],
	["DISCLAIMER_OK"] = "鲜血为引，灵魂为代价，我签订这份契约。",
	["DO_EMPTY"] = "空白文档",
	["DO_LINKS_ONCLOSE"] = "在关闭时",
	["DO_LINKS_ONCLOSE_TT"] = "在玩家通过操作或其他事件（例如工作流）关闭时触发。",
	["DO_LINKS_ONOPEN"] = "在打开时",
	["DO_LINKS_ONOPEN_TT"] = "在玩家打开文档时触发。",
	["DO_NEW_DOC"] = "文档",
	["DO_PAGE_ADD"] = "增加一页",
	["DO_PAGE_BORDER"] = "边界",
	["DO_PAGE_BORDER_1"] = "羊皮纸",
	["DO_PAGE_COUNT"] = "页码 %s / %s",
	["DO_PAGE_EDITOR"] = "页面编辑：第 %s 页",
	["DO_PAGE_FIRST"] = "第一页",
	["DO_PAGE_FONT"] = "%s 字体",
	["DO_PAGE_HEIGHT"] = "页面高度",
	["DO_PAGE_HEIGHT_TT"] = "以像素为单位的页面高度，请注意有些背景图案只适合特定的宽高比，因此可能会变形。",
	["DO_PAGE_LAST"] = "最后一页",
	["DO_PAGE_MANAGER"] = "页面管理器",
	["DO_PAGE_NEXT"] = "下一页",
	["DO_PAGE_PREVIOUS"] = "上一页",
	["DO_PAGE_REMOVE"] = "删除页",
	["DO_PAGE_REMOVE_POPUP"] = "要删除页面 %s 吗？",
	["DO_PAGE_RESIZE"] = "可修改尺寸",
	["DO_PAGE_RESIZE_TT"] = [=[允许使用者修改页面的尺寸

|cffff9900请保证你的设计是可读的并且不受宽高比影响。

|cff00ff00尺寸无法被降低到默认最低尺寸以下。]=],
	["DO_PAGE_TILING"] = "堆砌背景",
	["DO_PAGE_TILING_TT"] = "选择背景图案是否会在横向和纵向两个尺度内堆叠，如果选择否，背景图案会被拉伸。",
	["DO_PAGE_WIDTH"] = "页面宽度",
	["DO_PAGE_WIDTH_TT"] = "以像素为单位的页面宽度，请注意有些背景图案只适合特定的宽高比，因此可能会变形。",
	["DO_PARAMS_CUSTOM"] = "自定义页面参数",
	["DO_PARAMS_GLOBAL"] = "默认参数",
	["DO_PARAMS_GLOBAL_TT"] = "改变文档的默认参数，这些参数会被所有没有自定义参数的页面使用。",
	["DO_PREVIEW"] = "点击以预览页面",
	["DOC_UNKNOWN_ALERT"] = "无法打开文档 (Missing class)",
	["DR_DELETED"] = "摧毁了: %s x%d",
	["DR_DROP_ERROR_INSTANCE"] = "无法在场景内扔下物品",
	["DR_DROPED"] = "扔在地上： %s x%d",
	["DR_NOTHING"] = "在这个地区没有发现任何物品.",
	["DR_POPUP"] = "扔在这里",
	["DR_POPUP_ASK"] = [=[Total RP 3
 
选择如何处理该物品:
%s]=],
	["DR_POPUP_REMOVE"] = "摧毁",
	["DR_POPUP_REMOVE_TEXT"] = "要摧毁这个物品吗?",
	["DR_RESULTS"] = "找到了 %s 物品",
	["DR_SEARCH_BUTTON"] = "搜索 |cff00ff00我的|r 物品",
	["DR_SEARCH_BUTTON_TT"] = "搜索附近15码内你的物品.",
	["DR_STASHED"] = "藏匿了: %s x%d",
	["DR_STASHES"] = "藏匿",
	["DR_STASHES_CREATE"] = "创建一个藏宝箱",
	["DR_STASHES_CREATE_TT"] = "在你站的地方创建一个藏宝箱.",
	["DR_STASHES_DROP"] = "你不能把物品丢在别人的藏宝箱里.",
	["DR_STASHES_EDIT"] = "编辑藏匿物",
	["DR_STASHES_ERROR_INSTANCE"] = "无法在场景内创建藏匿物",
	["DR_STASHES_ERROR_OUT_SYNC"] = "藏匿物同步失败，重试.",
	["DR_STASHES_ERROR_SYNC"] = "藏匿物没有同步.",
	["DR_STASHES_FOUND"] = "发现藏匿物: %s",
	["DR_STASHES_FULL"] = "这个藏宝箱满了。",
	["DR_STASHES_HIDE"] = "防止搜索",
	["DR_STASHES_HIDE_TT"] = [=[这些宝箱不会出现在其他玩家的地图扫描上.

请注意，如果他们知道它在哪里，他们将始终能够打开它。]=],
	["DR_STASHES_MAX"] = "最多 50 个字符",
	["DR_STASHES_NAME"] = "藏匿",
	["DR_STASHES_NOTHING"] = "这地方没发现藏匿物.",
	["DR_STASHES_OWNER"] = "所有者",
	["DR_STASHES_OWNERSHIP"] = "接管藏匿物",
	["DR_STASHES_OWNERSHIP_PP"] = [=[接管这个藏匿物吗?
当其他玩家扫描时，这个角色将显示为这个藏匿物的拥有者。]=],
	["DR_STASHES_REMOVE"] = "删除藏匿物",
	["DR_STASHES_REMOVE_PP"] = [=[删除藏匿物?
|cffff9900All 存放在里面的东西会丢失!]=],
	["DR_STASHES_REMOVED"] = "藏匿物已删除",
	["DR_STASHES_RESYNC"] = "重新同步",
	["DR_STASHES_SCAN"] = "搜索玩家的藏匿物",
	["DR_STASHES_SCAN_MY"] = "搜索我的藏匿物",
	["DR_STASHES_SEARCH"] = "搜索 |cff00ff00玩家的|r 藏匿物",
	["DR_STASHES_SEARCH_ACTION"] = "搜索15码内其他玩家的藏匿物。",
	["DR_STASHES_SEARCH_TT"] = "搜索需要3秒，别动!",
	["DR_STASHES_SYNC"] = "正在同步...",
	["DR_STASHES_TOO_FAR"] = "你离藏匿物太远了.",
	["DR_STASHES_WITHIN"] = "|cff00ff00Your|r 15码内有藏匿物",
	["DR_SYSTEM"] = "寻宝系统",
	["DR_SYSTEM_TT"] = [=[ 丢下/搜索物品或创建/查看你自己的藏匿点。

这个系统不能在地下城/竞技场/战场使用.]=],
	["EDITOR_BOTTOM"] = "底部",
	["EDITOR_CANCEL_TT"] = [=[取消对物品 %s 的所有修改（物品本身和所有的内含物品）

|cffff9900未保存的修改将会丢失！]=],
	["EDITOR_CONFIRM"] = "确认",
	["EDITOR_HEIGHT"] = "高度",
	["EDITOR_ICON"] = "选择图标",
	["EDITOR_ICON_SELECT"] = "点击以选择一个图标",
	["EDITOR_ID_COPY"] = "复制 ID",
	["EDITOR_ID_COPY_POPUP"] = "你可以复制下方的物品ID以便把它粘贴到某处。",
	["EDITOR_MAIN"] = "主要",
	["EDITOR_MORE"] = "更多",
	["EDITOR_NOTES"] = "自由记录",
	["EDITOR_PREVIEW"] = "预览",
	["EDITOR_SAVE_TT"] = "保存对物品 %s 的所有修改（物品本身和所有的内含物品）并增加版本号。",
	["EDITOR_TOP"] = "顶部",
	["EDITOR_WARNINGS"] = [=[报告了 %s 个错误

|cffff9900%s|r

真的要保存吗?]=],
	["EDITOR_WIDTH"] = "宽度",
	["EFFECT_CAT_CAMERA"] = "视角",
	["EFFECT_CAT_CAMERA_LOAD"] = "载入视角",
	["EFFECT_CAT_CAMERA_LOAD_TT"] = "将玩家的视角设定为一个保存好的位置。",
	["EFFECT_CAT_CAMERA_SAVE"] = "保存视角",
	["EFFECT_CAT_CAMERA_SAVE_TT"] = "将玩家现在的视角保存在5个栏位当中的一个",
	["EFFECT_CAT_CAMERA_SLOT"] = "栏位编号",
	["EFFECT_CAT_CAMERA_SLOT_TT"] = "栏位的编码，从1到5",
	["EFFECT_CAT_CAMERA_ZOOM_DISTANCE"] = "放大距离",
	["EFFECT_CAT_CAMERA_ZOOM_IN"] = "视角放大",
	["EFFECT_CAT_CAMERA_ZOOM_IN_TT"] = "将视角放大一定距离。",
	["EFFECT_CAT_CAMERA_ZOOM_OUT"] = "视角缩小",
	["EFFECT_CAT_CAMERA_ZOOM_OUT_TT"] = "将视角缩小一定距离。",
	["EFFECT_CAT_CAMPAIGN"] = "剧本和任务",
	["EFFECT_CAT_SOUND"] = "声音和音乐",
	["EFFECT_CAT_SPEECH"] = "发言和表情",
	["EFFECT_COOLDOWN_DURATION"] = "冷却时间",
	["EFFECT_COOLDOWN_DURATION_TT"] = "冷却时间，以秒计算。",
	["EFFECT_DIALOG_ID"] = "过场动画ID",
	["EFFECT_DIALOG_QUICK"] = "快速过场动画",
	["EFFECT_DIALOG_QUICK_TT"] = "生成一个只有一步的快速过场动画，自动选择玩家目标作为说话的人。",
	["EFFECT_DIALOG_START"] = "开始过场动画",
	["EFFECT_DIALOG_START_PREVIEW"] = "开始过场动画 %s.",
	["EFFECT_DIALOG_START_TT"] = "播放过场动画，如果已经有过场动画在播放了，它会被中断并播放这一个过场动画。",
	["EFFECT_DISMOUNT"] = "解散坐骑",
	["EFFECT_DISMOUNT_TT"] = "解散玩家的现有坐骑。",
	["EFFECT_DISPET"] = "解散战斗宠物",
	["EFFECT_DISPET_TT"] = "解散玩家的现有战斗宠物。",
	["EFFECT_DO_EMOTE"] = "做出表情",
	["EFFECT_DO_EMOTE_ANIMATED"] = "动作",
	["EFFECT_DO_EMOTE_OTHER"] = "其他",
	["EFFECT_DO_EMOTE_SPOKEN"] = "语言",
	["EFFECT_DO_EMOTE_TT"] = "使玩家做出一个游戏内置的表情动作。",
	["EFFECT_DOC_CLOSE"] = "关闭文档",
	["EFFECT_DOC_CLOSE_TT"] = "关闭打开的文档， 如果没有打开的文档那就没有效果。",
	["EFFECT_DOC_DISPLAY"] = "显示文档",
	["EFFECT_DOC_DISPLAY_TT"] = "给玩家展示一个文档，如果已经有一个打开的文档了，它会被新文档代替。",
	["EFFECT_DOC_ID"] = "文档ID",
	["EFFECT_DOC_ID_TT"] = [=[用于展示的文档

|cffffff00请输入完整的文档ID（母物品ID和内部ID）

|cff00ff00H提示：复制粘贴完整ID以防输入错误。]=],
	["EFFECT_ITEM_ADD"] = "添加物品",
	["EFFECT_ITEM_ADD_CRAFTED"] = "手工制作的",
	["EFFECT_ITEM_ADD_CRAFTED_TT"] = "如果选择此项，且被添加物品是手工制作的（拥有“手工制作的”属性），物品信息当中将会显示 \"由 xxx 制作\"，xxx 是玩家姓名。",
	["EFFECT_ITEM_ADD_ID"] = "物品ID",
	["EFFECT_ITEM_ADD_ID_TT"] = [=[要添加的物品

|cffffff00请输入完整的物品ID（母物品ID和内部ID）。

|cff00ff00提示：复制粘贴完整ID以防输入错误。]=],
	["EFFECT_ITEM_ADD_PREVIEW"] = "增加了 %s 个 %s",
	["EFFECT_ITEM_ADD_QT"] = "数量",
	["EFFECT_ITEM_ADD_QT_TT"] = [=[添加物品的数量

|cff00ff00插件将会试图达到这个数量，但仍然会被一些条件限制，如：背包已满，或拥有持有数量上限（唯一）。]=],
	["EFFECT_ITEM_ADD_TT"] = "将物品添加到你的背包",
	["EFFECT_ITEM_BAG_DURABILITY"] = "损坏/维修容器",
	["EFFECT_ITEM_BAG_DURABILITY_METHOD"] = "类型",
	["EFFECT_ITEM_BAG_DURABILITY_METHOD_DAMAGE"] = "损坏",
	["EFFECT_ITEM_BAG_DURABILITY_METHOD_DAMAGE_TT"] = "损坏母容器，母容器的耐久度不能低于0",
	["EFFECT_ITEM_BAG_DURABILITY_METHOD_HEAL"] = "维修",
	["EFFECT_ITEM_BAG_DURABILITY_METHOD_HEAL_TT"] = "维修母容器，母容器的耐久度不能高于最大值",
	["EFFECT_ITEM_BAG_DURABILITY_PREVIEW_1"] = "|cff00ff00维修|cffffff00 母容器使其获得 %s 点耐久",
	["EFFECT_ITEM_BAG_DURABILITY_PREVIEW_2"] = "|cffff0000损坏|cffffff00 母容器使其丢失 %s 点耐久",
	["EFFECT_ITEM_BAG_DURABILITY_TT"] = [=[维修或损坏母容器的耐久度。

|cff00ff00只在容器有耐久度时才有效。]=],
	["EFFECT_ITEM_BAG_DURABILITY_VALUE"] = "耐久度",
	["EFFECT_ITEM_BAG_DURABILITY_VALUE_TT"] = "向母容器增加/减少的耐久度点数。",
	["EFFECT_ITEM_CONSUME"] = "消耗物品",
	["EFFECT_ITEM_CONSUME_TT"] = "消耗被使用的物品并摧毁它。",
	["EFFECT_ITEM_COOLDOWN"] = "开始冷却",
	["EFFECT_ITEM_COOLDOWN_PREVIEW"] = "持续时间： %s 秒",
	["EFFECT_ITEM_COOLDOWN_TT"] = "启动物品的冷却时间。",
	["EFFECT_ITEM_DICE"] = "ROLL点",
	["EFFECT_ITEM_DICE_PREVIEW"] = "Roll %s",
	["EFFECT_ITEM_DICE_PREVIEW_STORED"] = "Roll %s 点并将结果保存到 %s",
	["EFFECT_ITEM_DICE_ROLL"] = "Roll",
	["EFFECT_ITEM_DICE_ROLL_TT"] = [=[输入一个类似 /trp3 roll 的指令。

|cff00ff00如：1d20, 3d6…]=],
	["EFFECT_ITEM_DICE_ROLL_VAR"] = "变量名称 (可选)",
	["EFFECT_ITEM_DICE_ROLL_VAR_TT"] = [=[你希望存储Roll点结果的变量名称
如果你不想存储则留空]=],
	["EFFECT_ITEM_DICE_TT"] = "他们看见我在Roll点，他们不喜欢。",
	["EFFECT_ITEM_LOOT"] = "展示/丢下可拾取物品",
	["EFFECT_ITEM_LOOT_DROP"] = "丢下物品",
	["EFFECT_ITEM_LOOT_DROP_TT"] = "把物品丢在地上而不是展示一个拾取窗口，玩家可以通过“搜索物品”来拾取这个物品。",
	["EFFECT_ITEM_LOOT_NAME"] = "来源名称",
	["EFFECT_ITEM_LOOT_NAME_TT"] = "这是拾取的容器的名称。",
	["EFFECT_ITEM_LOOT_PREVIEW_1"] = "在地上丢下 %s 物品。",
	["EFFECT_ITEM_LOOT_PREVIEW_2"] = "显示有 %s 的可拾取物品",
	["EFFECT_ITEM_LOOT_SLOT"] = "点击一个栏位以设定它。",
	["EFFECT_ITEM_LOOT_TT"] = "向玩家显示一个可被拾取的容器或在玩家当前位置放下拾取物。",
	["EFFECT_ITEM_REMOVE"] = "摧毁物品",
	["EFFECT_ITEM_REMOVE_ID_TT"] = [=[摧毁这个物品。

|cffffff00请输入物品的完整ID（母物品ID和子物品ID）。

|cff00ff00提示：可以使用复制粘贴来必变输入错误。]=],
	["EFFECT_ITEM_REMOVE_PREVIEW"] = "摧毁 %s 个 %s",
	["EFFECT_ITEM_REMOVE_QT_TT"] = "摧毁物品的数量",
	["EFFECT_ITEM_REMOVE_TT"] = "从你的背包当中摧毁物品",
	["EFFECT_ITEM_SOURCE_1"] = "所有背包",
	["EFFECT_ITEM_SOURCE_1_ADD_TT"] = "向所有角色背包添加物品，从主背包开始。",
	["EFFECT_ITEM_SOURCE_1_SEARCH_TT"] = "在整个角色背包里搜索物品。",
	["EFFECT_ITEM_SOURCE_2"] = "所有容器",
	["EFFECT_ITEM_SOURCE_2_ADD_TT"] = [=[只向这个容器（及其子容器）添加物品。

	|cffff9900只在这段代码在物品当中时有效。]=],
	["EFFECT_ITEM_SOURCE_2_SEARCH_TT"] = [=[只在这个容器（及其子容器）当中搜索物品。
	
	|cffff9900只在这段代码在物品当中时有效。]=],
	["EFFECT_ITEM_SOURCE_3"] = "所有物品",
	["EFFECT_ITEM_SOURCE_3_ADD_TT"] = [=[只向这个物品（及其子容器）添加物品。

	|cffff9900只在这段代码在物品当中，且该物品是容器时有效。]=],
	["EFFECT_ITEM_SOURCE_3_SEARCH_TT"] = [=[只在这个物品（及其子容器）当中搜索物品。
	
	|cffff9900只在这段代码在物品当中，且该物品是容器时有效。]=],
	["EFFECT_ITEM_SOURCE_ADD"] = "添加到",
	["EFFECT_ITEM_SOURCE_ID"] = "你可以选择你想搜索的物品ID，或通过留空来搜索所有类型的物品。",
	["EFFECT_ITEM_SOURCE_SEARCH"] = "在……搜索",
	["EFFECT_ITEM_USE"] = "容器：使用物品",
	["EFFECT_ITEM_USE_PREVIEW"] = "使用 %s 栏位的物品",
	["EFFECT_ITEM_USE_TT"] = [=[使用容器当中某一栏位的物品

|cffff9900只在该工作流被容器触发时有效。]=],
	["EFFECT_ITEM_WORKFLOW"] = "运行物品工作流",
	["EFFECT_ITEM_WORKFLOW_PREVIEW_C"] = "触发子物品当中的工作流 %s ，位于 %s 栏位。",
	["EFFECT_ITEM_WORKFLOW_PREVIEW_P"] = "触发母容器当中的工作流 %s。",
	["EFFECT_ITEM_WORKFLOW_PREVIEW_S"] = "触发同类物品当中的工作流 %s ，位于 %s 栏位。",
	["EFFECT_ITEM_WORKFLOW_TT"] = "对母容器或特定子物品当中的物品（仅对容器有效）运行工作流",
	["EFFECT_MISSING"] = "该效果 (%s)未知，你应当删除它。",
	["EFFECT_OPERATION"] = "操作",
	["EFFECT_OPERATION_TYPE"] = "操作类型",
	["EFFECT_OPERATION_TYPE_ADD"] = "相加",
	["EFFECT_OPERATION_TYPE_DIV"] = "除以",
	["EFFECT_OPERATION_TYPE_INIT"] = "赋初值",
	["EFFECT_OPERATION_TYPE_INIT_TT"] = "在变量没有值的情况下，为变量赋初值。",
	["EFFECT_OPERATION_TYPE_MULTIPLY"] = "乘以",
	["EFFECT_OPERATION_TYPE_SET"] = "设定",
	["EFFECT_OPERATION_TYPE_SET_TT"] = "将变量设置为一个值，即使在它已经有一个值的情况下也可以。",
	["EFFECT_OPERATION_TYPE_SUB"] = "减去",
	["EFFECT_OPERATION_VALUE"] = "操作值",
	["EFFECT_PROMPT"] = "输入提示",
	["EFFECT_PROMPT_CALLBACK"] = "工作流回调 (可选)",
	["EFFECT_PROMPT_CALLBACK_TT"] = [=[用户输入后调用的工作流。

这是可选的，如果不需要回调请留空。

工作流将会以有正确名称的工作流变量为输入数据回调。

|cffffff00警告：即使玩家选择“取消”，回调也会发生，但这种情况下变量不会发生变化。]=],
	["EFFECT_PROMPT_DEFAULT"] = "默认值",
	["EFFECT_PROMPT_DEFAULT_TT"] = "输入的默认值。",
	["EFFECT_PROMPT_PREVIEW"] = "让使用者输入一个值到变量 |cff00ff00%s|r.",
	["EFFECT_PROMPT_TEXT"] = "弹窗文字",
	["EFFECT_PROMPT_TEXT_TT"] = "在输入弹窗中提示给使用者的文字。",
	["EFFECT_PROMPT_TT"] = [=[要求使用者输入一个值并保存到变量，并可选地触发一个工作流。

|cffff0000警告：这两个步骤不是同步的。]=],
	["EFFECT_PROMPT_VAR"] = "变量名称",
	["EFFECT_PROMPT_VAR_TT"] = "存储用户输入值的变量名称",
	["EFFECT_QUEST_GOTOSTEP"] = "改变任务步骤",
	["EFFECT_QUEST_GOTOSTEP_ID"] = "任务步骤ID",
	["EFFECT_QUEST_GOTOSTEP_ID_TT"] = [=[通过浏览器选择任务步骤（任务和任务步骤必须是已经存在的。）

如果你的任务步骤没有在浏览器中出现，保存任务并再试一次。]=],
	["EFFECT_QUEST_GOTOSTEP_PREVIEW"] = "前往第 %s 步。",
	["EFFECT_QUEST_GOTOSTEP_TT"] = [=[改变任务步骤

|cffff9900仅当任务是当前激活剧情的一部分，且已在任务日志当中出现时有效。]=],
	["EFFECT_QUEST_OBJ_ID"] = "任务目标ID",
	["EFFECT_QUEST_OBJ_ID_TT"] = "输入任务目标ID，这只是任务目标ID而不是完整的剧本-任务-目标格式的ID。",
	["EFFECT_QUEST_REVEAL_OBJ"] = "揭示任务目标",
	["EFFECT_QUEST_REVEAL_OBJ_DONE"] = "完成任务目标",
	["EFFECT_QUEST_REVEAL_OBJ_DONE_PREVIEW"] = "完成任务目标： %s 为了 %s",
	["EFFECT_QUEST_REVEAL_OBJ_DONE_TT"] = [=[将一个任务目标标记为完成。

|cffff9900仅当任务和任务目标已激活，且任务属于当前激活的剧本时有效。 ]=],
	["EFFECT_QUEST_REVEAL_OBJ_PREVIEW"] = "揭示任务目标： %s 为了 %s",
	["EFFECT_QUEST_REVEAL_OBJ_TT"] = [=[揭示一个任务目标

|cffff9900仅当任务已激活，且任务属于当前激活的剧本时有效。]=],
	["EFFECT_QUEST_START"] = "揭示任务",
	["EFFECT_QUEST_START_ID"] = "任务ID",
	["EFFECT_QUEST_START_ID_TT"] = [=[通过浏览器选择任务（任务必须是已经存在的。）

如果你的任务没有在浏览器中出现，保存任务并再试一次。]=],
	["EFFECT_QUEST_START_PREVIEW"] = "揭示任务 %s.",
	["EFFECT_QUEST_START_TT"] = [=[在任务日志当中揭示一个任务。

|cffff9900仅当任务属于当前激活的剧本时有效。]=],
	["EFFECT_RANDSUM"] = "召唤随机战斗宠物",
	["EFFECT_RANDSUM_PREVIEW_FAV"] = "从你的 |c0000ff00偏好|r 当中随机召唤一个战斗宠物",
	["EFFECT_RANDSUM_PREVIEW_FULL"] = "从你的 |c0000ff00所有宠物|r 当中随机召唤一个战斗宠物",
	["EFFECT_RANDSUM_SUMMON_FAV"] = "只召唤偏好战斗宠物。",
	["EFFECT_RANDSUM_TT"] = "召唤一个随机战斗宠物",
	["EFFECT_RUN_WORKFLOW"] = "运行工作流",
	["EFFECT_RUN_WORKFLOW_ID"] = "工作流 ID",
	["EFFECT_RUN_WORKFLOW_ID_TT"] = "你希望运行的工作流ID",
	["EFFECT_RUN_WORKFLOW_PREVIEW"] = "运行 %s 在 %s 当中",
	["EFFECT_RUN_WORKFLOW_SLOT"] = "栏位ID",
	["EFFECT_RUN_WORKFLOW_SLOT_TT"] = "要触发的容器栏位指数，栏位从左上角编号到右下角，以1为开始。",
	["EFFECT_RUN_WORKFLOW_TT"] = "运行另一个工作流，继续沿用现有的所有工作流变量。",
	["EFFECT_SCRIPT"] = "执行限定的Lua脚本",
	["EFFECT_SCRIPT_I_EFFECT"] = "插入效果",
	["EFFECT_SCRIPT_I_EFFECT_TT"] = [=[插入一个游标在代码当中的功能效果，
这个功能的形式是：
|cff00ffff效果(效果ID, args, arg1, arg2, ...);|r
- |cff00ffff效果ID|r:效果的ID，可以在插件源代码当中找到。
- |cff00ffffargs|r: 执行参数：应该一直是一个arg变量。
- |cff00ffff效果参数argX|r: 所有的效果参数都可以在插件源代码当中找到
|cffffff00请确保'args'是第二指标，|r 它包含所有的工作流参数，功能效果需要它。
|cff00ff00我们暂时不会记录所有的效果ID和参数，因为我们认为使用者对这个功能要量力而为。)]=],
	["EFFECT_SCRIPT_SCRIPT"] = "Lua代码",
	["EFFECT_SCRIPT_SCRIPT_TT"] = [=[这段代码会在一个你可以使用所有 Lua 语法和API (table, string, math...) 及扩展|cff00ff00效果|r功能的安全环境下执行。
|cffff0000你在这里无法访问游戏API！|r
由于每次使用都要编译，自定义Lua代码没有工作流的效率高，因为工作流已经编译好了。
|cffff9900请只在有需要的时候使用它。]=],
	["EFFECT_SCRIPT_TT"] = "在受限的安全环境下执行Lua代码",
	["EFFECT_SECURE_MACRO_ACTION_NAME"] = "执行宏命令",
	["EFFECT_SECURE_MACRO_BLOCKED"] = "被阻止的宏命令：",
	["EFFECT_SECURE_MACRO_DESCRIPTION"] = [=[执行宏命令。

|cffcccccc提示：
-该效果只会被玩家动作触发（使用物品，点击过场动画中的选项等）。
-该效果不受工作流当中的延时影响，所有宏命令都将在玩家动作发生后马上执行。
-该效果可以被条件限制并可以修改变量。
-该效果永远不会在战斗状态出发，或被剧情当中的事件触发。
|r]=],
	["EFFECT_SECURE_MACRO_HELP"] = [=[你可以使用你能在宏命令当中使用的任何指令，同时也包括来自其他插件的指令。

你也可以使用TRP3E变量： (|cnGREEN_FONT_COLOR:${my_var_name}|r).

|cnWARNING_FONT_COLOR:Note that macros can have a maximum of 255 characters.|r]=],
	["EFFECT_SECURE_MACRO_HELP_TITLE"] = "Macro commands",
	["EFFECT_SHEATH"] = "切换武器显示",
	["EFFECT_SHEATH_TT"] = "拿出或收起角色的武器。",
	["EFFECT_SIGNAL"] = "发出信号",
	["EFFECT_SIGNAL_ID"] = "信号 ID",
	["EFFECT_SIGNAL_ID_TT"] = "这是你的信号的ID，它可以通过游戏事件 |cff00ff00TRP3_SIGNAL|r 触发的条件和工作流来测试。",
	["EFFECT_SIGNAL_PREVIEW"] = "|cffffff00发送信号ID:|r %s|cffffff00 值为:|r %s",
	["EFFECT_SIGNAL_TT"] = [=[向玩家目标发送一个有ID的信号值。

这个信号可以被事件 |cff00ff00TRP3_SIGNAL|r 通过剧本和任务步骤来调整。]=],
	["EFFECT_SIGNAL_VALUE"] = "信号值",
	["EFFECT_SIGNAL_VALUE_TT"] = "这是你的信号的值，它可以通过游戏事件 |cff00ff00TRP3_SIGNAL|r 触发的条件和工作流来测试并以 |cff00ff00${event.2}|r 这样的形式插入。",
	["EFFECT_SOUND_ID_FADEOUT"] = "淡出时间（可选）",
	["EFFECT_SOUND_ID_FADEOUT_TT"] = "音效在停止前淡出的时长（秒）。如果留空音效马上停止。",
	["EFFECT_SOUND_ID_LOCAL"] = "播放环境音效",
	["EFFECT_SOUND_ID_LOCAL_PREVIEW"] = "播放环境音效 %s，在频道 %s 内，范围为 %s 码半径。",
	["EFFECT_SOUND_ID_LOCAL_STOP"] = "停止环境音效",
	["EFFECT_SOUND_ID_LOCAL_STOP_TT"] = "停止你附近的所有玩家播放的环境音效",
	["EFFECT_SOUND_ID_LOCAL_TT"] = "为你附近的玩家播放音效。",
	["EFFECT_SOUND_ID_SELF"] = "播放音效 ID",
	["EFFECT_SOUND_ID_SELF_CHANNEL"] = "频道",
	["EFFECT_SOUND_ID_SELF_CHANNEL_AMBIANCE"] = "环境",
	["EFFECT_SOUND_ID_SELF_CHANNEL_AMBIANCE_TT"] = [=[环境音效，使用游戏内的环境音效功能。

多个环境音效可以同时播放。

|cffff9900请不要使用这个功能播放音乐，因为它会和游戏音乐互相叠加，如果想播放音乐，请使用音乐功能。]=],
	["EFFECT_SOUND_ID_SELF_CHANNEL_SFX"] = "声效",
	["EFFECT_SOUND_ID_SELF_CHANNEL_SFX_TT"] = [=[声效，使用游戏内的声效功能。

多个声效可以同时播放。]=],
	["EFFECT_SOUND_ID_SELF_ID"] = "声音ID",
	["EFFECT_SOUND_ID_SELF_ID_TT"] = [=[游戏内声音的ID。

|cff00ff00你可以在类似wowhead这类网站上找到声音的ID。

|cffff9900留空以终止所有频道播放的音乐。]=],
	["EFFECT_SOUND_ID_SELF_PREVIEW"] = "播放ID为 %s 的音效，在频道 %s 中。",
	["EFFECT_SOUND_ID_SELF_SOUNDFILE"] = "声音文件ID",
	["EFFECT_SOUND_ID_SELF_SOUNDFILE_TT"] = "如果你想使用你在类似Wow.tools数据库中获得的声音文件ID，请勾选此项。如果你想使用从Wowhead获得的声音ID，请不要勾选。",
	["EFFECT_SOUND_ID_SELF_TT"] = "在特定频道播放音效，只有你能听到。",
	["EFFECT_SOUND_ID_STOP"] = "停止声音ID",
	["EFFECT_SOUND_ID_STOP_ALL_PREVIEW"] = "停止播放 |cff00ff00所有|cffffff00 在频道 %s 中的音效",
	["EFFECT_SOUND_ID_STOP_FADEOUT_ALL_PREVIEW"] = "停止频道%s中的 |cff00ff00all|r声音，%s秒后生效。",
	["EFFECT_SOUND_ID_STOP_FADEOUT_PREVIEW"] = "停止声音ID%s，该声音在频道%s中播放，%秒后生效。",
	["EFFECT_SOUND_ID_STOP_PREVIEW"] = "停止播放 %s，在频道 %s 中。",
	["EFFECT_SOUND_ID_STOP_TT"] = "停止特定频道里的一个或所有音效。",
	["EFFECT_SOUND_LOCAL_DISTANCE"] = "播放半径。",
	["EFFECT_SOUND_LOCAL_DISTANCE_TT"] = "确定音效播放的有效半径。",
	["EFFECT_SOUND_MUSIC_LOCAL"] = "播放环境音乐",
	["EFFECT_SOUND_MUSIC_LOCAL_PREVIEW"] = "播放音乐 \"%s\" ，在 %s 码半径内。",
	["EFFECT_SOUND_MUSIC_LOCAL_STOP"] = "停止环境音乐",
	["EFFECT_SOUND_MUSIC_LOCAL_STOP_TT"] = [=[如果你使用“播放环境音乐”功能，该音乐会不断循环播放直至游戏开始播放一段新的音乐（例如进入新区域时）或玩家手动终止播放。

|cffff9900这只能停止插件播放的音乐，无法停止游戏自身播放的音乐。]=],
	["EFFECT_SOUND_MUSIC_LOCAL_TT"] = "为你附近的玩家播放音乐。",
	["EFFECT_SOUND_MUSIC_SELF"] = "播放音乐",
	["EFFECT_SOUND_MUSIC_SELF_PATH"] = "音乐路径",
	["EFFECT_SOUND_MUSIC_SELF_PATH_TT"] = [=[游戏文件内的音乐路径。

|cffff9900不包括路径的Sounds\Music\部分以及结尾的.mp3。]=],
	["EFFECT_SOUND_MUSIC_SELF_PREVIEW"] = "播放音乐：%s",
	["EFFECT_SOUND_MUSIC_SELF_TT"] = [=[播放音乐，只有你能听到。

	该音乐会不断循环播放直至游戏开始播放一段新的音乐（例如进入新区域时）或玩家手动终止播放。]=],
	["EFFECT_SOUND_MUSIC_STOP"] = "停止音乐",
	["EFFECT_SOUND_MUSIC_STOP_TT"] = [=[如果使用“播放环境音乐”功能，该音乐会不断循环播放直至游戏开始播放一段新的音乐（例如进入新区域时）或玩家手动终止播放。

|cffff9900这只能停止插件播放的音乐，无法停止游戏自身播放的音乐。]=],
	["EFFECT_SOUND_PLAY"] = "播放",
	["EFFECT_SOURCE"] = "来源",
	["EFFECT_SOURCE_CAMPAIGN"] = "激活的剧本",
	["EFFECT_SOURCE_CAMPAIGN_TT"] = "在有激活剧本的情况下，在整个剧本内搜索变量。",
	["EFFECT_SOURCE_OBJECT"] = "对象",
	["EFFECT_SOURCE_OBJECT_TT"] = [=[在工作流源对象中搜索变量。

只在对象是物品或剧本/任务/任务步骤时有效。
	
	此时，变量会在整个剧本尺度内搜索。]=],
	["EFFECT_SOURCE_PARENT"] = "母容器",
	["EFFECT_SOURCE_PARENT_TT"] = "在母容器当中搜索变量",
	["EFFECT_SOURCE_SLOT"] = "栏位中的物品 (子容器)",
	["EFFECT_SOURCE_SLOT_B"] = "栏位中的物品 (同级容器)",
	["EFFECT_SOURCE_SLOT_B_TT"] = "在同一母容器内的特定栏位上的物品搜索工作流。",
	["EFFECT_SOURCE_SLOT_TT"] = "在同一母容器内的特定栏位上的物品搜索工作流。只对容器物品有效！",
	["EFFECT_SOURCE_V"] = "变量来源",
	["EFFECT_SOURCE_W"] = "工作流来源",
	["EFFECT_SOURCE_WORKFLOW"] = "工作流",
	["EFFECT_SOURCE_WORKFLOW_TT"] = "在工作流内搜索变量，这个变量的适用范围仅限于工作流执行时且会在结束时清空。",
	["EFFECT_SPEECH_NAR"] = "发言：叙述",
	["EFFECT_SPEECH_NAR_DEFAULT"] = "今夜的山上，积雪闪着白色的光……",
	["EFFECT_SPEECH_NAR_TEXT_TT"] = "请不要包括 || 字符。",
	["EFFECT_SPEECH_NAR_TT"] = [=[显示一段叙述性发言。

|cff00ff00与带有 || 字符的表情发言效果相同。其他TRP玩家会看到它的正常格式。]=],
	["EFFECT_SPEECH_NPC"] = "发言：NPC",
	["EFFECT_SPEECH_NPC_DEFAULT"] = "你想堆雪人吗？",
	["EFFECT_SPEECH_NPC_NAME"] = "NPC姓名",
	["EFFECT_SPEECH_NPC_NAME_TT"] = "NPC的姓名。",
	["EFFECT_SPEECH_NPC_TT"] = [=[显示一段NPC发言。

|cff00ff00与带有 || 字符和NPC姓名的表情发言效果相同。其他TRP玩家会看到它的正常格式。]=],
	["EFFECT_SPEECH_PLAYER"] = "发言：玩家",
	["EFFECT_SPEECH_PLAYER_DEFAULT"] = "让巨龙吞噬你！",
	["EFFECT_SPEECH_PLAYER_TT"] = "让玩家说话、喊话或作出表情动作。",
	["EFFECT_SPEECH_TYPE"] = "发言类型",
	["EFFECT_SUMMOUNT"] = "召唤一个坐骑",
	["EFFECT_SUMMOUNT_ACTION_TT"] = "选定坐骑",
	["EFFECT_SUMMOUNT_RANDOMMOUNT"] = "随机偏好",
	["EFFECT_SUMMOUNT_TT"] = "在可用的情况下随机召唤一个坐骑。",
	["EFFECT_TEXT"] = "显示文字",
	["EFFECT_TEXT_PREVIEW"] = "显示的文字",
	["EFFECT_TEXT_TEXT"] = "文字",
	["EFFECT_TEXT_TEXT_DEFAULT"] = [=[Hi~ o(*￣▽￣*)ブ.
你好]=],
	["EFFECT_TEXT_TEXT_TT"] = "要显示的文字",
	["EFFECT_TEXT_TT"] = [=[显示一段文字。
格式可以改变。]=],
	["EFFECT_TEXT_TYPE"] = "文字类型",
	["EFFECT_TEXT_TYPE_1"] = "聊天框文字",
	["EFFECT_TEXT_TYPE_2"] = "弹出警告",
	["EFFECT_TEXT_TYPE_3"] = "团队警告",
	["EFFECT_TEXT_TYPE_4"] = "警告消息",
	["EFFECT_USE_SLOT"] = "容器栏位编码",
	["EFFECT_USE_SLOT_TT"] = "从左上角到右下角。",
	["EFFECT_VAR"] = "变量名",
	["EFFECT_VAR_INDEX"] = "参数指数",
	["EFFECT_VAR_INDEX_TT"] = [=[参数的指数

如果你想测试第三个参数或事件，输入3.]=],
	["EFFECT_VAR_OBJECT_CHANGE"] = "变量操作",
	["EFFECT_VAR_OBJECT_CHANGE_TT"] = [=[对变量进行一个操作。

|cffff9900对于数学操作：如果变量不存在或无法转换为数值，它会被初始化为0.]=],
	["EFFECT_VAR_OPERAND"] = "变量的动态值",
	["EFFECT_VAR_OPERAND_CONFIG"] = "变量参数",
	["EFFECT_VAR_OPERAND_CONFIG_NO"] = "该变量没有参数。",
	["EFFECT_VAR_OPERAND_TT"] = "为变量赋动态值，可以使用各类条件。",
	["EFFECT_VAR_VALUE"] = "变量值",
	["EFFECT_W_CAMPAIGN_TT"] = "在整个剧本中搜索工作流。",
	["EFFECT_W_OBJECT_TT"] = "在同一对象当中搜索工作流。",
	["ERROR_MISSING_ARG"] = "参数 %1$s 在试图启用 %2$s 功能时丢失。",
	["ERROR_SPEECH_EFFECT"] = "在一个延时或事件后无法使用“/说”和“/大喊”指令。",
	["EX_SOUND_HISTORY"] = "声音历史",
	["EX_SOUND_HISTORY_ACTION_OPEN"] = "打开声音历史",
	["EX_SOUND_HISTORY_ACTION_STOP"] = "停止所有声音",
	["EX_SOUND_HISTORY_CLEAR"] = "清除。",
	["EX_SOUND_HISTORY_EMPTY"] = "没有声音被播放。",
	["EX_SOUND_HISTORY_LINE"] = "%s 播放了ID为 %s 的声音，在频道 %s 中。",
	["EX_SOUND_HISTORY_REPLAY"] = "重播",
	["EX_SOUND_HISTORY_STOP"] = "停止",
	["EX_SOUND_HISTORY_STOP_ALL"] = "全部停止",
	["EX_SOUND_HISTORY_TT"] = "浏览播放过的声音，查看他们的来源以及停止仍在播放的声音。",
	["IN_INNER"] = "内部对象",
	["IN_INNER_ADD"] = "添加内部对象",
	["IN_INNER_ADD_COPY"] = "添加现有对象的副本",
	["IN_INNER_ADD_NEW"] = "创建新的对象",
	["IN_INNER_COPY_ACTION"] = "复制对象内容",
	["IN_INNER_DELETE_CONFIRM"] = [=[删除内部对象 |cff00ffff"%s"|r |cff00ff00[%s]|r ，从母对象 |cff00ff00[%s]|r 当中吗?

|cffff9900内部对象会丢失。]=],
	["IN_INNER_DELETE_TT"] = "从母对象当中删除内部对象。",
	["IN_INNER_EMPTY"] = [=[没有内部对象，

你可以通过下面的按钮添加一个。]=],
	["IN_INNER_ENTER_ID"] = "输入新的内部对象ID",
	["IN_INNER_ENTER_ID_NO_SPACE"] = "对象ID不能有空格，这不是对象的名字！",
	["IN_INNER_ENTER_ID_TT"] = [=[母对象中的内部对象ID必须是独一无二的。

|cffff9900请不要使用除了小写字母和下划线以外的字符，所有这类字符都会被转换为下划线。]=],
	["IN_INNER_HELP"] = [=[内部对象是存储于母对象内部的对象。]
举个例子：
|cffff9900
- 你想制造一个内含子弹的火枪。一般来说火枪是母对象，子弹是内部对象。
- 打开文档的邮件对象，邮件文档是这个邮件的内部对象。
- 任务：所有的对象/过场动画都是任务的内部对象。
|r内部对象的好处有：
|cff00ff00
- 内部对象的数据都在母对象当中，使用相同的版本号，数据也是随母对象交换的。
- 内部对象ID可以随意更改，因为有母对象ID作为前缀。同一个母对象里不能有相同ID的内部对象。
- 内部对象的效果更为出色。
- 你可以把母对象当做文件夹来管理内部对象，这样做的效率很高。
|r道理很简单，当你想做一个对象时，确定一下它能不能被作为一个内部对象。
|cff00ff00同时：文档和过场动画只能是内部对象！]=],
	["IN_INNER_HELP_TITLE"] = "什么是内部对象？",
	["IN_INNER_ID"] = [=[请给内部对象输入一个新ID |cff00ff00[%s]|r.

旧ID: |cff00ffff"%s"|r]=],
	["IN_INNER_ID_ACTION"] = "改变ID",
	["IN_INNER_ID_COPY"] = "复制",
	["IN_INNER_ID_COPY_TT"] = "你可以复制你的内部对象并粘贴到其他母对象里。",
	["IN_INNER_LIST"] = "内部对象清单",
	["IN_INNER_NO_AVAILABLE"] = "这个内部ID不可用！",
	["IN_INNER_PASTE_ACTION"] = "粘贴对象内容",
	["IN_INNER_PASTE_CONFIRM"] = "将这个内部对象的内容代替为你复制的内容吗？",
	["IN_INNER_S"] = "内部对象 ",
	["INV_PAGE_CAMERA_CONFIG"] = [=[摄像机参数:
   旋转: %.2f]=],
	["INV_PAGE_CHARACTER_INSPECTION"] = "角色检查",
	["INV_PAGE_CHARACTER_INSPECTION_TT"] = "检查这个角色的背包。",
	["INV_PAGE_CHARACTER_INV"] = "背包",
	["INV_PAGE_EDIT_ERROR1"] = "你必须是这个物品的作者才能编辑它。",
	["INV_PAGE_EDIT_ERROR2"] = "这个物品不是快速模式创建的。",
	["INV_PAGE_INV_OPEN"] = "打开背包",
	["INV_PAGE_ITEM_LOCATION"] = "物品在角色身上的位置",
	["INV_PAGE_LOOT_ALL"] = "拾取所有",
	["INV_PAGE_MARKER"] = [=[标记的位置:
   x: %.2f
   y: %.2f]=],
	["INV_PAGE_PLAYER_INV"] = "%s的背包",
	["INV_PAGE_QUICK_SLOT"] = " 行囊袋",
	["INV_PAGE_QUICK_SLOT_TT"] = "该栏位会作为主要容器。",
	["INV_PAGE_SEQUENCE"] = "序列 ID",
	["INV_PAGE_SEQUENCE_PRESET"] = "你可以设置对应某个表情的序列ID。",
	["INV_PAGE_SEQUENCE_TT"] = [=[你可以通过输入动作ID并选择关键帧来设定你角色的姿态。

警告：如果动画崩溃，是因为你的角色种族模型有错误，如果这种情况发生，请换一个动作。]=],
	["INV_PAGE_TOTAL_VALUE"] = "物品总价值",
	["INV_PAGE_TOTAL_VALUE_TT"] = [=[这是你背包物品的总价值。

这不是货币的数额，而是一个估计价值。]=],
	["INV_PAGE_WAIT"] = "等待响应",
	["INV_PAGE_WEAR_ACTION"] = "设定物品位置",
	["INV_PAGE_WEAR_ACTION_RESET"] = "重设位置",
	["INV_PAGE_WEAR_TT"] = [=[这个物品是可穿戴的。
绿色区域显示了它在角色身上的位置。]=],
	["INV_TU_1"] = [=[你可以在背包的每一个栏位摆放一个（或一叠）物品。
|cff00ff00由于你可以有无限个容器，因此你的背包容量实际上并没有限制。
|cffff9900你需要注意的是容器的最大容量。|r
如果你容器里的物品超出了容许的最大容量，它的耐久度会慢慢消耗，并有可能会把物品掉在地上！]=],
	["INV_TU_2"] = [=[放在这里的容器是主要容器。
|cffff9900请保持主容器一直有空栏，这是和其他玩家进行物品交换时的容器。
|cff00ff00主容器可以通过TRP工具栏打开。]=],
	["INV_TU_3"] = [=[对于在角色身上（而不是包里）的可穿戴物品，|cff00ff00你可以指定它在你角色身上的位置。
|cffff9900要这样做，点击物品旁边的圆点，并把他拖到角色上。你还可以旋转你的角色并给他设定动作。
|cff00ff00当其他人观察你的角色时，他们就会看到这些物品和它们的位置！
|r你可以通过点击他们并选择|cff00ff00"角色检查"|r 来观察其他角色。
|cffff9900玩家必须安装了TRP3 Extended才能互相检查。]=],
	["INV_TU_4"] = [=[向容器外拖放物品时， |cffff990你会被询问是要摧毁物品还是将其丢在地上。|r
你可以在世界上的绝大多数地方丢下物品。|cff00ff00并可以用“搜索物品”功能拾取他们。
你还可以打开地图使用“搜索我的物品”功能。
|cffff9900有时候物品会自己掉在地上：背包已满或是背包损坏的时候。]=],
	["INV_TU_5_V2"] = [=[你可以使用拖放或目标框架上的按钮来跟其他玩家交易物品（和游戏里一样）。

|cffff9900其他人给你物品时，交易窗口会提示它可能包括一些奇怪的效果。（没人希望他们的角色发出奇怪的喊声）

|r这时，TRP的安全机制会启动，将喊话转换为仅对你自己可见的文本，你可以选择关闭这个机制。

|cff00ff00你可以通过Alt+右击物品来这么做。]=],
	["IT_CAST"] = "制作",
	["IT_CO_DURABILITY"] = "耐久",
	["IT_CO_DURABILITY_TT"] = [=[决定你的容器的最大耐久度，容器会随时间丢失耐久度或损坏，容器可以被特定物品修复。

	|cff00ff000代表永不磨损]=],
	["IT_CO_MAX"] = "最大重量 (g/克)",
	["IT_CO_MAX_TT"] = [=[这确定了你的容器的最大容量，超过这个容量时容器会开始消耗耐久。

	|cff00ff000代表没有限制。
	
	|cffff9900请输入以克为单位的种类]=],
	["IT_CO_ONLY_INNER"] = "只能装载内部物品。",
	["IT_CO_ONLY_INNER_TT"] = [=[标记这个容器为只能装载它的子物品。
	
	目前，只有带这个选项的容器可以带内部物品交易。]=],
	["IT_CO_SIZE"] = "容器大小",
	["IT_CO_SIZE_COLROW"] = "%s |1行; 行; by %s 列",
	["IT_CON"] = "容器",
	["IT_CON_CAN_INNER"] = "不能把这个背包放进它自己里!",
	["IT_CON_ERROR_TRADE"] = "如果它不是空的，你不能删除这个背包。",
	["IT_CON_ERROR_TYPE"] = "这个背包不能容纳这种物品.",
	["IT_CON_OPEN"] = "打开/关闭背包",
	["IT_CON_TT"] = "容器 (%d/%d 已用)",
	["IT_CON_TT_MISSING_CLASS"] = "物品 ID 丢失",
	["IT_CONTAINER_TT"] = [=[将这个物品标记为容器，容器可以包含其他物品。

	|cff00ff00容器可以在物品编辑器的“容器”页修改。]=],
	["IT_CONVERT_TO_NORMAL"] = "转化为标准模式。",
	["IT_CONVERT_TO_NORMAL_TT"] = [=[你正在快捷模式中，这是个快速创建物品的简易
	模式。
	
	你可以在普通模式完善这个物品，它提供了更多功能但也更复杂。
	
	|cffff9900警告：被转变为普通模式的快捷物品无法被变回来。]=],
	["IT_CRAFTED"] = "手工制作的",
	["IT_CRAFTED_TT"] = "手工制作的物品会显示制作人的名字。这个制作人是通过手动添加或工作流生产这个物品的角色。",
	["IT_DISPLAY_ATT"] = "显示属性",
	["IT_DOC_ACTION"] = "阅读文档",
	["IT_DR_SOUND"] = "丢弃音效",
	["IT_EX_DOWNLOAD"] = "下载",
	["IT_EX_DOWNLOAD_TT"] = [=[|cffff9900这个物品有 %s 长，需要最少 %.1f 秒来下载（理想情况下）。

	|cff00ff00点击来请求 %s 发送给你所有有关这个物品的信息。
	
	|cffff9900在没有接收到所有的物品数据前不能结束交易。]=],
	["IT_EX_DOWNLOADING"] = "下载: %0.1f %%",
	["IT_EX_EMPTY"] = "没有需要交易的物品。",
	["IT_EX_EMPTY_DRAG"] = "你可以在这里拖拽物品.",
	["IT_EX_SLOT_DOWNLOAD"] = [=[|r你没有这个物品的信息。

	|cff00ff00如果这个物品不大，TRP3会从 %s 那里自动下载它。
	
	|cffff9900如果它太大了，你可以手动点击下载，下载可能会花一些数据。]=],
	["IT_EX_TRADE_BUTTON"] = "打开交换界面。",
	["IT_EX_TRADE_BUTTON_TT"] = "打开物品交换界面，让你可以和其他玩家交换物品。",
	["IT_FIELD_NAME"] = "物品名称",
	["IT_FIELD_NAME_TT"] = "这是你的物品名称，会显示在物品上。",
	["IT_FIELD_QUALITY"] = "物品质量",
	["IT_GAMEPLAY_ATT"] = "游戏属性",
	["IT_INV_ERROR_CANT_DESTROY_LOOT"] = "不能销毁这个拾取物。",
	["IT_INV_ERROR_CANT_HERE"] = "你不能把东西放在这。",
	["IT_INV_ERROR_FULL"] = "%s 满了.",
	["IT_INV_ERROR_MAX"] = "你不能携带更多的 %s 了。",
	["IT_INV_GOT"] = "接收到了 %s ，共 %d 个。",
	["IT_INV_SCAN_MY_ITEMS"] = "搜索我的物品",
	["IT_INV_SHOW_ALL"] = "打开所有背包",
	["IT_LOOT_ERROR"] = "现在无法显示可拾取物品，已经有一个可拾取物品在显示了。",
	["IT_NEW_NAME"] = "新的物品",
	["IT_NEW_NAME_CO"] = "新的容器",
	["IT_NO_ADD"] = "防止手动添加",
	["IT_NO_ADD_TT"] = "防止玩家通过工作流手动添加这个物品，只能通过工作流添加。",
	["IT_ON_USE"] = "使用时",
	["IT_ON_USE_TT"] = [=[当玩家使用这个项目时，这个工作流将被触发。

|cffff9900Note:|r 如果您想要为这个项目提供更多的工作流，您可以通过数据库视图将它转换为专家模式 (b通过右键单击并选择 |cff00ff00专家模式|r).]=],
	["IT_PU_SOUND"] = "拾取音效",
	["IT_PU_SOUND_1183"] = "包",
	["IT_PU_SOUND_1184"] = "书",
	["IT_PU_SOUND_1185"] = "衣服",
	["IT_PU_SOUND_1186"] = "食物",
	["IT_PU_SOUND_1187"] = "草药",
	["IT_PU_SOUND_1188"] = "锁链",
	["IT_PU_SOUND_1189"] = "肉",
	["IT_PU_SOUND_1190"] = "金属 大",
	["IT_PU_SOUND_1191"] = "金属 小",
	["IT_PU_SOUND_1192"] = "纸",
	["IT_PU_SOUND_1193"] = "戒指",
	["IT_PU_SOUND_1194"] = "石头",
	["IT_PU_SOUND_1195"] = "锁链 小",
	["IT_PU_SOUND_1196"] = "魔杖",
	["IT_PU_SOUND_1197"] = "液体",
	["IT_PU_SOUND_1198"] = "木 小",
	["IT_PU_SOUND_1199"] = "木 大",
	["IT_PU_SOUND_1221"] = "宝石",
	["IT_QUEST"] = "任务标记（！）",
	["IT_QUEST_TT"] = [=[对物品添加一个标记，表明它是任务的起始物品。

	|cffff7700这只是一个视觉标记，并不代表你的物品真的要开始一个任务。]=],
	["IT_QUICK_EDITOR"] = "快速创建物品",
	["IT_QUICK_EDITOR_EDIT"] = "快速编辑物品",
	["IT_SOULBOUND_TT"] = "这个物品会绑定到玩家，不能被丢在地上或者交易。",
	["IT_STACK"] = "堆叠",
	["IT_STACK_COUNT"] = "最大堆叠数量。",
	["IT_STACK_COUNT_TT"] = "设定这个物品可以堆叠的最大数量，总是大于1.",
	["IT_STACK_TT"] = "允许这个物品被堆叠在同一个栏位里。",
	["IT_TRIGGER_ON_DESTROY"] = "摧毁堆叠时",
	["IT_TRIGGER_ON_DESTROY_TT"] = [=[在玩家摧毁一叠这类物品时触发，|cffff9900

对每一叠物品生效，并在摧毁前触发。（此时统计背包物品数量仍会包括这些物品）]=],
	["IT_TRIGGER_ON_USE"] = "使用时",
	["IT_TRIGGER_ON_USE_TT"] = [=[玩家使用这个物品时触发。

|cff00ff00别忘了把物品标记为可使用。]=],
	["IT_TT_DESCRIPTION"] = "物品描述",
	["IT_TT_DESCRIPTION_TT"] = [=[这是你的物品描述，

	|cff00ff00请避免堆砌大段文字。
	
	如果你的物品可用，可以提示它如何使用。]=],
	["IT_TT_LEFT"] = "物品描述（左边）",
	["IT_TT_LEFT_TT"] = [=[物品名字下方的自由注释。

	|cff00ff00可以用于描述物品类型（护甲，书本，药剂）]=],
	["IT_TT_REAGENT"] = "材料标记",
	["IT_TT_REAGENT_TT"] = [=[对物品添加一个材料标记。

	|cffff7700这同样是一个视觉标记，并不真正代表你的物品是材料。]=],
	["IT_TT_RIGHT"] = "物品描述（右边）",
	["IT_TT_RIGHT_TT"] = [=[物品名字右下方的自由注释。

	|cff00ff00可以用来细化你的物品分类。
	
	如将“护甲”分为手套或是鞋子。]=],
	["IT_TT_VALUE"] = "物品价值",
	["IT_TT_VALUE_FORMAT"] = "物品价值 (单位为 %s)",
	["IT_TT_VALUE_TT"] = [=[这个值会在扩展物品界面（按alt）或交易时显示。

|cffff7700如果你认为物品是无价的，请输入0。这不代表物品不值钱，而是说它没有一个价值。]=],
	["IT_TT_WEIGHT"] = "物品重量",
	["IT_TT_WEIGHT_FORMAT"] = "物品重量（克）",
	["IT_TT_WEIGHT_TT"] = [=[物品的重量会影响你的容器。

|cffff7700请输入以克为标准的重量，它会被转换为你选择的重量。]=],
	["IT_UNIQUE_COUNT"] = "最大数量",
	["IT_UNIQUE_COUNT_TT"] = "设定一个玩家可以拥有这个物品的最大数量，总是大于0",
	["IT_UNIQUE_TT"] = "生效时，玩家可以持有这个物品的最大数量会被限制。",
	["IT_USE"] = "可用",
	["IT_USE_TEXT"] = "使用说明",
	["IT_USE_TEXT_TT"] = "这段文本显示在物品上，它说明了使用物品的效果。",
	["IT_USE_TT"] = [=[标记这个物品为可以使用。

|cff00ff00你可以通过工作流来编辑它的使用效果。]=],
	["IT_WARNING_1"] = "你不能制作一个同时可堆叠且可被制造的物品。 (%s)",
	["IT_WARNING_2"] = "你不能制作一个可堆叠的容器。 (%s)",
	["IT_WEARABLE"] = "可穿戴的",
	["IT_WEARABLE_TT"] = [=[使这个物品可以被角色穿戴并出现在角色检查界面。

	|cffff9900如果打钩，其他玩家可以看到你放在身上的这个物品，即使你没有给它设定具体位置。]=],
	["ITEM_ID"] = "物品 ID",
	["LOOT"] = "战利品",
	["LOOT_CONTAINER"] = "拾取容器",
	["LOOT_DISTANCE"] = "你离拾取位置太远了。",
	["MODE_EXPERT"] = "专家模式",
	["MODE_NORMAL"] = "标准模式",
	["MODE_QUICK"] = "快速魔兽",
	["NEW_EXTENDED_VERSION"] = "|cffff9900一个新的TRP3 Extended版本可用 (%s)， |cff00ff00去Curse上下载吧！",
	["NPC_EMOTES"] = "表情",
	["NPC_SAYS"] = "说",
	["NPC_WHISPERS"] = "悄悄说",
	["NPC_YELLS"] = "喊",
	["OP_ADD_TEST"] = "添加测试",
	["OP_AND"] = "和",
	["OP_AND_SWITCH"] = "切换为“和”",
	["OP_BOOL"] = "布尔变量",
	["OP_BOOL_FALSE"] = "FALSE",
	["OP_BOOL_TRUE"] = "TRUE",
	["OP_COMP_EQUALS"] = "等于",
	["OP_COMP_GREATER"] = "大于",
	["OP_COMP_GREATER_OR_EQUALS"] = "大等于",
	["OP_COMP_LESSER"] = "小于",
	["OP_COMP_LESSER_OR_EQUALS"] = "小等于",
	["OP_COMP_NEQUALS"] = "不等于",
	["OP_COMPA_SEL"] = "选择比较",
	["OP_CONFIGURE"] = "设定",
	["OP_CURRENT"] = "当前值",
	["OP_CURRENT_TT"] = "在聊天框显示基于当前情况的测试结果。",
	["OP_DIRECT_VALUE"] = "直接值",
	["OP_EVAL_VALUE"] = "估计值",
	["OP_FAIL"] = "失败信息",
	["OP_FAIL_TT"] = "如果条件未满足，显示这个信息，如果不想显示任何信息就留空。",
	["OP_FAIL_W"] = "失败工作流（专家模式）",
	["OP_FAIL_W_TT"] = [=[如果条件未满足，运行这个工作流，这是表达“否则”的一种方式。

|cffff9900请谨慎使用这一功能，失败工作流必须在同一物品内。

|cffff0000绝对不要建立无限循环的工作流！！！]=],
	["OP_NUMERIC"] = "数值",
	["OP_OP_CHAR_ACHIEVEMENT"] = "成就",
	["OP_OP_CHAR_ACHIEVEMENT_ACC"] = "账号",
	["OP_OP_CHAR_ACHIEVEMENT_ACC_TT"] = "检查这个账号上的任意角色是否完成了这个成就",
	["OP_OP_CHAR_ACHIEVEMENT_CHAR"] = "角色",
	["OP_OP_CHAR_ACHIEVEMENT_CHAR_TT"] = "检查这个角色是否完成了这个成就",
	["OP_OP_CHAR_ACHIEVEMENT_ID"] = "成就ID",
	["OP_OP_CHAR_ACHIEVEMENT_ID_TT"] = "你希望检查的成就的数字ID",
	["OP_OP_CHAR_ACHIEVEMENT_PREVIEW"] = "%s ，被 |cffff9900%s 完成",
	["OP_OP_CHAR_ACHIEVEMENT_TT"] = "检查这个账号是否完成了特定成就",
	["OP_OP_CHAR_ACHIEVEMENT_WHO"] = "完成于",
	["OP_OP_CHAR_CAM_DISTANCE"] = "视角距离",
	["OP_OP_CHAR_CAM_DISTANCE_TT"] = "视角和玩家的距离，0就是第一人称。",
	["OP_OP_CHAR_FACING"] = "角色面向",
	["OP_OP_CHAR_FACING_TT"] = [=[返回角色的面向 (单位是弧度，0为北方，逆时针增加。).

|cffff9900表示玩家面向的方向，玩家前进时不会变化]=],
	["OP_OP_CHAR_FALLING"] = "玩家在坠落",
	["OP_OP_CHAR_FALLING_TT"] = "检查玩家是否在坠落",
	["OP_OP_CHAR_FLYING"] = "玩家在飞行",
	["OP_OP_CHAR_FLYING_TT"] = "检查玩家是否在飞行",
	["OP_OP_CHAR_INDOORS"] = "玩家在室内",
	["OP_OP_CHAR_INDOORS_TT"] = "检查玩家是否在室内",
	["OP_OP_CHAR_MINIMAP"] = "小地图文本",
	["OP_OP_CHAR_MINIMAP_TT"] = [=[返回小地图文本

文本改变时触发游戏内"MINIMAP_ZONE_CHANGED" 事件。 你可以将它用于检测任务区域。]=],
	["OP_OP_CHAR_MOUNTED"] = "玩家在骑乘",
	["OP_OP_CHAR_MOUNTED_TT"] = "检查玩家有没有坐骑",
	["OP_OP_CHAR_RESTING"] = "玩家在休息",
	["OP_OP_CHAR_RESTING_TT"] = "检查玩家是否在休息，即他们是否在主城或者旅店里。",
	["OP_OP_CHAR_STEALTH"] = "玩家在潜行",
	["OP_OP_CHAR_STEALTH_TT"] = "检查玩家是否在潜行。",
	["OP_OP_CHAR_SUBZONE"] = "小区域名称",
	["OP_OP_CHAR_SUBZONE_TT"] = [=[玩家当前所处的小区域名称。

|cffff9900警告：这和服务器语言有关。]=],
	["OP_OP_CHAR_SWIMMING"] = "玩家在游泳。",
	["OP_OP_CHAR_SWIMMING_TT"] = "检查玩家是否在游泳，他们不需要在水下。",
	["OP_OP_CHAR_ZONE"] = "区域名称",
	["OP_OP_CHAR_ZONE_TT"] = [=[玩家当前所处的区域名称。

|cffff9900警告：这和服务器语言有关。]=],
	["OP_OP_CHECK_EVENT_VAR"] = "事件参数子串",
	["OP_OP_CHECK_EVENT_VAR_N"] = "事件参数子串值",
	["OP_OP_CHECK_EVENT_VAR_N_PREVIEW"] = "第 %s 个事件参数|cff00ff00(数字)",
	["OP_OP_CHECK_EVENT_VAR_N_TT"] = [=[检查触发这个事件的第N个参数。

作为一个数字返回。

如果参数不存在或无法解释，标记为0。]=],
	["OP_OP_CHECK_EVENT_VAR_PREVIEW"] = "第 %s 个事件参数|cff00ff00(字符)",
	["OP_OP_CHECK_EVENT_VAR_TT"] = [=[检查触发这个事件的第N个参数。

作为一个字符串返回。

如果参数不存在或无法解释，标记为“nil”。]=],
	["OP_OP_CHECK_VAR"] = "变量字符值",
	["OP_OP_CHECK_VAR_N"] = "变量数值",
	["OP_OP_CHECK_VAR_N_PREVIEW"] = "|cff00ffff%s: |cffff9900(n)|r %s",
	["OP_OP_CHECK_VAR_N_TT"] = [=[返回一个变量的值， |cff00ff00作为数字返回|r。

如果变量不存在，不可获取或无法解释，返回“0”。

|cffff9900这个值取决于工作流运行，因此无法预览。]=],
	["OP_OP_CHECK_VAR_PREVIEW"] = "|cff00ffff%s:|r %s",
	["OP_OP_CHECK_VAR_TT"] = [=[返回一个变量的值， |cff00ff00作为字符串返回|r。

	如果变量不存在或不可获取，返回“nil”。

|cffff9900这个值取决于工作流运行，因此无法预览。]=],
	["OP_OP_DATE_DAY"] = "日期：日",
	["OP_OP_DATE_DAY_OF_WEEK"] = "日期：一周中的某一日",
	["OP_OP_DATE_DAY_OF_WEEK_TT"] = "当天是周几，从1（周日）到7（周六）。",
	["OP_OP_DATE_DAY_TT"] = "本地时间日期。",
	["OP_OP_DATE_MONTH"] = "日期：月份",
	["OP_OP_DATE_MONTH_TT"] = "本地时间月份。",
	["OP_OP_DATE_YEAR"] = "日期：年",
	["OP_OP_DATE_YEAR_TT"] = "当前时间年份。",
	["OP_OP_DISTANCE_CURRENT"] = "使用当前位置",
	["OP_OP_DISTANCE_ME"] = "单位到玩家的距离",
	["OP_OP_DISTANCE_ME_TT"] = [=[返回一个单位和玩家之间的距离（码）

只对玩家有效。

在没有单位时返回0.

|cffff99007.1更新后对战场/副本/地下城无效。]=],
	["OP_OP_DISTANCE_POINT"] = "点坐标距离",
	["OP_OP_DISTANCE_POINT_PREVIEW"] = "|cff00ff00%s|r 到 |cff00ff00(%s, %s) 的举例",
	["OP_OP_DISTANCE_POINT_TT"] = [=[返回单位到某个点的距离（码）

	只对玩家有效。

	在没有单位时返回0.
	
	|cffff99007.1更新后对战场/副本/地下城无效。]=],
	["OP_OP_DISTANCE_X"] = "X 坐标",
	["OP_OP_DISTANCE_Y"] = "Y 坐标",
	["OP_OP_INV_CONTAINER_SLOT_ID"] = "容器栏位ID",
	["OP_OP_INV_CONTAINER_SLOT_ID_PREVIEW"] = "%s号栏位中的物品ID",
	["OP_OP_INV_CONTAINER_SLOT_ID_TT"] = "|cff00ff00某一容器栏位中的物品ID。|cffff9900只有工作流是被容器触发时生效。",
	["OP_OP_INV_COUNT"] = "物品数量",
	["OP_OP_INV_COUNT_ANY"] = "任意物品",
	["OP_OP_INV_COUNT_PREVIEW"] = "%s 个物品在 |cffff9900%s 当中",
	["OP_OP_INV_COUNT_TT"] = [=[|cff00ff00玩家背包里某个物品的数量。

ID留空即可统计所有物品。]=],
	["OP_OP_INV_ICON"] = "物品图标",
	["OP_OP_INV_ICON_PREVIEW"] = "%s的图标",
	["OP_OP_INV_ICON_TT"] = "|cff00ff00特定ID的物品的图标。",
	["OP_OP_INV_ITEM_WEIGHT"] = "物品重量",
	["OP_OP_INV_ITEM_WEIGHT_PREVIEW"] = "%s的重量",
	["OP_OP_INV_ITEM_WEIGHT_TT"] = "|cff00ff00特定ID的物品的重量。",
	["OP_OP_INV_NAME"] = "物品名称",
	["OP_OP_INV_NAME_PREVIEW"] = "%s的名字",
	["OP_OP_INV_NAME_TT"] = "|cff00ff00特定ID的物品的名字。",
	["OP_OP_INV_QUALITY"] = "物品品质",
	["OP_OP_INV_QUALITY_PREVIEW"] = "%s的品质",
	["OP_OP_INV_QUALITY_TT"] = "|cff00ff00特定ID的物品的品质。",
	["OP_OP_INV_VALUE"] = "物品价值",
	["OP_OP_INV_VALUE_PREVIEW"] = "%s的价值",
	["OP_OP_INV_VALUE_TT"] = "|cff00ff00特定ID的物品的价值。",
	["OP_OP_INV_WEIGHT"] = "容器总重",
	["OP_OP_INV_WEIGHT_PREVIEW"] = "|cffff9900%s 的总重量",
	["OP_OP_INV_WEIGHT_TT"] = "|cff00ff00容器和其内容物的总重量。",
	["OP_OP_QUEST_ACTIVE_CAMPAIGN"] = "激活的剧情",
	["OP_OP_QUEST_ACTIVE_CAMPAIGN_TT"] = "返回激活的剧情的ID，如果当前没有激活的剧情，返回无。",
	["OP_OP_QUEST_NPC"] = "单位是剧情NPC",
	["OP_OP_QUEST_NPC_TT"] = "|cff00ff00返回单位是否是自定义剧情当中的NPC",
	["OP_OP_QUEST_OBJ"] = "任务目标",
	["OP_OP_QUEST_OBJ_ALL"] = "所有任务目标",
	["OP_OP_QUEST_OBJ_ALL_PREVIEW"] = "%s 所有任务目标已完成",
	["OP_OP_QUEST_OBJ_ALL_TT"] = "返回所有的任务目标是否已完成，它们必须是已被揭露的。",
	["OP_OP_QUEST_OBJ_CURRENT"] = "当前目标",
	["OP_OP_QUEST_OBJ_CURRENT_PREVIEW"] = "%s 当前目标已完成",
	["OP_OP_QUEST_OBJ_CURRENT_TT"] = "返回当前揭露的任务目标是否已完成",
	["OP_OP_QUEST_OBJ_PREVIEW"] = " %s 目标，来自 %s",
	["OP_OP_QUEST_OBJ_TT"] = "返回任务目标的完成情况，如果没有被揭露，返回false",
	["OP_OP_QUEST_STEP"] = "当前任务步骤",
	["OP_OP_QUEST_STEP_PREVIEW"] = "%s 当前任务步骤",
	["OP_OP_QUEST_STEP_TT"] = "返回当前任务步骤的ID，如果没有揭露或没有任务，返回nil",
	["OP_OP_RANDOM"] = "随机",
	["OP_OP_RANDOM_FROM"] = "从",
	["OP_OP_RANDOM_PREVIEW"] = "从 |cff00ff00%s|r 到 |cff00ff00%s|r 之间的随机数。",
	["OP_OP_RANDOM_TO"] = "到",
	["OP_OP_RANDOM_TT"] = "两个值之间的随机数（整数）。",
	["OP_OP_TIME_HOUR"] = "时间：小时",
	["OP_OP_TIME_HOUR_TT"] = "当前时间的小时数，以服务器时间为准。",
	["OP_OP_TIME_MINUTE"] = "时间：分钟",
	["OP_OP_TIME_MINUTE_TT"] = "当前时间的分钟数，以服务器时间为准。",
	["OP_OP_UNIT_CLASS"] = "单位职业",
	["OP_OP_UNIT_CLASS_TT"] = "|cff00ff00小写英文的单位职业，和UnitClass返回的第二个参数一样。",
	["OP_OP_UNIT_CLASSIFICATION"] = "单位分类",
	["OP_OP_UNIT_CLASSIFICATION_TT"] = [=[|cff00ff00小写英文的单位职业，如： normal, elite, rare, worldboss, minus...

玩家一定是normal]=],
	["OP_OP_UNIT_CREATURE_FAMILY"] = "单位的种类",
	["OP_OP_UNIT_CREATURE_FAMILY_TT"] = "|cff00ff00单位的种类，只对野兽和恶魔有效，例如：螃蟹、狼、魅魔、虚空行者等",
	["OP_OP_UNIT_CREATURE_TYPE"] = "单位的物种",
	["OP_OP_UNIT_CREATURE_TYPE_TT"] = "|cff00ff00单位的物种，例如：野兽、龙类、元素等",
	["OP_OP_UNIT_DEAD"] = "单位已死亡",
	["OP_OP_UNIT_DEAD_TT"] = "|cff00ff00返回目标是否已死亡或是幽灵。",
	["OP_OP_UNIT_DISTANCE_INSPECT"] = "目标在附近（检查距离）",
	["OP_OP_UNIT_DISTANCE_INSPECT_TT"] = "|cff00ff00返回目标是否在检查距离（28码）内。",
	["OP_OP_UNIT_DISTANCE_TRADE"] = "目标在附近（交易）",
	["OP_OP_UNIT_DISTANCE_TRADE_TT"] = "|cff00ff00返回目标是否在交易距离（11.11码）内。",
	["OP_OP_UNIT_EXISTS"] = "目标存在",
	["OP_OP_UNIT_EXISTS_TT"] = [=[|cff00ff00返回目标是否存在。

|r存在是相对于玩家的，如果玩家有目标，则目标存在，如果玩家在与NPC互动，则NPC存在。]=],
	["OP_OP_UNIT_FACTION"] = "单位阵营",
	["OP_OP_UNIT_FACTION_TT"] = "|cff00ff00小写英文的单位阵营。",
	["OP_OP_UNIT_GUILD"] = "单位公会名",
	["OP_OP_UNIT_GUILD_RANK"] = "单位公会等级",
	["OP_OP_UNIT_GUILD_RANK_TT"] = "|cff00ff00单位的公会等级（如果有公会）。",
	["OP_OP_UNIT_GUILD_TT"] = "|cff00ff00单位的公会名字（如果有）。",
	["OP_OP_UNIT_HEALTH"] = "单位生命值",
	["OP_OP_UNIT_HEALTH_TT"] = "|cff00ff00单位的现有生命值（点数）",
	["OP_OP_UNIT_ID"] = "单位 ID",
	["OP_OP_UNIT_ID_TT"] = "|cff00ff00以 |cff00ff00'玩家名-服务器'|r 为形式的单位ID，服务器部分是必须的。",
	["OP_OP_UNIT_ISPLAYER"] = "单位是玩家",
	["OP_OP_UNIT_ISPLAYER_TT"] = "|cff00ff00返回单位是否是玩家。",
	["OP_OP_UNIT_LEVEL"] = "单位等级",
	["OP_OP_UNIT_LEVEL_TT"] = "|cff00ff00单位的等级",
	["OP_OP_UNIT_NAME"] = "单位名字",
	["OP_OP_UNIT_NAME_TT"] = [=[|cff00ff00单位的名字

|r 用在玩家上时，可能是|cff00ff00'玩家名'|r 或 |cff00ff00'玩家名-服务器'|r. 如果你希望使用 |cff00ff00'玩家名-ID'|r 的话请使用 |cff00ff00'单位ID'|r 。]=],
	["OP_OP_UNIT_NPC_ID"] = " 单位NPC ID",
	["OP_OP_UNIT_NPC_ID_TT"] = "|cff00ff00NPC的ID，只对NPC有效。",
	["OP_OP_UNIT_POSITION_X"] = "单位X坐标",
	["OP_OP_UNIT_POSITION_X_TT"] = [=[返回单位的X坐标。

只对玩家有效。

|cffff99007.1更新后对战场/副本/地下城无效。]=],
	["OP_OP_UNIT_POSITION_Y"] = "单位Y坐标",
	["OP_OP_UNIT_POSITION_Y_TT"] = [=[返回单位的Y坐标。

只对玩家有效。

|cffff99007.1更新后对战场/副本/地下城无效。]=],
	["OP_OP_UNIT_RACE"] = "单位种族",
	["OP_OP_UNIT_RACE_TT"] = [=[|cff00ff00小写英文的单位种族。

亡灵生物就是“Scourge”]=],
	["OP_OP_UNIT_SEX"] = "单位性别",
	["OP_OP_UNIT_SEX_TT"] = [=[|cff00ff00单位性别指数，2 = 雄性, 3 = 雌性。 1 是中立或未知。

|cffffff00作为字符串返回。]=],
	["OP_OP_UNIT_SPEED"] = "单位速度",
	["OP_OP_UNIT_SPEED_TT"] = "|cff00ff00以码/秒为单位的单位当前速度。行走是2.5，无BUFF奔跑是7.",
	["OP_OR"] = "或",
	["OP_OR_SWITCH"] = "切换为“或”",
	["OP_PREVIEW"] = "预览数值",
	["OP_REMOVE_TEST"] = "删除测试",
	["OP_STRING"] = "字符串值",
	["OP_UNIT"] = "单位类型",
	["OP_UNIT_NPC"] = "NPC",
	["OP_UNIT_PLAYER"] = "玩家",
	["OP_UNIT_TARGET"] = "目标",
	["OP_UNIT_TEST"] = "单位测试",
	["OP_UNIT_VALUE"] = "单位值",
	["QE_ACTION"] = "任务动作",
	["QE_ACTION_NO_CURRENT"] = "你没有激活的剧本，你应当在进行动作之前激活一个剧本。",
	["QE_ACTIONS_TYPE_INTERRACT"] = "交互",
	["QE_ACTIONS_TYPE_LISTEN"] = "听",
	["QE_ACTIONS_TYPE_LOOK"] = "检查",
	["QE_ACTIONS_TYPE_TALK"] = "说",
	["QE_AUTO_REVEAL"] = "自动揭示",
	["QE_AUTO_REVEAL_TT"] = "剧本开始时自动揭示任务。",
	["QE_AUTORESUME_CONFIRM"] = [=[剧本|cff00ff00[%s]可以被激活。|r.

要激活吗？
如果你已经有了激活的剧本，它的进度会保存。]=],
	["QE_BUTTON"] = "打开任务日志",
	["QE_CAMPAIGN"] = "剧本",
	["QE_CAMPAIGN_CURRENT"] = "现在的剧本.",
	["QE_CAMPAIGN_CURRENT_NO"] = "没有激活的剧本.",
	["QE_CAMPAIGN_EMPTY"] = "这个剧本没有任务.",
	["QE_CAMPAIGN_FULL"] = "完成",
	["QE_CAMPAIGN_LIST"] = "%s 可以接的剧本",
	["QE_CAMPAIGN_NO"] = "还没有开始",
	["QE_CAMPAIGN_NOQUEST"] = [=[这个剧本没有揭示的任务。
查看剧本注释来揭示你的任务。]=],
	["QE_CAMPAIGN_PAUSE"] = "暂停现在的剧本.",
	["QE_CAMPAIGN_RESET"] = "重置剧本",
	["QE_CAMPAIGN_RESUME"] = "恢复暂停 |cff00ff00[%s]|r.",
	["QE_CAMPAIGN_START"] = "开始剧本 |cff00ff00[%s]|r.",
	["QE_CAMPAIGN_START_BUTTON"] = "开始或继续剧本",
	["QE_CAMPAIGN_UNSTARTED"] = [=[你还不能开始这个剧本.
点击顶部"开始"按钮来开始.]=],
	["QE_CAMPAIGNS"] = "所有剧本",
	["QE_COMPLETED"] = "完成",
	["QE_DESCRIPTION"] = "任务概要",
	["QE_DESCRIPTION_TT"] = "这段概要会在任务日志的任务界面可见。",
	["QE_FAILED"] = "失败",
	["QE_LINKS_ON_OBJECTIVE"] = "任务目标完成时",
	["QE_LINKS_ON_OBJECTIVE_TT"] = [=[玩家完成这个任务的目标时触发。

|cff00ff00可以用于检查所有目标已完成并揭示下一个任务。]=],
	["QE_LINKS_ON_START"] = "任务开始时",
	["QE_LINKS_ON_START_TT"] = [=[任务开始时触发 |cff00ff00一次|r。

|cff00ff00这是任务的第一步。]=],
	["QE_MACRO"] = "创建宏",
	["QE_MACRO_MAX"] = "你不能再有更多的宏了，请清理一些宏栏位。",
	["QE_MACRO_TT"] = "为这个动作创建一个宏并把它放在鼠标上以便放置到动作条。",
	["QE_NAME"] = "任务名字",
	["QE_NAME_NEW"] = "新的任务",
	["QE_NAME_TT"] = "这是你任务日志里显示的人物名字。",
	["QE_NEW"] = "新的任务已揭示",
	["QE_NOACTION_ACTION"] = "这里没有任何事情.",
	["QE_NOACTION_LISTEN"] = "你没有听到任何特殊的声音.",
	["QE_NOACTION_LOOK"] = "你没有看到任何特殊的地方.",
	["QE_NOACTION_TALK"] = "无话可说.",
	["QE_NPC"] = "剧本 NPC",
	["QE_OBJ"] = "任务目标",
	["QE_OBJ_ADD"] = "添加任务目标",
	["QE_OBJ_AUTO"] = "自动揭示",
	["QE_OBJ_AUTO_TT"] = "任务解锁时自动揭示任务目标。",
	["QE_OBJ_ID"] = "目标 ID",
	["QE_OBJ_ID_TT"] = "这是任务目标ID，一个任务里不能有两个ID相同的目标。",
	["QE_OBJ_NO"] = "没有任务目标",
	["QE_OBJ_REMOVE"] = "删除这个任务目标?",
	["QE_OBJ_SINGULAR"] = "任务目标",
	["QE_OBJ_TEXT"] = "目标文本",
	["QE_OBJ_TT"] = [=[任务目标是玩家的提示。完成所有目标不会自动完成任务。你决定什么时候显示目标，这样你就可以在你的任务中有一个秘密目标。
|cffff9900在任务日志中，总是按照目标ID排序，而不是按照它们的显示顺序。]=],
	["QE_OVERVIEW"] = "任务综述",
	["QE_PREVIOUS_STEP"] = "前一步",
	["QE_PROGRESS"] = "进度",
	["QE_PROGRESS_TT"] = [=[这个指标表示了这个任务在剧本当中的进度（即使任务没有揭示）。

	这是一个百分比，显示了完成的任务占总任务量的比率。
	
	|cff00ff00一般来说都是勾选的。]=],
	["QE_QUEST"] = "任务",
	["QE_QUEST_LIST"] = "这个剧本的任务",
	["QE_QUEST_OBJ_AND_HIST"] = "任务目标和历史",
	["QE_QUEST_OBJ_FINISHED"] = "|cffffff00任务完成: |cff00ff00%s",
	["QE_QUEST_OBJ_REVEALED"] = "|cffffff00新目标 : |cff00ff00%s",
	["QE_QUEST_OBJ_UPDATED"] = "|cffffff00任务更新: |cff00ff00%s",
	["QE_QUEST_START"] = "开始任务 |cff00ff00[%s]|r.",
	["QE_QUEST_TT_STEP"] = [=[|cffffff00当前:|r
"%s"]=],
	["QE_QUESTS"] = "任务",
	["QE_QUESTS_HELP"] = [=[你可以在这里增加你的任务. 当他开始你的剧本时，任务不会自动添加到玩家的任务日志中.你必须通过工作流程来完成任务.
|cffff9900任务按照ID在任务日志中进行排序，而不是通过名称或显示顺序.]=],
	["QE_RESET_CONFIRM"] = [=[重置这个剧本吗？

你会丢失所有的任务进度。

通过任务获得的物品都可以保存。]=],
	["QE_ST_AUTO_REVEAL"] = "第一步",
	["QE_ST_AUTO_REVEAL_TT"] = "将这一步标记为解锁任务时的第一步。",
	["QE_ST_END"] = "最后一步",
	["QE_ST_END_TT"] = "将这一步标记为任务的最后一步，到达这一步时，任务会被标记为完成。",
	["QE_ST_LINKS_ON_LEAVE"] = "离开步骤",
	["QE_ST_LINKS_ON_LEAVE_TT"] = " |cff00ff00每次|r 玩家离开这个任务步骤前往下一个时触发，这将在下一步的 \"步骤开始\" 之前触发。",
	["QE_ST_LINKS_ON_START"] = "步骤开始",
	["QE_ST_LINKS_ON_START_TT"] = "|cff00ff00每次|r玩家到达这一步时触发。",
	["QE_ST_POST"] = "任务历史记录",
	["QE_ST_PRE"] = "任务内容",
	["QE_STEP"] = "任务步骤",
	["QE_STEP_ADD"] = "添加任务步骤",
	["QE_STEP_CREATE"] = [=[请输入步骤ID，一个任务里不能有两个相同的步骤ID。

	|cffff9900所有的步骤ID会以字母顺序排序。
	
	|cff00ff00因此以Step_#这种格式编辑较为合理。]=],
	["QE_STEP_DD_COPY"] = "复制步骤内容",
	["QE_STEP_DD_PASTE"] = "粘贴步骤内容",
	["QE_STEP_DD_REMOVE"] = "删除步骤",
	["QE_STEP_EXIST"] = "ID %s已经有一个步骤了。",
	["QE_STEP_LIST"] = "这个任务的步骤",
	["QE_STEP_LIST_CURRENT"] = "可用的任务",
	["QE_STEP_LIST_FINISHED"] = "完成的任务",
	["QE_STEP_MISSING"] = "缺少步骤信息.",
	["QE_STEP_NAME_NEW"] = "新的任务步骤",
	["QE_STEP_NO"] = "没有任务步骤",
	["QE_STEP_REMOVE"] = "删除这一步骤?",
	["QE_STEP_TT"] = [=[每个任务都被分割为几个步骤。
	每一个步骤都可以在到达的时候显示一个说明并在完成时显示另一个。]=],
	["QE_STEPS"] = "任务步骤",
	["QUEST_ID"] = "任务 ID",
	["QUEST_TU_1"] = [=[任务通常会要求你 |cff00ff00和NPC或周边环境互动|r。
有四种动作可以选择： |cff00ff00聆听，观察，交谈和互动。|r.
你可以通过 |cff00ff00右击工具栏上的任务图标来进行这种动作|r。
但更简便的方法是使用|cff00ff00宏|r。你可以通过这个按钮来创建宏。]=],
	["QUEST_TU_2"] = [=[|cff00ff00这是你当前可用的剧本。|r
剧本是一个或多个任务的集合。
|cffff9900你一次只能进行一个剧本。|r首先需要激活剧本。 |cff00ff00你可以点击“开始或继续”来激活一个剧本|r
切换剧本不会丢失进度。
|cffff9900你可以通过右键点击重置剧本，通过剧本获得的物品不会删除。]=],
	["QUEST_TU_3"] = [=[|cff00ff00你在这里可以找到所有的可用任务和完成的任务。|r
你可以看到任务的状况和它们得目标。]=],
	["QUEST_TU_4"] = [=[|cff00ff00你在这里可以看到任务的进度和所有的任务目标。|r
你还可以看到之前的步骤以帮助你想起一些东西。]=],
	["ROOT_CREATED"] = "%s 在 %s 创建",
	["ROOT_CREATED_BY"] = "创建者",
	["ROOT_CREATED_ON"] = "创建在",
	["ROOT_GEN_ID"] = "产生的ID",
	["ROOT_ID"] = "对象ID",
	["ROOT_SAVED"] = "最后一次修改是%s 在 %s",
	["ROOT_TITLE"] = "根对象",
	["ROOT_VERSION"] = "版本",
	["SEC_EFFECT_BLOCKED"] = "效果已被屏蔽",
	["SEC_EFFECT_BLOCKED_TT"] = [=[根据你当前的安全设定，这个物品的一个效果已经被屏蔽。

|cffff9900点击来检查物品的安全信息。

你也可以在背包里通过Ctrl+右击来更改安全信息。]=],
	["SEC_HIGH"] = "高",
	["SEC_HIGH_TT"] = "这个物品的安全等级是高，不会带来不想要的效果。",
	["SEC_LEVEL"] = "安全等级",
	["SEC_LEVEL_DETAIL"] = "点击显示不安全的代码细节。",
	["SEC_LEVEL_DETAIL2"] = "点击显示不安全的代码细节并决定哪些可以执行。",
	["SEC_LEVEL_DETAILS"] = "安全细节",
	["SEC_LEVEL_DETAILS_ACCEPTED"] = "接受",
	["SEC_LEVEL_DETAILS_ALL"] = "调整所有对象的安全性",
	["SEC_LEVEL_DETAILS_ALL_TT"] = "允许所有对象执行内部效果。",
	["SEC_LEVEL_DETAILS_BLOCKED"] = "阻挡",
	["SEC_LEVEL_DETAILS_FROM"] = "总是阻挡来自 %s的效果。",
	["SEC_LEVEL_DETAILS_SECURED"] = "这个对象和它所有的内部对象都是安全的！",
	["SEC_LEVEL_DETAILS_THIS"] = "调整这个对象的安全性。",
	["SEC_LEVEL_DETAILS_THIS_TT"] = "只允许这个对象执行效果。",
	["SEC_LEVEL_DETAILS_TT"] = [=[对于 %s 和它所有的内部对象：
|cffff9900作者： |cff00ff00%s
|cffff9900来自： |cff00ff00%s]=],
	["SEC_LOW"] = "低",
	["SEC_LOW_TT"] = "这个物品包含了多于一个的导致不愉快内容的效果。",
	["SEC_MEDIUM"] = "中等",
	["SEC_MEDIUM_TT"] = "这个物品包含了多于一个的可能导致不愉快内容的效果。",
	["SEC_MISSING_SCRIPT"] = "找不到工作流 \"%s\"",
	["SEC_REASON_DISMOUNT"] = "解散坐骑",
	["SEC_REASON_DISMOUNT_WHY"] = [=[这个物品会强制你解散坐骑。

|cffff9900这可能并不是你想要的，尤其是在飞行的时候。]=],
	["SEC_REASON_EMOTE"] = "角色表情",
	["SEC_REASON_EMOTE_WHY"] = "该物品会强制你的角色发出表情。 |cffff0000它可能会出于恶意强制你用表情刷屏，从而导致你可能被游戏封禁。 |cff00ff00如果禁用，表情将只为你个人显示而不是被你的角色发送到服务器。",
	["SEC_REASON_MACRO"] = "执行一个宏",
	["SEC_REASON_MACRO_WHY"] = [=[这个物品可能触发任何一个宏命令。

|cffff0000它可能会释放技能或使用物品，它也可能执行任何会影响你的物品，金币，公会的Lua指令，也可能使你发表违法暴雪服务条例从而导致封禁的语言。 

|cff00ff00如果选择阻挡，宏命令将不被执行，而是显示在聊天框当中。]=],
	["SEC_REASON_SCRIPT"] = "Lua 脚本",
	["SEC_REASON_SCRIPT_WHY"] = [=[这个物品可能会产生任何TRPE的效果。

|cffff0000它可能强制使你发言，这可能违犯暴雪条款并导致你被封禁。

|cff00ff00如果选择阻挡，代码仍然会被执行，但会在安全环境下执行（只显示在你的聊天框当中）。]=],
	["SEC_REASON_SOUND"] = "播放声音",
	["SEC_REASON_SOUND_WHY"] = [=[这个物品会播放声音并让附近的其他玩家听到。

|cffff9900他们可能并不想听到这些声音并可能屏蔽你。

|cff00ff00如果选择阻挡，只有你能听到声音。]=],
	["SEC_REASON_TALK"] = "角色发言",
	["SEC_REASON_TALK_WHY"] = [=[这个物品会强制你的角色做出说话/喊话或表情动作。

|cffff0000这可能违犯暴雪条款并导致你被封禁。

|cff00ff00如果选择阻挡，代码仍然会被执行，但会在安全环境下执行（只显示在你的聊天框当中）。]=],
	["SEC_RESOLUTION_ALL"] = "对于所有物品",
	["SEC_RESOLUTION_AUTHOR"] = "你是作者",
	["SEC_RESOLUTION_THIS_OBJECT"] = "仅为此对象",
	["SEC_RESOLUTION_WHITELISTED"] = "白名单中的发送者",
	["SEC_SCRIPT_ERROR"] = "工作流 %s 错误",
	["SEC_TT_COMBO"] = "Alt+右击|cffff9900 调整安全性",
	["SEC_TT_COMBO_2"] = "调整安全性",
	["SEC_UNSECURED_WHY"] = "这为什么不安全？",
	["SET_TT_DETAILS_1"] = "按住Alt显示更多",
	["SET_TT_DETAILS_2"] = "%s 个警告",
	["SET_TT_OLD"] = "这个物品是老版本TRPE创建的(v %s)，可能导致不兼容。",
	["SET_TT_SECURED"] = [=[一些可能的恶意效果已被阻拦。
|cff00ff00Alt+右击显示更多细节。]=],
	["SET_TT_SECURED_2"] = "一些可能的恶意效果已被阻拦。",
	["SET_TT_SECURED_2_1"] = "显示更多细节",
	["SPECIFIC"] = "特殊对象",
	["SPECIFIC_INNER_ID"] = "内部 ID",
	["SPECIFIC_MODE"] = "模式",
	["SPECIFIC_PATH"] = "根路径",
	["TB_TOOLS"] = "扩展对象数据库",
	["TB_TOOLS_TT"] = "创建你自己的物品和任务.",
	["TU_AC_1_TEXT"] = [=[|cff00ff00动作链接|r 用于将工作流链接到任务动作。
	玩家可以进行四种任务动作： |cff00ff00聆听，观察，交谈和互动。|r.
	你可以将动作链接到剧本、任务或任务步骤。]=],
	["TU_AC_2"] = "动作分析",
	["TU_AC_2_TEXT"] = [=[每一个动作都可以通过 |cff00ff00Ctrl+左击|r 添加条件。
	玩家进行动作时， |cff00ff00所有的动作链接会被按特定顺序分析|r，从任务步骤开始，到任务，再到剧本。
	如果链接可以使用（链接类型合理，满足条件或没有条件），相关的工作流就会执行，同时 |cffff9900插件会停止搜索另一个链接|r。]=],
	["TU_CO_1_TEXT"] = [=[容器是一个能装入其他物品的物品。
	你可以通过在物品栏里 |cff00ff00双击|r 来打开它。
	容器也可以被设置为可使用物品，这两种功能并不冲突。
	|cffff9900请注意，目前你只能交易给其他玩家空容器或包含其内部物品的容器。请参考内部物品页面来获取更多信息。]=],
	["TU_CS_1_TEXT"] = [=[你可以通过 |cff00ff00过场动画|r 来创建视觉化的信息。
	过场动画和Storyline这个插件的格局是一样的。]=],
	["TU_CS_2_TEXT"] = [=[过场动画是一步步播放的。
	它看起来像是两个角色的对话。
	你可以手动修改过场动画的每一步。]=],
	["TU_CS_3_TEXT"] = [=[步骤文本会在你输入双线的时候被分割为小步骤，但他们共用同一个步骤设置。
	一般来说当你想切换说话的角色的时候就可以切换步骤了。
	当你想切换步骤的时候，请|cff00ff00保证参数是激活的（？）。]=],
	["TU_CS_4"] = "过场动画和工作流",
	["TU_CS_4_TEXT"] = [=[你可以将工作流链接到一个步骤，他将在步骤开始的时候被执行。
	如果工作流有拾取效果，你可以勾选“等待拾取”以强制玩家在播放动画前拾取物品。]=],
	["TU_CS_5"] = "预览",
	["TU_CS_5_TEXT"] = [=[你可以随时预览过场动画。
	|cffff9900L预览时链接的工作流不会执行。]=],
	["TU_DB_1_TEXT"] = [=[|cff00ff00欢迎来到数据库教学。|r
	这里是数据库，存储了所有的对象。
	对象当中包括了物品、文档、剧本/任务/任务步骤的所有信息。]=],
	["TU_DB_2"] = "数据库类型",
	["TU_DB_2_TEXT"] = [=[数据库有四个过滤标签。
	|cff00ff00我的数据库：|r 包含了所有你创建的对象。
	|cff00ff00玩家数据库：|r 包含所有你从其他玩家那里收到/导入的对象。
	|cff00ff00开发者数据库：|r 包含TRP3开发组制作的所有物品。
	|cff00ff00完整数据库：|r 包含上面三个分类的所有对象。]=],
	["TU_DB_3_TEXT"] = [=[你可以在任何数据库当中通过过滤|cff00ff00搜索|r 功能来找到你想要的物品。
	如果没有过滤，数据库是树状结构显示。
	如果有过滤，显示结构则是扁平的。
	点击过滤面板的|cff00ff00清除|r 按钮即可退出过滤模式。]=],
	["TU_DB_4"] = "根对象和内部对象",
	["TU_DB_4_TEXT"] = [=[对象包括两种， |cff00ff00根对象和内部对象。|r.
	|cff00ff00内部对象|r are alw总是储存在 |cff00ff00根对象|r 内部（即使他们是其他子对象的内部对象，但最终仍然指向根对象）。
	你和其他玩家交换对象时，实际上会交换包括根对象在内的所有信息（即使你交换的是一个内部对象。）
	因此，可以把需要一起交换的数据全部设置为某个对象的内部对象。
	例如：
	文档物品：文档总是文档物品的内部对象。
	有四个任务的剧本：任务总是剧本的内部对象。
	发射子弹物品的火枪物品：子弹总是火枪的内部对象。
	不用担心难以设置，这是自然的！]=],
	["TU_DB_5"] = "根对象",
	["TU_DB_5_TEXT"] = [=[只有物品和剧本可以是根对象

	你可以用这两个按钮创建物品和剧本。]=],
	["TU_DB_6"] = "创建一个物品",
	["TU_DB_6_TEXT"] = [=[创建新物品时，你可以使用快速创建模式或使用模板。
	|cff00ff00快速创建|r 模式可以让你快速建立物品，但可用的功能有限。你之后可以将其转化为标准模式。
	使用|cff00ff00空白物品|r 模板来从头建立一个物品。
	|cff00ff00文档物品|r 会产生两个对象，物品本身和它内部的文档对象。它还会调整对象使其在使用时显示文档。
	|cff00ff00容器物品|r会创建一个可以作为容器的物品。
	最后|cff00ff00以……为模板创建|r可以让你复制已有的物品。]=],
	["TU_DB_7"] = "对象行",
	["TU_DB_7_TEXT"] = "每一行都是一个对象，你可以左击编辑它，或右击操作它。",
	["TU_EL_1_TEXT"] = [=[你可以在事件链接页面|cff00ff00将工作流链接到事件|r。
	|cffff9900工作流不是自动执行的！|r 你需要将它们链接到事件，以便在事件发生时执行他们。
	事件分为两类：|cff00ff00对象事件和游戏事件。|r]=],
	["TU_EL_2_TEXT"] = [=[|cff00ff00对象事件 |r 是基于TRP3架构的事件。
	根据对象类型的不同，可用的事件也是不同的。
	一个事件只能链接一个工作流，但一个工作流可以被多个事件链接。]=],
	["TU_EL_3_TEXT_V2"] = [=[|cff00ff00游戏事件|r 是当一些情况发生的时候游戏触发的事件。
		每个链接都会将一个游戏事件链接到一个工作流。事件发生的似乎很工作流就会被执行。
		|cff00ff00你可以通过Ctrl+左击给链接附加条件|r 条件将会访问需要的参数。
		例如你监测释放法术的事件，你就可以将法术释放完成作为条件。
		|cffff9900游戏内事件非常多，你可以参考wowwiki来获取详细列表。
		http://wowwiki.wikia.com/wiki/Event_API
	
	|r除了游戏内事件之外， |cff00ff00TRP3 Extended还提供一些其他事件|r 并在插件官方wiki列出。
	|cff00ff00https://github.com/Ellypse/Total-RP-3-Extended/wiki|r]=],
	["TU_EL_4_TEXT"] = "|cff00ff00游戏事件|r 只能在剧本/任务/任务步骤当中使用。",
	["TU_IT_1_TEXT"] = [=[|cff00ff00欢迎来到物品创建教程。|r
	物品是可以放在玩家物品栏里或扔在地上的对象。
	这里是主界面，可以定义物品的各类属性。]=],
	["TU_IT_2"] = "显示属性",
	["TU_IT_2_TEXT"] = "属性完全是视觉化的，并没有游戏内的各种效果。",
	["TU_IT_3"] = "自由记录",
	["TU_IT_3_TEXT"] = [=[你可以写下一些能帮助你构思物品的东西。
		这也可以帮助其他人理解你的物品。]=],
	["TU_IT_4"] = "游戏性属性",
	["TU_IT_4_TEXT"] = [=[游戏性属性会影响游戏性。
	其中有两个很关键： |cff00ff00可使用|r 和 |cff00ff00容器|r，勾选他们会启用 |cff00ff00工作流|r 和 |cff00ff00容器|r 编辑标签。]=],
	["TU_TITLE"] = "教学",
	["TU_WO_1_TEXT"] = [=[|cff00ff00欢迎来到工作流教学。|r
工作流是一个可以让你发挥创造力的机制。你可以显示文本，播放声音，或者获得物品。]=],
	["TU_WO_2"] = "工作流列表",
	["TU_WO_2_TEXT"] = [=[|cff00ff00工作流列表|r 在左边。
你可以通过右击来删除、修改和重命名工作流。
|cffff9900标准模式没有工作流列表，只有一个“使用时”工作流。如果你希望有多个工作流，请把它转为专家模式物品。]=],
	["TU_WO_3_TEXT"] = [=[这里是所有的工作流元素。
元素可以是效果、延迟或条件。
元素的顺序非常重要，工作流触发时它们是按顺序运行的。
你可以通过元素上的箭头改变它们的顺序。]=],
	["TU_WO_4"] = "增加一个效果",
	["TU_WO_4_TEXT"] = [=[类似“播放声音”，“显示文字”，“播放过场动画”这样的效果。.
效果有很多，每一个效果的注释里都有详细描述。]=],
	["TU_WO_5"] = "增加条件",
	["TU_WO_5_TEXT"] = [=[条件可以让你 |cff00ff00进行一些测试从而停止工作流运行。|r
|cffff9900如果条件不满足，工作流就不会继续运行。|r
条件是一系列由“与”和“或”连接起来的逻辑测试。
每个测试都是一个数值对比，比如“目标生命值小于500”， “玩家没有死亡”或“玩家背包里的X物品多余N个”。]=],
	["TU_WO_6"] = "添加延迟",
	["TU_WO_6_TEXT"] = "延迟可以把工作流运行中断一定时间，但延迟也可以作为施法时间使用。",
	["TU_WO_ERROR_1"] = "请在继续教程前建立一个工作流。",
	["TYPE"] = "类型",
	["TYPE_CAMPAIGN"] = "剧本",
	["TYPE_DIALOG"] = "过场动画",
	["TYPE_DOCUMENT"] = "文档",
	["TYPE_ITEM"] = "物品",
	["TYPE_ITEMS"] = "物品(s)",
	["TYPE_LOOT"] = "战利品",
	["TYPE_QUEST"] = "任务",
	["TYPE_QUEST_STEP"] = "任务步骤",
	["UNIT_FRIES"] = "薯条",
	["UNIT_POTATOES"] = "土豆",
	["WO_ACTIONS_LINKS"] = "动作链接",
	["WO_ACTIONS_LINKS_TT"] = [=[你在这里可以把玩家的任务动作链接到工作流。
	动作包括： |cff00ff00互动，聆听，交谈和检查|r
	每个链接都可以添加条件。]=],
	["WO_ADD"] = "创建工作流",
	["WO_ADD_ID"] = [=[|cff00ff00输入工作流ID|r

	这是你管理工作流的内部ID，物品使用者并不可见。
	
	同一对象内不能有同名工作流。]=],
	["WO_ADD_ID_NO_AVAILABLE"] = "这个工作流 ID 无效.",
	["WO_COMMON_EFFECT"] = "一般效果",
	["WO_CONDITION"] = "条件",
	["WO_CONDITION_TT"] = [=[判定一个条件。
判定失败时终止工作流。]=],
	["WO_CONTEXT"] = "环境",
	["WO_CONTEXT_TT"] = "工作流环境确定了可以在工作流中使用哪些效果.",
	["WO_COPY"] = "复制工作流环境",
	["WO_DELAY"] = "延时",
	["WO_DELAY_CAST"] = "施法",
	["WO_DELAY_CAST_SOUND"] = "施法音效 ID",
	["WO_DELAY_CAST_SOUND_TT"] = [=[施法音效的声音ID，可以填写一个可循环播放的声音，当施法停止时音效也会停止。

|cff00ff00例如： 12273, 12361, ...]=],
	["WO_DELAY_CAST_TEXT"] = "施法文字",
	["WO_DELAY_CAST_TEXT_TT"] = "施法条上的文字",
	["WO_DELAY_DURATION"] = "持续时间",
	["WO_DELAY_DURATION_TT"] = "延时的时长，以秒计算",
	["WO_DELAY_INTERRUPT"] = "中断",
	["WO_DELAY_INTERRUPT_1"] = "不中断",
	["WO_DELAY_INTERRUPT_2"] = "移动时中断",
	["WO_DELAY_SECONDS"] = "秒",
	["WO_DELAY_TT"] = [=[暂停工作流。
可以用于延时或者施法]=],
	["WO_DELAY_TYPE"] = "延时类型",
	["WO_DELAY_TYPE_1"] = "正常延时",
	["WO_DELAY_TYPE_1_TT"] = "暂停工作流一定时间，不向玩家反馈任何信息。",
	["WO_DELAY_TYPE_2"] = "施法",
	["WO_DELAY_TYPE_2_TT"] = "在工作流延时期间显示一个施法条",
	["WO_DELAY_WAIT"] = "等待",
	["WO_EFFECT"] = "效果",
	["WO_EFFECT_CAT_COMMON"] = "通常",
	["WO_EFFECT_NO_EDITOR"] = "这个效果不能编辑。",
	["WO_EFFECT_SELECT"] = "选择一个效果",
	["WO_EFFECT_TT"] = [=[激活一个效果。
它可以是播放声音，显示文字等。]=],
	["WO_ELEMENT"] = "编辑元素",
	["WO_ELEMENT_ADD"] = "将元素添加到工作流",
	["WO_ELEMENT_COND"] = "编辑效果条件",
	["WO_ELEMENT_COND_NO"] = "删除效果条件",
	["WO_ELEMENT_COND_TT"] = "对这个效果添加一个条件",
	["WO_ELEMENT_COPY"] = "复制元素内容",
	["WO_ELEMENT_EDIT"] = "点击编辑元素",
	["WO_ELEMENT_EDIT_CTRL"] = "Ctrl+左击来设定条件",
	["WO_ELEMENT_EDIT_RIGHT"] = "右击显示更多操作",
	["WO_ELEMENT_PASTE"] = "粘贴元素内容",
	["WO_ELEMENT_TYPE"] = "选择元素类型",
	["WO_EMPTY"] = [=[你可以给你的工作流增加元素。
元素可以是效果、条件或延迟。]=],
	["WO_END"] = "工作流结束",
	["WO_EVENT_EX_ADD"] = "添加事件链接。",
	["WO_EVENT_EX_BROWSER_COMBAT_LOG_ERROR"] = "无法显示参数，请参考Wowpedia",
	["WO_EVENT_EX_BROWSER_NO_PAYLOAD"] = "没有参数",
	["WO_EVENT_EX_BROWSER_OPEN"] = "打开事件浏览器",
	["WO_EVENT_EX_BROWSER_TITLE"] = "事件浏览器",
	["WO_EVENT_EX_CONDI"] = "事件链接条件编辑器",
	["WO_EVENT_EX_EDITOR"] = "事件链接编辑器",
	["WO_EVENT_EX_LINK"] = "游戏事件链接",
	["WO_EVENT_EX_LINKS"] = "游戏事件链接",
	["WO_EVENT_EX_LINKS_TT"] = [=[在这里你可以将你的工作流与游戏事件联系起来.
每个环节都是有条件的.]=],
	["WO_EVENT_EX_NO"] = "没有事件链接",
	["WO_EVENT_EX_UNKNOWN_ERROR"] = "[错误]未知事件 %s 在 %s 中",
	["WO_EVENT_ID"] = "事件 ID",
	["WO_EVENT_ID_TT"] = [=[事件的ID。 

你可以在WowWiki或者WoWpedia上找到完整的事件列表

例如： PLAYER_REGEN_DISABLED 在玩家进入战斗时触发。]=],
	["WO_EVENT_LINKS"] = "对象事件链接",
	["WO_EXECUTION"] = "执行工作流",
	["WO_EXPERT"] = "专家模式",
	["WO_EXPERT_DONE"] = "将 %s 转化为专家模式，释放你的想象力吧！",
	["WO_EXPERT_EFFECT"] = "专家模式效果",
	["WO_EXPERT_TT"] = [=[工作流是可以让你的对象活动起来的一系列设定。

你在这里可以设定你的对象的工作流，并把它们链接到事件链接当中。]=],
	["WO_LINKS"] = "事件链接",
	["WO_LINKS_NO_LINKS"] = "没有链接",
	["WO_LINKS_NO_LINKS_TT"] = "不将这个动作/事件链接到工作流",
	["WO_LINKS_SELECT"] = "选择一个要链接的工作流",
	["WO_LINKS_TO"] = "链接到了工作流",
	["WO_LINKS_TRIGGERS"] = "在这里，您可以将工作流程与该对象的具体事件链接起来.",
	["WO_NO"] = "没有工作流",
	["WO_PASTE"] = "粘贴工作流内容",
	["WO_PASTE_CONFIRM"] = "将这个工作流的内容替换为你先前复制的内容吗？",
	["WO_REMOVE_POPUP"] = "删除这个工作流 %s 吗?",
	["WO_SECURITY"] = "安全等级",
	["WO_SECURITY_HIGH"] = "高",
	["WO_SECURITY_HIGH_DETAILS"] = "这个效果是安全的，不会触发安全警告。",
	["WO_SECURITY_LOW"] = "低",
	["WO_SECURITY_LOW_DETAILS"] = "这个效果不安全而且可能是恶意的。它会根据你的安全设定触发安全警告。",
	["WO_SECURITY_NORMAL"] = "中等",
	["WO_SECURITY_NORMAL_DETAILS"] = "这个效果是安全的，但可能会带来不便。它会根据你的安全设定触发安全警告。",
	["WO_WO_SECURITY"] = "工作流安全性",
	["WO_WORKFLOW"] = "工作流"
};

TRP3_API.loc:GetLocale("zhCN"):AddTexts(L);
